//! Pure rendering of the memory index. No I/O, no network, no clock.
//!
//! `emit` is the enforcement point for `open_meta.status` / `open_meta.verified`,
//! because those keys live in the OPEN tier and nothing validates them at write
//! time (design §"The open-tier cost"). A missing or malformed key is therefore a
//! DEFECT that fails the command — never a value that quietly defaults.

use chrono::NaiveDate;
use uuid::Uuid;

pub const GENERATED_HEADER: &str = "<!-- GENERATED by `temper memory emit` — do not edit -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryEntry {
    pub id: Uuid,
    pub title: String,
    pub context_ref: String,
    pub status: String,
    pub verified: NaiveDate,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MemoryDefect {
    MissingStatus {
        id: Uuid,
        title: String,
    },
    MissingVerified {
        id: Uuid,
        title: String,
    },
    BadStatus {
        id: Uuid,
        title: String,
        found: String,
    },
    BadVerified {
        id: Uuid,
        title: String,
        found: String,
    },
}

impl std::fmt::Display for MemoryDefect {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingStatus { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.status is missing (expected \"active\" or \"superseded\")"
            ),
            Self::MissingVerified { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is missing (expected an ISO date, YYYY-MM-DD)"
            ),
            Self::BadStatus { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.status is {found:?} (expected \"active\" or \"superseded\")"
            ),
            Self::BadVerified { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is {found:?} (expected an ISO date, YYYY-MM-DD)"
            ),
        }
    }
}

fn open_str(open_meta: &serde_json::Value, key: &str) -> Option<String> {
    open_meta.get(key)?.as_str().map(str::to_owned)
}

/// Parse one metadata row into an entry, or the specific defect that stops the render.
///
/// `list_meta` returns `ResourceMetaListResponse { rows: Vec<ResourceDetail>, .. }`
/// (`crates/temper-workflow/src/types/managed_meta.rs:143-147`). `ResourceDetail`
/// is a `#[serde(flatten)]`ed `ResourceRow` plus the two meta tiers
/// (`crates/temper-workflow/src/types/resource.rs:187-197`), so identity fields
/// are reached through `.row`. `ResourceRow` carries no composed `context_ref` —
/// only `context_owner_ref` + `context_slug` (`resource.rs:36-42`), which this
/// composes into the `@owner/slug` form.
pub fn parse_entry(
    d: &temper_workflow::types::resource::ResourceDetail,
) -> Result<MemoryEntry, MemoryDefect> {
    let id = d.row.id.uuid();
    let title = d.row.title.clone();
    let om = d.open_meta.clone().unwrap_or(serde_json::Value::Null);

    let status = open_str(&om, "status").ok_or_else(|| MemoryDefect::MissingStatus {
        id,
        title: title.clone(),
    })?;
    if status != "active" && status != "superseded" {
        return Err(MemoryDefect::BadStatus {
            id,
            title,
            found: status,
        });
    }

    let raw = open_str(&om, "verified").ok_or_else(|| MemoryDefect::MissingVerified {
        id,
        title: title.clone(),
    })?;
    let verified =
        NaiveDate::parse_from_str(&raw, "%Y-%m-%d").map_err(|_| MemoryDefect::BadVerified {
            id,
            title: title.clone(),
            found: raw,
        })?;

    Ok(MemoryEntry {
        id,
        title,
        context_ref: match (&d.row.context_owner_ref, &d.row.context_slug) {
            (Some(owner), Some(slug)) => format!("{owner}/{slug}"),
            _ => String::new(),
        },
        status,
        verified,
    })
}

/// One memory that still lives only as a file on this machine.
///
/// It has no `id`, so it can carry no `temper://` link, and no `verified` date of the kind the
/// contract means — a file's mtime records when it was *written*, never that anyone re-checked
/// what it says. Both absences are represented by the type having no field for them, so a future
/// change cannot fill either with something plausible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalEntry {
    /// Bare filename, resolved relative to the index — the two sit in the same directory.
    pub filename: String,
    /// The curated title, read from the file's own frontmatter (stamped by
    /// [`super::harvest`]), never from the index this render is about to overwrite.
    pub title: String,
}

/// The un-migrated half of the index.
///
/// `untitled` is a count rather than a list because those files have no hook to render — but it
/// is carried rather than dropped, since a reader must be able to tell "this machine holds
/// nothing else" from "this machine holds four things I cannot name here".
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LocalIndex {
    pub entries: Vec<LocalEntry>,
    pub untitled: usize,
}

impl LocalIndex {
    /// Every local file this machine carries, listed or not — what the section heading counts.
    fn total(&self) -> usize {
        self.entries.len() + self.untitled
    }

    fn is_empty(&self) -> bool {
        self.total() == 0
    }
}

/// Render the index. `today` is a parameter, never the clock — a renderer that
/// reads the clock cannot be tested deterministically.
///
/// The un-migrated section is appended only when there is something local to say. A machine that
/// has finished migrating renders byte-for-byte what it rendered before the union existed, which
/// is what keeps this transitional rather than a permanent second code path.
pub fn render_index(
    entries: &[MemoryEntry],
    local: &LocalIndex,
    today: NaiveDate,
    stale_after_days: u32,
) -> String {
    let mut out = render_migrated(entries, today, stale_after_days);
    if !local.is_empty() {
        out.push_str(&render_local(local));
    }
    out
}

/// The un-migrated section: a heading that counts what the machine carries, a preamble stating
/// what these entries are *not*, and one marked line per file it can name.
fn render_local(local: &LocalIndex) -> String {
    let total = local.total();
    let mut out = format!(
        "\n## Not yet migrated — local to this machine ({total} file{})\n\n\
         Not in Temper: no id, no verified date, readable only on this machine.\n\
         Run `temper memory migrate` to move them.\n\n",
        if total == 1 { "" } else { "s" }
    );

    for e in &local.entries {
        out.push_str(&format!("- [{}](./{})  [local]\n", e.title, e.filename));
    }

    // Stated, never merely absent: what the index omits, it says it has omitted.
    if local.untitled > 0 {
        out.push_str(&format!(
            "\n{} further local file{} carr{} no title and {} not listed — \
             `temper memory status` names them.\n",
            local.untitled,
            if local.untitled == 1 { "" } else { "s" },
            if local.untitled == 1 { "ies" } else { "y" },
            if local.untitled == 1 { "is" } else { "are" },
        ));
    }
    out
}

fn render_migrated(entries: &[MemoryEntry], today: NaiveDate, stale_after_days: u32) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n\n# Memory index\n");

    let mut contexts: Vec<&str> = entries
        .iter()
        .filter(|e| e.status == "active")
        .map(|e| e.context_ref.as_str())
        .collect();
    contexts.sort_unstable();
    contexts.dedup();

    for ctx in contexts {
        out.push_str(&format!("\n## {ctx}\n\n"));
        for e in entries
            .iter()
            .filter(|e| e.status == "active" && e.context_ref == ctx)
        {
            let age = (today - e.verified).num_days();
            // UNEXAMINED, never STALE/WRONG: an old date means nobody has checked,
            // which is not evidence the claim is false.
            let mark = if age > i64::from(stale_after_days) {
                format!("[verified {} — UNEXAMINED {}d]", e.verified, age)
            } else {
                format!("[verified {}]", e.verified)
            };
            // The TITLE is the hook this index carries, and nothing else is. `descriptor` is
            // deliberately absent: its job is FTS weight-D searchability on the resource, and
            // printing it here paid for that job twice — measured on the real corpus, ~279 bytes
            // per line against ~120, i.e. ~49 KB for the full set where the hand-written file it
            // replaces was 19.3 KB. This file is loaded every session; every byte is paid 178
            // times. (`[decided — 2026-08-01, Pete]`)
            out.push_str(&format!("- [{}](temper://{})  {}\n", e.title, e.id, mark));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{DateTime, Utc};
    use serde_json::json;
    use temper_core::types::ids::{ProfileId, ResourceId};
    use temper_workflow::types::resource::{BodyStorage, IngestState, ResourceDetail, ResourceRow};

    fn d(s: &str) -> NaiveDate {
        NaiveDate::parse_from_str(s, "%Y-%m-%d").unwrap()
    }

    fn entry(title: &str, status: &str, verified: &str) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::nil(),
            title: title.to_string(),
            context_ref: "@me/temper".to_string(),
            status: status.to_string(),
            verified: d(verified),
        }
    }

    /// Build a `ResourceDetail` wrapping a real `ResourceRow`, with `open_meta`
    /// carrying `status`/`verified` only when the corresponding argument is
    /// `Some` — omitting a key entirely (not setting it to null) is what a
    /// real un-migrated memory resource looks like.
    fn row_with(status: Option<&str>, verified: Option<&str>) -> ResourceDetail {
        let mut open = serde_json::Map::new();
        if let Some(s) = status {
            open.insert("status".to_string(), json!(s));
        }
        if let Some(v) = verified {
            open.insert("verified".to_string(), json!(v));
        }

        let row = ResourceRow {
            id: ResourceId::from(Uuid::nil()),
            kb_context_id: None,
            origin_uri: String::new(),
            title: "a memory".to_string(),
            originator_profile_id: ProfileId::from(Uuid::nil()),
            owner_profile_id: ProfileId::from(Uuid::nil()),
            is_active: true,
            created: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            updated: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            context_name: None,
            doc_type_name: "memory".to_string(),
            owner_handle: "someone".to_string(),
            context_slug: Some("temper".to_string()),
            context_owner_ref: Some("@me".to_string()),
            cogmap_id: None,
            cogmap_name: None,
            stage: None,
            seq: None,
            mode: None,
            effort: None,
            body_hash: None,
            ingest_state: Some(IngestState::Complete),
            body_storage: Some(BodyStorage::Derived),
        };

        ResourceDetail {
            row,
            managed_meta: None,
            open_meta: Some(serde_json::Value::Object(open)),
        }
    }

    fn local(filename: &str, title: &str) -> LocalEntry {
        LocalEntry {
            filename: filename.to_string(),
            title: title.to_string(),
        }
    }

    /// The union is transitional machinery, and machinery that leaves a residue after the thing
    /// it was for is finished has become permanent. With nothing local left, the render must be
    /// what it was before the union existed — asserted against the whole string, since a stray
    /// blank line or trailing newline is exactly the kind of difference that would make every
    /// future `check` report drift on a machine that finished migrating.
    #[test]
    fn an_empty_local_set_renders_exactly_what_it_rendered_before_the_union() {
        let out = render_index(
            &[entry("a memory", "active", "2026-07-20")],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert_eq!(
            out,
            "<!-- GENERATED by `temper memory emit` — do not edit -->\n\n\
             # Memory index\n\n\
             ## @me/temper\n\n\
             - [a memory](temper://00000000-0000-0000-0000-000000000000)  [verified 2026-07-20]\n"
        );
    }

    /// The task's hard constraint: an un-migrated entry must not look migrated. Three signals
    /// carry it, and the per-line ones matter most — a line quoted or grepped out of its section
    /// keeps the distinction that the heading alone would have lost.
    #[test]
    fn an_unmigrated_entry_never_looks_migrated() {
        let out = render_index(
            &[entry("migrated one", "active", "2026-07-20")],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 0,
            },
            d("2026-08-01"),
            90,
        );
        let line = out
            .lines()
            .find(|l| l.contains("local one"))
            .expect("the local entry must render");
        assert!(
            line.contains("(./project_x.md)"),
            "the link must resolve to the file on disk: {line}"
        );
        assert!(
            !line.contains("temper://"),
            "an un-migrated entry has no resource id and must not appear to: {line}"
        );
        assert!(
            line.contains("[local]"),
            "the per-line marker is what survives being quoted out of context: {line}"
        );
    }

    /// A local file's date would have to come from its mtime or its `modified` — neither of which
    /// is a record that anyone re-checked the claim. Printing either in the same column the
    /// migrated entries use for `verified` would manufacture exactly the false certification the
    /// goal's `a-claim-must-never-read-as-checked-when-nobody-checked-it` forbids.
    #[test]
    fn an_unmigrated_entry_is_given_no_verified_date_at_all() {
        let out = render_index(
            &[],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 0,
            },
            d("2026-08-01"),
            90,
        );
        let line = out
            .lines()
            .find(|l| l.contains("local one"))
            .expect("the local entry must render");
        assert!(
            !line.contains("verified") && !line.contains("UNEXAMINED"),
            "no date may be fabricated for a memory nobody has checked: {line}"
        );
    }

    /// `the-index-stays-readable-as-the-corpus-grows` requires that what the index omits, it says
    /// it has omitted. The four files no index link names are not listed — they never were — but
    /// a reader must not conclude from their absence that this machine carries nothing else.
    #[test]
    fn files_omitted_for_want_of_a_title_are_counted_never_silently_dropped() {
        let out = render_index(
            &[],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 4,
            },
            d("2026-08-01"),
            90,
        );
        assert!(
            out.contains("(5 files)"),
            "the heading counts what the machine carries, not what it could name: {out}"
        );
        assert!(
            out.contains("4 further"),
            "the omission must be stated, with its count: {out}"
        );
        assert!(
            out.contains("temper memory status"),
            "and must say where the omitted ones can be named: {out}"
        );
    }

    /// The acceptance criterion, at the real ratio rather than a two-element fixture: taking the
    /// index over after a partial migration must lose no entry a reader had before. 69 migrated
    /// and 114 local is this machine's actual state on 2026-08-01.
    #[test]
    fn no_entry_is_lost_at_the_real_migrated_to_local_ratio() {
        let migrated: Vec<MemoryEntry> = (0..69)
            .map(|i| entry(&format!("migrated {i}"), "active", "2026-07-20"))
            .collect();
        let locals: Vec<LocalEntry> = (0..114)
            .map(|i| local(&format!("project_{i}.md"), &format!("local {i}")))
            .collect();

        let out = render_index(
            &migrated,
            &LocalIndex {
                entries: locals,
                untitled: 0,
            },
            d("2026-08-01"),
            90,
        );

        for i in 0..69 {
            assert!(out.contains(&format!("migrated {i}]")), "lost migrated {i}");
        }
        for i in 0..114 {
            assert!(out.contains(&format!("local {i}]")), "lost local {i}");
        }
        assert_eq!(
            out.lines().filter(|l| l.starts_with("- [")).count(),
            183,
            "every one of the 183 entries renders exactly once"
        );
    }

    #[test]
    fn superseded_memories_are_absent_from_the_index() {
        let out = render_index(
            &[
                entry("live one", "active", "2026-08-01"),
                entry("dead one", "superseded", "2026-08-01"),
            ],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert!(out.contains("live one"));
        assert!(
            !out.contains("dead one"),
            "superseded memories must not render"
        );
    }

    #[test]
    fn a_stale_entry_is_marked_unexamined_never_false() {
        let out = render_index(
            &[entry("old claim", "active", "2026-01-01")],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert!(
            out.contains("UNEXAMINED"),
            "an over-threshold entry is marked"
        );
        for word in ["STALE", "WRONG", "FALSE", "OUTDATED"] {
            assert!(
                !out.contains(word),
                "must not imply the claim is false, found {word}"
            );
        }
    }

    /// The index is loaded into context every session, so every byte on a line is paid for 178
    /// times. `open_meta.descriptor`'s job is FTS weight-D searchability — printing it here pays
    /// for that job a second time and, measured against the real corpus on 2026-08-01, took the
    /// mean line from ~120 to 279 bytes: ~49 KB for the full set against a hand-written file of
    /// 19.3 KB. The descriptor stays on the resource and stays searchable; it just stops being
    /// rendered.
    #[test]
    fn the_index_does_not_print_the_descriptor() {
        let out = render_index(
            &[entry("a title", "active", "2026-07-20")],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert!(
            !out.contains("hook text"),
            "the descriptor is searchable on the resource; the index carries the title: {out}"
        );
        assert!(
            out.contains("a title"),
            "the title is the hook the index carries"
        );
    }

    #[test]
    fn a_fresh_entry_carries_its_verified_date_and_no_marker() {
        let out = render_index(
            &[entry("fresh", "active", "2026-07-20")],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert!(out.contains("[verified 2026-07-20]"));
        assert!(!out.contains("UNEXAMINED"));
    }

    #[test]
    fn the_index_declares_itself_generated() {
        let out = render_index(
            &[entry("x", "active", "2026-08-01")],
            &LocalIndex::default(),
            d("2026-08-01"),
            90,
        );
        assert!(out.starts_with("<!-- GENERATED by `temper memory emit` — do not edit -->"));
    }

    #[test]
    fn entries_group_under_their_context() {
        let mut a = entry("from temper", "active", "2026-08-01");
        a.context_ref = "@me/temper".into();
        let mut b = entry("from agreements", "active", "2026-08-01");
        b.context_ref = "@me/working-agreements".into();
        let out = render_index(&[a, b], &LocalIndex::default(), d("2026-08-01"), 90);
        assert!(out.contains("## @me/temper"));
        assert!(out.contains("## @me/working-agreements"));
    }

    #[test]
    fn a_memory_missing_status_is_a_defect_not_a_default() {
        let row = row_with(None, Some("2026-08-01"));
        assert!(
            matches!(parse_entry(&row), Err(MemoryDefect::MissingStatus { .. })),
            "emit is the enforcement point; a missing key must never silently default to active"
        );
    }

    #[test]
    fn a_memory_with_an_unknown_status_is_a_defect() {
        let row = row_with(Some("activ"), Some("2026-08-01"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadStatus { .. })
        ));
    }

    #[test]
    fn a_memory_with_an_unparseable_verified_date_is_a_defect() {
        let row = row_with(Some("active"), Some("last tuesday"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadVerified { .. })
        ));
    }
}
