//! Pure rendering of the memory index. No I/O, no network, no clock.
//!
//! `emit` is the enforcement point for `open_meta.status` / `open_meta.verified`,
//! because those keys live in the OPEN tier and nothing validates them at write
//! time. A missing or malformed key is therefore a DEFECT that fails the command —
//! never a value that quietly defaults.

use chrono::NaiveDate;
use uuid::Uuid;

pub const GENERATED_HEADER: &str = "<!-- GENERATED by `temper memory emit` — do not edit -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryEntry {
    pub id: Uuid,
    pub title: String,
    pub context_ref: String,
    pub descriptor: Option<String>,
    pub status: String,
    pub verified: NaiveDate,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MemoryDefect {
    MissingStatus {
        id: Uuid,
        title: String,
    },
    MissingVerified {
        id: Uuid,
        title: String,
    },
    BadStatus {
        id: Uuid,
        title: String,
        found: String,
    },
    BadVerified {
        id: Uuid,
        title: String,
        found: String,
    },
}

impl std::fmt::Display for MemoryDefect {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingStatus { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.status is missing (expected \"active\" or \"superseded\")"
            ),
            Self::MissingVerified { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is missing (expected an ISO date, YYYY-MM-DD)"
            ),
            Self::BadStatus { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.status is {found:?} (expected \"active\" or \"superseded\")"
            ),
            Self::BadVerified { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is {found:?} (expected an ISO date, YYYY-MM-DD)"
            ),
        }
    }
}

fn open_str(open_meta: &serde_json::Value, key: &str) -> Option<String> {
    open_meta.get(key)?.as_str().map(str::to_owned)
}

/// Parse one metadata row into an entry, or the specific defect that stops the render.
///
/// `list_meta` returns `ResourceMetaListResponse { rows: Vec<ResourceDetail>, .. }`
/// (`crates/temper-workflow/src/types/managed_meta.rs:143-147`). `ResourceDetail`
/// is a `#[serde(flatten)]`ed `ResourceRow` plus the two meta tiers
/// (`crates/temper-workflow/src/types/resource.rs:187-197`), so identity fields
/// are reached through `.row`. `ResourceRow` carries no composed `context_ref` —
/// only `context_owner_ref` + `context_slug` (`resource.rs:36-42`), which this
/// composes into the `@owner/slug` form.
pub fn parse_entry(
    d: &temper_workflow::types::resource::ResourceDetail,
) -> Result<MemoryEntry, MemoryDefect> {
    let id = d.row.id.uuid();
    let title = d.row.title.clone();
    let om = d.open_meta.clone().unwrap_or(serde_json::Value::Null);

    let status = open_str(&om, "status").ok_or_else(|| MemoryDefect::MissingStatus {
        id,
        title: title.clone(),
    })?;
    if status != "active" && status != "superseded" {
        return Err(MemoryDefect::BadStatus {
            id,
            title,
            found: status,
        });
    }

    let raw = open_str(&om, "verified").ok_or_else(|| MemoryDefect::MissingVerified {
        id,
        title: title.clone(),
    })?;
    let verified =
        NaiveDate::parse_from_str(&raw, "%Y-%m-%d").map_err(|_| MemoryDefect::BadVerified {
            id,
            title: title.clone(),
            found: raw,
        })?;

    Ok(MemoryEntry {
        id,
        title,
        context_ref: match (&d.row.context_owner_ref, &d.row.context_slug) {
            (Some(owner), Some(slug)) => format!("{owner}/{slug}"),
            _ => String::new(),
        },
        descriptor: open_str(&om, "descriptor"),
        status,
        verified,
    })
}

/// Render the index. `today` is a parameter, never the clock — a renderer that
/// reads the clock cannot be tested deterministically.
pub fn render_index(entries: &[MemoryEntry], today: NaiveDate, stale_after_days: u32) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n\n# Memory index\n");

    let mut contexts: Vec<&str> = entries
        .iter()
        .filter(|e| e.status == "active")
        .map(|e| e.context_ref.as_str())
        .collect();
    contexts.sort_unstable();
    contexts.dedup();

    for ctx in contexts {
        out.push_str(&format!("\n## {ctx}\n\n"));
        for e in entries
            .iter()
            .filter(|e| e.status == "active" && e.context_ref == ctx)
        {
            let hook = e.descriptor.as_deref().unwrap_or("");
            let age = (today - e.verified).num_days();
            // UNEXAMINED, never STALE/WRONG: an old date means nobody has checked,
            // which is not evidence the claim is false.
            let mark = if age > i64::from(stale_after_days) {
                format!("[verified {} — UNEXAMINED {}d]", e.verified, age)
            } else {
                format!("[verified {}]", e.verified)
            };
            let sep = if hook.is_empty() { "" } else { " — " };
            out.push_str(&format!(
                "- [{}](temper://{}){}{}  {}\n",
                e.title, e.id, sep, hook, mark
            ));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{DateTime, Utc};
    use serde_json::json;
    use temper_core::types::ids::{ProfileId, ResourceId};
    use temper_workflow::types::resource::{BodyStorage, IngestState, ResourceDetail, ResourceRow};

    fn d(s: &str) -> NaiveDate {
        NaiveDate::parse_from_str(s, "%Y-%m-%d").unwrap()
    }

    fn entry(title: &str, status: &str, verified: &str) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::nil(),
            title: title.to_string(),
            context_ref: "@me/temper".to_string(),
            descriptor: Some("hook text".to_string()),
            status: status.to_string(),
            verified: d(verified),
        }
    }

    /// Build a `ResourceDetail` wrapping a real `ResourceRow`, with `open_meta`
    /// carrying `status`/`verified` only when the corresponding argument is
    /// `Some` — omitting a key entirely (not setting it to null) is what a
    /// real un-migrated memory resource looks like.
    fn row_with(status: Option<&str>, verified: Option<&str>) -> ResourceDetail {
        let mut open = serde_json::Map::new();
        if let Some(s) = status {
            open.insert("status".to_string(), json!(s));
        }
        if let Some(v) = verified {
            open.insert("verified".to_string(), json!(v));
        }

        let row = ResourceRow {
            id: ResourceId::from(Uuid::nil()),
            kb_context_id: None,
            origin_uri: String::new(),
            title: "a memory".to_string(),
            originator_profile_id: ProfileId::from(Uuid::nil()),
            owner_profile_id: ProfileId::from(Uuid::nil()),
            is_active: true,
            created: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            updated: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            context_name: None,
            doc_type_name: "memory".to_string(),
            owner_handle: "someone".to_string(),
            context_slug: Some("temper".to_string()),
            context_owner_ref: Some("@me".to_string()),
            cogmap_id: None,
            cogmap_name: None,
            stage: None,
            seq: None,
            mode: None,
            effort: None,
            body_hash: None,
            ingest_state: Some(IngestState::Complete),
            body_storage: Some(BodyStorage::Derived),
        };

        ResourceDetail {
            row,
            managed_meta: None,
            open_meta: Some(serde_json::Value::Object(open)),
        }
    }

    #[test]
    fn superseded_memories_are_absent_from_the_index() {
        let out = render_index(
            &[
                entry("live one", "active", "2026-08-01"),
                entry("dead one", "superseded", "2026-08-01"),
            ],
            d("2026-08-01"),
            90,
        );
        assert!(out.contains("live one"));
        assert!(
            !out.contains("dead one"),
            "superseded memories must not render"
        );
    }

    #[test]
    fn a_stale_entry_is_marked_unexamined_never_false() {
        let out = render_index(
            &[entry("old claim", "active", "2026-01-01")],
            d("2026-08-01"),
            90,
        );
        assert!(
            out.contains("UNEXAMINED"),
            "an over-threshold entry is marked"
        );
        for word in ["STALE", "WRONG", "FALSE", "OUTDATED"] {
            assert!(
                !out.contains(word),
                "must not imply the claim is false, found {word}"
            );
        }
    }

    #[test]
    fn a_fresh_entry_carries_its_verified_date_and_no_marker() {
        let out = render_index(
            &[entry("fresh", "active", "2026-07-20")],
            d("2026-08-01"),
            90,
        );
        assert!(out.contains("[verified 2026-07-20]"));
        assert!(!out.contains("UNEXAMINED"));
    }

    #[test]
    fn the_index_declares_itself_generated() {
        let out = render_index(&[entry("x", "active", "2026-08-01")], d("2026-08-01"), 90);
        assert!(out.starts_with("<!-- GENERATED by `temper memory emit` — do not edit -->"));
    }

    #[test]
    fn entries_group_under_their_context() {
        let mut a = entry("from temper", "active", "2026-08-01");
        a.context_ref = "@me/temper".into();
        let mut b = entry("from agreements", "active", "2026-08-01");
        b.context_ref = "@me/working-agreements".into();
        let out = render_index(&[a, b], d("2026-08-01"), 90);
        assert!(out.contains("## @me/temper"));
        assert!(out.contains("## @me/working-agreements"));
    }

    #[test]
    fn a_memory_missing_status_is_a_defect_not_a_default() {
        let row = row_with(None, Some("2026-08-01"));
        assert!(
            matches!(parse_entry(&row), Err(MemoryDefect::MissingStatus { .. })),
            "emit is the enforcement point; a missing key must never silently default to active"
        );
    }

    #[test]
    fn a_memory_with_an_unknown_status_is_a_defect() {
        let row = row_with(Some("activ"), Some("2026-08-01"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadStatus { .. })
        ));
    }

    #[test]
    fn a_memory_with_an_unparseable_verified_date_is_a_defect() {
        let row = row_with(Some("active"), Some("last tuesday"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadVerified { .. })
        ));
    }
}
