//! Pure rendering of the memory index. No I/O, no network, no clock.
//!
//! `emit` is the enforcement point for `open_meta.status` / `open_meta.verified`,
//! because those keys live in the OPEN tier and nothing validates them at write
//! time (design §"The open-tier cost"). A missing or malformed key is therefore a
//! DEFECT that fails the command — never a value that quietly defaults.
//!
//! **`open_meta.reinforced` is the deliberate exception, and the line between them is what each
//! key holds up.** `status` and `verified` are the fields the render's own claims depend on, so
//! refusing the whole index on one is proportionate. `reinforced` only decides whether a memory
//! renders on its own line or inside the tail — so a malformed one is a SOFT class that `status`
//! names and `emit` renders straight through (`[decided — 2026-08-02, Pete]`). See
//! [`reinforcement_of`].

use std::collections::HashSet;

use chrono::NaiveDate;
use uuid::Uuid;

pub const GENERATED_HEADER: &str = "<!-- GENERATED by `temper memory emit` — do not edit -->";

/// What the index tells a reader about itself, before the first entry.
///
/// **The hand-written index it replaces carried this and the render did not, which is a loss the
/// takeover would otherwise have paid silently.** A session loads this file cold, with no other
/// account of what these lines are; without a preamble it gets a list of titles and has to infer
/// that a title is a hook rather than the memory, that the link is resolvable at all, and what an
/// old date does and does not mean. Every one of those is a thing the file can simply say.
///
/// Two lines, once — deliberately not per-entry. The per-line byte budget is spent on the title
/// and nothing else (see `render_migrated`); this is the one place the index is allowed to
/// explain itself, because its cost is paid once rather than 183 times.
pub const READING_GUIDANCE: &str = "\
> **Hooks only — a line is a title, not the memory.** Read the resource before acting on one: \
`temper resource show <id>`, or the `get_resource` MCP tool.\n\
> A `verified` date far in the past means nobody has re-checked the claim — never that it is \
wrong.\n";

/// How the index is to be rendered — the three policy values that are not the entries themselves.
///
/// A params struct rather than three positional arguments because they are all scalars of the same
/// shape ("a date, a number, a number") and a call site reading `(…, d("2026-08-01"), 90, None)`
/// says nothing about which is which.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenderPolicy {
    /// Always a parameter, never the clock — a renderer that reads the clock cannot be tested
    /// deterministically.
    pub today: NaiveDate,
    /// Days after which a `verified` date renders as UNEXAMINED.
    pub stale_after_days: u32,
    /// Distinct reinforcement dates required to render on an individual line. `None` — the only
    /// value with no guess in it — means every active memory renders individually, exactly as it
    /// did before this field existed. See [`temper_core::types::config::MemoryConfig`].
    pub reinforced_min: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryEntry {
    pub id: Uuid,
    pub title: String,
    pub context_ref: String,
    pub status: String,
    pub verified: NaiveDate,
    /// Distinct days this memory did work, ascending. Empty is ordinary — it means nothing has
    /// reinforced this memory yet, which is the state every memory starts in and the state the
    /// whole corpus is in until the convention has been used for a while.
    ///
    /// **A malformed `open_meta.reinforced` also lands here as empty**, deliberately: see
    /// [`reinforcement_of`].
    pub reinforced: Vec<NaiveDate>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MemoryDefect {
    MissingStatus {
        id: Uuid,
        title: String,
    },
    MissingVerified {
        id: Uuid,
        title: String,
    },
    BadStatus {
        id: Uuid,
        title: String,
        found: String,
    },
    BadVerified {
        id: Uuid,
        title: String,
        found: String,
    },
}

impl std::fmt::Display for MemoryDefect {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingStatus { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.status is missing (expected \"active\" or \"superseded\")"
            ),
            Self::MissingVerified { id, title } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is missing (expected an ISO date, YYYY-MM-DD)"
            ),
            Self::BadStatus { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.status is {found:?} (expected \"active\" or \"superseded\")"
            ),
            Self::BadVerified { id, title, found } => write!(
                f,
                "{id} \"{title}\": open_meta.verified is {found:?} (expected an ISO date, YYYY-MM-DD)"
            ),
        }
    }
}

fn open_str(open_meta: &serde_json::Value, key: &str) -> Option<String> {
    open_meta.get(key)?.as_str().map(str::to_owned)
}

/// What `open_meta.reinforced` was found to say, and — separately — whether it was well-formed.
///
/// The two travel together rather than as a `Result` because they are **not** alternatives: a
/// memory can be both unreinforced and malformed, and the render needs the first while `status`
/// needs the second.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Reinforcement {
    /// Distinct dates, ascending. Empty when the key is absent — and also when it is malformed.
    pub dates: Vec<NaiveDate>,
    /// A human-readable account of *what* was wrong, when something was. `None` covers both "the
    /// key is absent" and "the key is a well-formed list of dates" — neither is a report.
    pub malformed: Option<String>,
}

impl Reinforcement {
    /// Recency: the most recent date, or `None` for a memory nothing has reinforced.
    pub fn last(&self) -> Option<NaiveDate> {
        self.dates.last().copied()
    }
}

/// Read `open_meta.reinforced` — **a SOFT class, never a [`MemoryDefect`]**
/// (`[decided — 2026-08-02, Pete]`).
///
/// `status` and `verified` are the fields the render's own claims depend on, so refusing the whole
/// index on one is proportionate *there*. `reinforced` only decides ordering, so a bad value must
/// not take the index down with it: `status` names it and `emit` renders straight through.
///
/// **A malformed value yields NO dates, not the salvageable subset.** Keeping the parseable dates
/// out of `["2026-05-14", "last tuesday"]` was the tempting reading and it is the wrong one: the
/// accepted consequence on record is that *"a mistyped date silently demotes a memory into the
/// tail, which is recoverable because demotion is never deletion"* — and salvaging would make that
/// sentence false in exactly the mixed case, leaving the typo invisible instead of visibly
/// demoting the memory to where `status` explains it. Louder, and already decided.
///
/// Absent is not malformed. Every memory in existence is in that state today.
pub fn reinforcement_of(d: &temper_workflow::types::resource::ResourceDetail) -> Reinforcement {
    let Some(raw) = d.open_meta.as_ref().and_then(|om| om.get("reinforced")) else {
        return Reinforcement::default();
    };

    let Some(items) = raw.as_array() else {
        return Reinforcement {
            dates: Vec::new(),
            malformed: Some(format!(
                "open_meta.reinforced is {raw} (expected a list of ISO dates, YYYY-MM-DD)"
            )),
        };
    };

    let mut dates = Vec::with_capacity(items.len());
    let mut bad: Vec<String> = Vec::new();
    for item in items {
        match item
            .as_str()
            .and_then(|s| NaiveDate::parse_from_str(s, "%Y-%m-%d").ok())
        {
            Some(date) => dates.push(date),
            None => bad.push(item.to_string()),
        }
    }

    if !bad.is_empty() {
        return Reinforcement {
            dates: Vec::new(),
            malformed: Some(format!(
                "open_meta.reinforced holds {} unparseable entr{}: {} (expected ISO dates, \
                 YYYY-MM-DD)",
                bad.len(),
                if bad.len() == 1 { "y" } else { "ies" },
                bad.join(", "),
            )),
        };
    }

    // Distinct and ascending. `union_list` already dedups server-side by structural equality, so
    // this is not the primary guard — it is what makes `strength()` honest about a list that
    // reached storage some other way (a hand-written `--open-meta`, an import).
    dates.sort_unstable();
    dates.dedup();
    Reinforcement {
        dates,
        malformed: None,
    }
}

/// Parse one metadata row into an entry, or the specific defect that stops the render.
///
/// `list_meta` returns `ResourceMetaListResponse { rows: Vec<ResourceDetail>, .. }`
/// (`crates/temper-workflow/src/types/managed_meta.rs:143-147`). `ResourceDetail`
/// is a `#[serde(flatten)]`ed `ResourceRow` plus the two meta tiers
/// (`crates/temper-workflow/src/types/resource.rs:187-197`), so identity fields
/// are reached through `.row`. `ResourceRow` carries no composed `context_ref` —
/// only `context_owner_ref` + `context_slug` (`resource.rs:36-42`), which this
/// composes into the `@owner/slug` form.
pub fn parse_entry(
    d: &temper_workflow::types::resource::ResourceDetail,
) -> Result<MemoryEntry, MemoryDefect> {
    let id = d.row.id.uuid();
    let title = d.row.title.clone();
    let om = d.open_meta.clone().unwrap_or(serde_json::Value::Null);

    let status = open_str(&om, "status").ok_or_else(|| MemoryDefect::MissingStatus {
        id,
        title: title.clone(),
    })?;
    if status != "active" && status != "superseded" {
        return Err(MemoryDefect::BadStatus {
            id,
            title,
            found: status,
        });
    }

    let raw = open_str(&om, "verified").ok_or_else(|| MemoryDefect::MissingVerified {
        id,
        title: title.clone(),
    })?;
    let verified =
        NaiveDate::parse_from_str(&raw, "%Y-%m-%d").map_err(|_| MemoryDefect::BadVerified {
            id,
            title: title.clone(),
            found: raw,
        })?;

    Ok(MemoryEntry {
        id,
        title,
        context_ref: match (&d.row.context_owner_ref, &d.row.context_slug) {
            (Some(owner), Some(slug)) => format!("{owner}/{slug}"),
            _ => String::new(),
        },
        status,
        verified,
        // Soft by construction: whatever `reinforcement_of` made of the key, this row still
        // parses. The `malformed` half is dropped here and read by `status`, which is the surface
        // that reports it.
        reinforced: reinforcement_of(d).dates,
    })
}

/// One memory that still lives only as a file on this machine.
///
/// It has no `id`, so it can carry no resolvable resource link, and no `verified` date of the kind the
/// contract means — a file's mtime records when it was *written*, never that anyone re-checked
/// what it says. Both absences are represented by the type having no field for them, so a future
/// change cannot fill either with something plausible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalEntry {
    /// Bare filename, resolved relative to the index — the two sit in the same directory.
    pub filename: String,
    /// The curated title, read from the file's own frontmatter (stamped by
    /// [`super::harvest`]), never from the index this render is about to overwrite.
    pub title: String,
}

/// The un-migrated half of the index.
///
/// `untitled` is a count rather than a list because those files have no hook to render — but it
/// is carried rather than dropped, since a reader must be able to tell "this machine holds
/// nothing else" from "this machine holds four things I cannot name here".
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LocalIndex {
    pub entries: Vec<LocalEntry>,
    pub untitled: usize,
}

impl LocalIndex {
    /// Every local file this machine carries, listed or not — what the section heading counts.
    fn total(&self) -> usize {
        self.entries.len() + self.untitled
    }

    fn is_empty(&self) -> bool {
        self.total() == 0
    }
}

/// One principle and the memories that evidence it — the grouping the index sections by.
///
/// **Membership is read from edges, never from a field on the memory and never from a file anyone
/// maintains.** The edge is asserted memory → principle (`express`/`evidences`); this is the
/// principle's side of it, which is where the render reads because there are eight principles and
/// ~300 memories. Direction of *authoring* and direction of *reading* are deliberately opposite:
/// asserting from the memory is incidental to writing one, while asserting from the principle
/// would be filing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrincipleSection {
    pub id: Uuid,
    pub title: String,
    /// The section preamble — see [`statement_of`]. `None` renders a section with no preamble
    /// rather than a guessed one.
    pub statement: Option<String>,
    /// Ids of the memories carrying an `evidences` edge to this principle.
    pub members: Vec<Uuid>,
}

/// The preamble a principle contributes: **the first paragraph of its body, never the whole
/// body.**
///
/// Measured on the real corpus (2026-08-02): eight full bodies are 11,853 bytes against an index
/// of 37,159, so rendering them whole would add ~32% to a file loaded every session. The eight
/// first paragraphs are **1,706 bytes** — within 4% of the 1,638 the hand-written index spent on
/// exactly this job, which is the strongest available evidence that the first paragraph *is* the
/// statement and the rest is elaboration.
///
/// It is also not merely a size argument. Each body continues into a list of recurring shapes
/// whose bullets **are** the memories rendered directly beneath it, so the whole body prints the
/// section twice in two voices. The elaboration stays one `temper resource show` away.
///
/// **A body that does not open with prose yields `None`, never a fragment.** A heading, a list
/// item, a quote or a table row would render as a piece of structure torn out of its context and
/// presented as a claim — worse than no preamble, because it reads like one.
pub fn statement_of(body: &str) -> Option<String> {
    let first = body.trim_start().split("\n\n").next()?.trim();
    let opener = first.chars().next()?;
    if matches!(opener, '#' | '-' | '*' | '>' | '|' | '+' | '=') {
        return None;
    }
    // An ordered-list opener (`1.`, `2)`) is structure too, and is the one that does not announce
    // itself with a punctuation character.
    let mut digits = first.chars().take_while(char::is_ascii_digit).count();
    if digits > 0 {
        if digits > first.len() {
            digits = first.len();
        }
        if matches!(first[digits..].chars().next(), Some('.' | ')')) {
            return None;
        }
    }
    Some(first.to_string())
}

/// Render the index.
///
/// **Grouping by principle is applied when there is a grouping to apply, and the flat render is
/// the fallback rather than a legacy path.** With no principles, or none of them carrying a live
/// member, this renders byte-for-byte what it rendered before principles existed — which is what
/// makes the feature degrade instead of breaking the one file a cold session depends on.
///
/// The un-migrated section is appended only when there is something local to say. A machine that
/// has finished migrating renders byte-for-byte what it rendered before the union existed, which
/// is what keeps this transitional rather than a permanent second code path.
pub fn render_index(
    entries: &[MemoryEntry],
    local: &LocalIndex,
    principles: &[PrincipleSection],
    policy: RenderPolicy,
) -> String {
    let grouped: Vec<&PrincipleSection> = principles
        .iter()
        .filter(|p| p.members.iter().any(|id| is_live_member(entries, *id)))
        .collect();

    let mut out = if grouped.is_empty() {
        render_migrated(entries, policy)
    } else {
        render_by_principle(entries, &grouped, policy)
    };
    if !local.is_empty() {
        out.push_str(&render_local(local));
    }
    out
}

/// Does `id` name an entry this render would show? A principle whose every member is superseded
/// contributes no section — an empty heading with a preamble under it costs bytes to say nothing.
fn is_live_member(entries: &[MemoryEntry], id: Uuid) -> bool {
    entries.iter().any(|e| e.id == id && e.status == "active")
}

/// The un-migrated section: a heading that counts what the machine carries, a preamble stating
/// what these entries are *not*, and one marked line per file it can name.
fn render_local(local: &LocalIndex) -> String {
    let total = local.total();
    let mut out = format!(
        "\n## Not yet migrated — local to this machine ({total} file{})\n\n\
         Not in Temper: no id, no verified date, readable only on this machine.\n",
        if total == 1 { "" } else { "s" }
    );

    // **Only where it is true of something listed.** `migrate` moves a file by its title, so once
    // every remaining local file is untitled — the terminal state of a transition — this sends the
    // reader to a command that skips all of them without explaining itself.
    if !local.entries.is_empty() {
        out.push_str("Run `temper memory migrate` to move them.\n\n");
        for e in &local.entries {
            out.push_str(&format!("- [{}](./{})  [local]\n", e.title, e.filename));
        }
    }

    // Stated, never merely absent: what the index omits, it says it has omitted — and says why the
    // obvious remedy will not reach them, since "run migrate" is what a reader would try next.
    if local.untitled > 0 {
        let (plural, verb, is_are) = if local.untitled == 1 {
            ("", "ies", "is")
        } else {
            ("s", "y", "are")
        };
        if !local.entries.is_empty() {
            out.push('\n');
        }
        out.push_str(&format!(
            "{} further local file{plural} carr{verb} no title, {is_are} not listed, and \
             `temper memory migrate` skips {} — `temper memory status` names them.\n",
            local.untitled,
            if local.untitled == 1 { "it" } else { "them" },
        ));
    }
    out
}

/// Split a section's entries into the ones that render individually and the ones the tail
/// collapses. **Order within each half is preserved** — this filters, it never re-sorts, so an
/// unconfigured threshold cannot reorder anything.
///
/// `None` puts every entry in the first half, which is what makes the absent-threshold render
/// byte-identical to the render that existed before this function did.
fn split_by_reinforcement(
    entries: Vec<&MemoryEntry>,
    reinforced_min: Option<u32>,
) -> (Vec<&MemoryEntry>, Vec<&MemoryEntry>) {
    let Some(min) = reinforced_min else {
        return (entries, Vec::new());
    };
    entries
        .into_iter()
        .partition(|e| e.reinforced.len() as u64 >= u64::from(min))
}

/// The tail line: **demotion, never deletion.**
///
/// It states the count, the section they are still in, why they were collapsed, and the command
/// that lands on the section they are still in — because an entry that stops rendering must not
/// thereby become something
/// a reader has no route back to. `--all` is part of that: a bare `resource list` returns a capped
/// page, so sending a reader to one would be sending them to a second truncation.
///
/// Returns `None` for an empty tail rather than rendering "0 more", so a section that collapsed
/// nothing looks exactly like a section from before the tail existed.
///
/// **`route` is a parameter because the section is no longer always a context.** It used to be
/// composed here as `resource list --context {section}`, which was true while every heading was a
/// context ref and became false the moment a heading could be a principle — and a route back that
/// does not resolve is worse than none, since `decay-must-never-make-a-memory-unfindable` is
/// satisfied by the route *working*, not by a command being printed.
fn render_tail(
    collapsed: &[&MemoryEntry],
    section: &str,
    route: &str,
    reinforced_min: u32,
) -> Option<String> {
    if collapsed.is_empty() {
        return None;
    }
    // At a threshold of 1 the collapsed set really is the unreinforced ones, which is the plain
    // word for it. Above 1 that word would be false — an entry with one date is reinforced and
    // still demoted — so the line states the threshold instead of reaching for the shorter phrase.
    let why = if reinforced_min <= 1 {
        "unreinforced".to_string()
    } else {
        format!("reinforced fewer than {reinforced_min} times")
    };
    Some(format!(
        "- … {} more in {section}, {why} — demoted, not dropped: `{route}`\n",
        collapsed.len(),
    ))
}

/// Everything above the first section heading. One definition, so the grouped and flat renders
/// cannot drift on the preamble a cold session reads first.
fn index_header() -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("\n\n# Memory index\n\n");
    out.push_str(READING_GUIDANCE);
    out
}

/// One section's entry lines plus its tail, appended to `out`.
///
/// Extracted so the two renders emit *the same line*: the per-entry format is the byte budget the
/// whole index is built around, and two copies of it would drift the first time one was touched.
fn push_section(
    out: &mut String,
    in_section: Vec<&MemoryEntry>,
    section: &str,
    route: &str,
    policy: RenderPolicy,
) {
    let RenderPolicy {
        today,
        stale_after_days,
        reinforced_min,
    } = policy;
    let (kept, collapsed) = split_by_reinforcement(in_section, reinforced_min);
    for e in kept {
        let age = (today - e.verified).num_days();
        // UNEXAMINED, never STALE/WRONG: an old date means nobody has checked,
        // which is not evidence the claim is false.
        let mark = if age > i64::from(stale_after_days) {
            format!("[verified {} — UNEXAMINED {}d]", e.verified, age)
        } else {
            format!("[verified {}]", e.verified)
        };
        // The TITLE is the hook this index carries, and nothing else is. `descriptor` is
        // deliberately absent: its job is FTS weight-D searchability on the resource, and
        // printing it here paid for that job twice — measured on the real corpus, ~279 bytes
        // per line against ~120, i.e. ~49 KB for the full set where the hand-written file it
        // replaces was 19.3 KB. This file is loaded every session; every byte is paid 178
        // times. (`[decided — 2026-08-01, Pete]`)
        //
        // The link target is the **bare id**, which is what `parse_ref` accepts — so a target
        // copied out of this file resolves as-is. It previously carried a `temper://` scheme,
        // which resolved in neither surface a reader has: `parse_ref` rejects it outright, and
        // MCP's resource URI is `temper://resources/{id}`, not `temper://{id}`. A link that
        // works nowhere is worse than no link, because it reads as one.
        out.push_str(&format!("- [{}]({})  {}\n", e.title, e.id, mark));
    }
    // `split_by_reinforcement` returns an empty tail for `None`, so this nesting never has to
    // invent a threshold to describe a collapse that cannot have happened.
    if let Some(min) = reinforced_min {
        if let Some(tail) = render_tail(&collapsed, section, route, min) {
            out.push_str(&tail);
        }
    }
}

/// What the ungrouped section says about itself.
///
/// **It is an error surface for the assignment pass, and it says so — it is NOT a cull list.**
/// That reading was tried and falsified on 2026-08-02: of 46 ungrouped memories, 23 were
/// assignment errors and 9 had their descriptor destroyed by an unrelated YAML bug, so roughly two
/// thirds of what lands here is a defect in the *filing*, not a memory that stopped earning its
/// place. One of the misses stated a claim that is literally one of its principle's named edges.
/// So this heading measures **attention, never value**, and anything built on top of it that
/// culled or decayed what is unassigned would delete an author's mistakes rather than the corpus's
/// dead weight, silently.
const UNGROUPED_PREAMBLE: &str = "\
No principle edge yet. This measures what nobody has judged — never what is surplus, and never a \
list to cull from.\n\
Assign one with `temper edge assert <memory> <principle> --kind express --label evidences`.\n";

/// Section by principle: preamble from the principle's own body, members from its edges.
///
/// **Principles are ordered by title, deliberately not by member count.** Size ordering would
/// reshuffle the whole file every time an edge landed, turning an ordinary assignment into a
/// large, meaningless diff in a file whose drift gate is a hand-edit detector.
///
/// The context axis is dropped here `[decided — 2026-08-02, Pete]`. Every principle spans both
/// configured contexts (measured: 7 of 8), so keeping context as a heading would split eight
/// sections into sixteen; and for a reader of *this* index the axis carries little, because every
/// configured context reaches this project by construction. The named loss is that the index no
/// longer says whether a memory is shared across projects or specific to this one.
fn render_by_principle(
    entries: &[MemoryEntry],
    principles: &[&PrincipleSection],
    policy: RenderPolicy,
) -> String {
    let mut out = index_header();

    let mut ordered: Vec<&&PrincipleSection> = principles.iter().collect();
    ordered.sort_by(|a, b| a.title.cmp(&b.title));

    let mut grouped_ids: HashSet<Uuid> = HashSet::new();
    for p in ordered {
        out.push_str(&format!("\n## {}\n\n", p.title));
        if let Some(statement) = &p.statement {
            out.push_str(statement);
            out.push_str("\n\n");
        }
        let members: HashSet<Uuid> = p.members.iter().copied().collect();
        // Entry order is `entries` order, never the edge order — the edges arrive sorted by when
        // somebody happened to assert them, which is not a property of the memories.
        let in_section: Vec<&MemoryEntry> = entries
            .iter()
            .filter(|e| e.status == "active" && members.contains(&e.id))
            .collect();
        for e in &in_section {
            grouped_ids.insert(e.id);
        }
        // The route back is the principle's own edge read: `--context` would name a context this
        // heading is not.
        let route = format!("temper resource show {} --edges", p.id);
        push_section(&mut out, in_section, &p.title, &route, policy);
    }

    let ungrouped: Vec<&MemoryEntry> = entries
        .iter()
        .filter(|e| e.status == "active" && !grouped_ids.contains(&e.id))
        .collect();
    if !ungrouped.is_empty() {
        out.push_str(&format!("\n## Not yet grouped ({})\n\n", ungrouped.len()));
        out.push_str(UNGROUPED_PREAMBLE);
        out.push('\n');
        // No tail here even under a threshold: collapsing the unjudged behind a count would hide
        // the assignment pass's own errors, which is the one thing this section exists to show.
        push_section(
            &mut out,
            ungrouped,
            "Not yet grouped",
            "temper memory status",
            RenderPolicy {
                reinforced_min: None,
                ..policy
            },
        );
    }
    out
}

fn render_migrated(entries: &[MemoryEntry], policy: RenderPolicy) -> String {
    let mut out = index_header();

    let mut contexts: Vec<&str> = entries
        .iter()
        .filter(|e| e.status == "active")
        .map(|e| e.context_ref.as_str())
        .collect();
    contexts.sort_unstable();
    contexts.dedup();

    for ctx in contexts {
        out.push_str(&format!("\n## {ctx}\n\n"));
        let in_section: Vec<&MemoryEntry> = entries
            .iter()
            .filter(|e| e.status == "active" && e.context_ref == ctx)
            .collect();
        let route = format!("temper resource list --type memory --context {ctx} --all");
        push_section(&mut out, in_section, ctx, &route, policy);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{DateTime, Utc};
    use serde_json::json;
    use temper_core::types::ids::{ProfileId, ResourceId};
    use temper_workflow::types::resource::{BodyStorage, IngestState, ResourceDetail, ResourceRow};

    fn d(s: &str) -> NaiveDate {
        NaiveDate::parse_from_str(s, "%Y-%m-%d").unwrap()
    }

    /// The render policy every pre-tail test was written against: no threshold configured, which
    /// is what every machine in existence has today.
    fn no_threshold(today: &str) -> RenderPolicy {
        RenderPolicy {
            today: d(today),
            stale_after_days: 90,
            reinforced_min: None,
        }
    }

    fn threshold(today: &str, min: u32) -> RenderPolicy {
        RenderPolicy {
            reinforced_min: Some(min),
            ..no_threshold(today)
        }
    }

    fn entry(title: &str, status: &str, verified: &str) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::nil(),
            title: title.to_string(),
            context_ref: "@me/temper".to_string(),
            status: status.to_string(),
            verified: d(verified),
            reinforced: Vec::new(),
        }
    }

    /// The same, with `n` distinct reinforcement dates — the only axis the tail reads.
    fn reinforced_entry(title: &str, n: usize) -> MemoryEntry {
        let mut e = entry(title, "active", "2026-07-20");
        e.reinforced = (0..n)
            .map(|i| d("2026-01-01") + chrono::Duration::days(i as i64))
            .collect();
        e
    }

    /// The flat, context-sectioned render — [`render_index`] with no principles.
    ///
    /// Every test that reaches for this predates principle grouping and is about the flat render,
    /// so naming that intent once beats twenty-five copies of `&[]` that say nothing. The grouped
    /// render's own tests call `render_index` directly with real sections, which is what keeps
    /// this helper from quietly becoming the only way the render is exercised.
    fn render_flat(entries: &[MemoryEntry], local: &LocalIndex, policy: RenderPolicy) -> String {
        render_index(entries, local, &[], policy)
    }

    /// Build a `ResourceDetail` wrapping a real `ResourceRow`, with `open_meta`
    /// carrying `status`/`verified` only when the corresponding argument is
    /// `Some` — omitting a key entirely (not setting it to null) is what a
    /// real un-migrated memory resource looks like.
    fn row_with(status: Option<&str>, verified: Option<&str>) -> ResourceDetail {
        row_with_reinforced(status, verified, None)
    }

    /// As [`row_with`], plus a raw `open_meta.reinforced` value — raw rather than typed because
    /// the cases that matter are the ones no type would let you construct.
    fn row_with_reinforced(
        status: Option<&str>,
        verified: Option<&str>,
        reinforced: Option<serde_json::Value>,
    ) -> ResourceDetail {
        let mut open = serde_json::Map::new();
        if let Some(s) = status {
            open.insert("status".to_string(), json!(s));
        }
        if let Some(v) = verified {
            open.insert("verified".to_string(), json!(v));
        }
        if let Some(r) = reinforced {
            open.insert("reinforced".to_string(), r);
        }

        let row = ResourceRow {
            id: ResourceId::from(Uuid::nil()),
            kb_context_id: None,
            origin_uri: String::new(),
            title: "a memory".to_string(),
            originator_profile_id: ProfileId::from(Uuid::nil()),
            owner_profile_id: ProfileId::from(Uuid::nil()),
            is_active: true,
            created: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            updated: DateTime::<Utc>::from_timestamp(0, 0).expect("epoch"),
            context_name: None,
            doc_type_name: "memory".to_string(),
            owner_handle: "someone".to_string(),
            context_slug: Some("temper".to_string()),
            context_owner_ref: Some("@me".to_string()),
            cogmap_id: None,
            cogmap_name: None,
            stage: None,
            seq: None,
            mode: None,
            effort: None,
            body_hash: None,
            ingest_state: Some(IngestState::Complete),
            body_storage: Some(BodyStorage::Derived),
        };

        ResourceDetail {
            row,
            managed_meta: None,
            open_meta: Some(serde_json::Value::Object(open)),
        }
    }

    fn local(filename: &str, title: &str) -> LocalEntry {
        LocalEntry {
            filename: filename.to_string(),
            title: title.to_string(),
        }
    }

    /// The union is transitional machinery, and machinery that leaves a residue after the thing
    /// it was for is finished has become permanent. With nothing local left, the render must be
    /// what it was before the union existed — asserted against the whole string, since a stray
    /// blank line or trailing newline is exactly the kind of difference that would make every
    /// future `check` report drift on a machine that finished migrating.
    #[test]
    fn an_empty_local_set_renders_exactly_what_it_rendered_before_the_union() {
        let out = render_flat(
            &[entry("a memory", "active", "2026-07-20")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert_eq!(
            out,
            format!(
                "<!-- GENERATED by `temper memory emit` — do not edit -->\n\n\
                 # Memory index\n\n\
                 {READING_GUIDANCE}\n\
                 ## @me/temper\n\n\
                 - [a memory](00000000-0000-0000-0000-000000000000)  [verified 2026-07-20]\n"
            )
        );
    }

    /// **The link has to work in the tool the reader is holding.** This asserts the rendered
    /// target against the real resolver rather than against a shape, which is the whole point: the
    /// previous form (`temper://{id}`) was a perfectly plausible-looking link that `parse_ref`
    /// rejects outright, and MCP does not accept either — its resource URI is
    /// `temper://resources/{id}`. A test that matched a regex for "looks like a link" would have
    /// passed on it. Only running the parser the CLI actually uses can catch that class.
    #[test]
    fn every_rendered_link_target_resolves_as_a_resource_ref() {
        let out = render_flat(
            &[entry("a memory", "active", "2026-07-20")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        let targets: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("- ["))
            .filter_map(|l| {
                let open = l.rfind('(')?;
                let close = l[open..].find(')')? + open;
                Some(&l[open + 1..close])
            })
            .collect();
        assert!(!targets.is_empty(), "the render must produce link targets");
        for t in targets {
            assert!(
                temper_workflow::operations::parse_ref(t).is_ok(),
                "a target a reader copies must resolve with the CLI's own parser: {t:?}"
            );
        }
    }

    /// A session loads this file cold. Without the preamble it gets titles and has to *infer* that
    /// a line is a hook, that the target resolves, and what an old date means — the three things
    /// the hand-written index said outright and the render used not to.
    #[test]
    fn the_index_states_how_to_read_itself() {
        let out = render_flat(
            &[entry("a memory", "active", "2026-07-20")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(
            out.contains("a line is a title, not the memory"),
            "the index must say what a line is: {out}"
        );
        assert!(
            out.contains("temper resource show <id>"),
            "the index must say how to resolve one: {out}"
        );
        assert!(
            out.contains("never that it is wrong"),
            "the index must say what an old date does NOT mean: {out}"
        );
        let guidance_at = out.find("Hooks only").expect("guidance must render");
        let first_entry = out.find("- [").expect("an entry must render");
        assert!(
            guidance_at < first_entry,
            "guidance a reader meets after the list it explains is guidance they have already \
             not had"
        );
    }

    /// The task's hard constraint: an un-migrated entry must not look migrated. Three signals
    /// carry it, and the per-line ones matter most — a line quoted or grepped out of its section
    /// keeps the distinction that the heading alone would have lost.
    #[test]
    fn an_unmigrated_entry_never_looks_migrated() {
        let out = render_flat(
            &[entry("migrated one", "active", "2026-07-20")],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 0,
            },
            no_threshold("2026-08-01"),
        );
        let line = out
            .lines()
            .find(|l| l.contains("local one"))
            .expect("the local entry must render");
        assert!(
            line.contains("(./project_x.md)"),
            "the link must resolve to the file on disk: {line}"
        );
        // Asserted against the resolver, on the target this line actually carries. The migrated
        // form is now a bare id, so "does not contain `temper://`" would be vacuously true of
        // every line and would guard nothing — what must stay true is that a local entry's target
        // does not resolve to a resource, because it is not one.
        let open = line.rfind('(').expect("the local line must carry a target");
        let close = line[open..].find(')').expect("the target must close") + open;
        let target = &line[open + 1..close];
        assert!(
            temper_workflow::operations::parse_ref(target).is_err(),
            "an un-migrated entry has no resource id and its target must not resolve to one: \
             {target:?}"
        );
        assert!(
            line.contains("[local]"),
            "the per-line marker is what survives being quoted out of context: {line}"
        );
    }

    /// A local file's date would have to come from its mtime or its `modified` — neither of which
    /// is a record that anyone re-checked the claim. Printing either in the same column the
    /// migrated entries use for `verified` would manufacture exactly the false certification the
    /// goal's `a-claim-must-never-read-as-checked-when-nobody-checked-it` forbids.
    #[test]
    fn an_unmigrated_entry_is_given_no_verified_date_at_all() {
        let out = render_flat(
            &[],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 0,
            },
            no_threshold("2026-08-01"),
        );
        let line = out
            .lines()
            .find(|l| l.contains("local one"))
            .expect("the local entry must render");
        assert!(
            !line.contains("verified") && !line.contains("UNEXAMINED"),
            "no date may be fabricated for a memory nobody has checked: {line}"
        );
    }

    /// `the-index-stays-readable-as-the-corpus-grows` requires that what the index omits, it says
    /// it has omitted. The four files no index link names are not listed — they never were — but
    /// a reader must not conclude from their absence that this machine carries nothing else.
    #[test]
    fn files_omitted_for_want_of_a_title_are_counted_never_silently_dropped() {
        let out = render_flat(
            &[],
            &LocalIndex {
                entries: vec![local("project_x.md", "local one")],
                untitled: 4,
            },
            no_threshold("2026-08-01"),
        );
        assert!(
            out.contains("(5 files)"),
            "the heading counts what the machine carries, not what it could name: {out}"
        );
        assert!(
            out.contains("4 further"),
            "the omission must be stated, with its count: {out}"
        );
        assert!(
            out.contains("temper memory status"),
            "and must say where the omitted ones can be named: {out}"
        );
    }

    /// **The instruction has to be true of the files it is printed beside.** `migrate` can only
    /// move a file that carries a title, so where every remaining local file is untitled — which
    /// is the terminal state of a transition, once harvest and migrate have taken everything they
    /// can — telling the reader to run it sends them to a command that will skip all of them and
    /// say nothing about why. Observed live on 2026-08-01 with the four files no index link named.
    #[test]
    fn the_migrate_instruction_is_absent_when_nothing_listed_can_be_migrated() {
        let out = render_flat(
            &[],
            &LocalIndex {
                entries: vec![],
                untitled: 4,
            },
            no_threshold("2026-08-01"),
        );
        assert!(
            !out.contains("Run `temper memory migrate`"),
            "must not instruct a run that would skip every remaining file: {out}"
        );
        assert!(
            out.contains("skip"),
            "and must say that migrate skips them, so the absence is explained: {out}"
        );
    }

    /// The converse, so the fix cannot be "delete the instruction". Where a titled file is
    /// present, `migrate` genuinely moves it and the instruction must survive.
    #[test]
    fn the_migrate_instruction_is_present_when_a_listed_file_can_be_migrated() {
        let out = render_flat(
            &[],
            &LocalIndex {
                entries: vec![local("project_x.md", "a hook")],
                untitled: 4,
            },
            no_threshold("2026-08-01"),
        );
        assert!(out.contains("Run `temper memory migrate`"));
    }

    /// A section rendered with nothing to list used to emit the preamble's trailing blank, the
    /// empty entry loop, and the note's leading blank in a row.
    #[test]
    fn the_section_never_renders_a_run_of_blank_lines() {
        for local_index in [
            LocalIndex {
                entries: vec![],
                untitled: 4,
            },
            LocalIndex {
                entries: vec![local("project_x.md", "a hook")],
                untitled: 2,
            },
            LocalIndex {
                entries: vec![local("project_x.md", "a hook")],
                untitled: 0,
            },
        ] {
            let out = render_flat(&[], &local_index, no_threshold("2026-08-01"));
            assert!(
                !out.contains("\n\n\n"),
                "no run of blank lines, got:\n{out}"
            );
        }
    }

    /// The acceptance criterion, at the real ratio rather than a two-element fixture: taking the
    /// index over after a partial migration must lose no entry a reader had before. 69 migrated
    /// and 114 local is this machine's actual state on 2026-08-01.
    #[test]
    fn no_entry_is_lost_at_the_real_migrated_to_local_ratio() {
        let migrated: Vec<MemoryEntry> = (0..69)
            .map(|i| entry(&format!("migrated {i}"), "active", "2026-07-20"))
            .collect();
        let locals: Vec<LocalEntry> = (0..114)
            .map(|i| local(&format!("project_{i}.md"), &format!("local {i}")))
            .collect();

        let out = render_flat(
            &migrated,
            &LocalIndex {
                entries: locals,
                untitled: 0,
            },
            no_threshold("2026-08-01"),
        );

        for i in 0..69 {
            assert!(out.contains(&format!("migrated {i}]")), "lost migrated {i}");
        }
        for i in 0..114 {
            assert!(out.contains(&format!("local {i}]")), "lost local {i}");
        }
        assert_eq!(
            out.lines().filter(|l| l.starts_with("- [")).count(),
            183,
            "every one of the 183 entries renders exactly once"
        );
    }

    #[test]
    fn superseded_memories_are_absent_from_the_index() {
        let out = render_flat(
            &[
                entry("live one", "active", "2026-08-01"),
                entry("dead one", "superseded", "2026-08-01"),
            ],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(out.contains("live one"));
        assert!(
            !out.contains("dead one"),
            "superseded memories must not render"
        );
    }

    #[test]
    fn a_stale_entry_is_marked_unexamined_never_false() {
        let out = render_flat(
            &[entry("old claim", "active", "2026-01-01")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(
            out.contains("UNEXAMINED"),
            "an over-threshold entry is marked"
        );
        for word in ["STALE", "WRONG", "FALSE", "OUTDATED"] {
            assert!(
                !out.contains(word),
                "must not imply the claim is false, found {word}"
            );
        }
    }

    /// The index is loaded into context every session, so every byte on a line is paid for 178
    /// times. `open_meta.descriptor`'s job is FTS weight-D searchability — printing it here pays
    /// for that job a second time and, measured against the real corpus on 2026-08-01, took the
    /// mean line from ~120 to 279 bytes: ~49 KB for the full set against a hand-written file of
    /// 19.3 KB. The descriptor stays on the resource and stays searchable; it just stops being
    /// rendered.
    #[test]
    fn the_index_does_not_print_the_descriptor() {
        let out = render_flat(
            &[entry("a title", "active", "2026-07-20")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(
            !out.contains("hook text"),
            "the descriptor is searchable on the resource; the index carries the title: {out}"
        );
        assert!(
            out.contains("a title"),
            "the title is the hook the index carries"
        );
    }

    #[test]
    fn a_fresh_entry_carries_its_verified_date_and_no_marker() {
        let out = render_flat(
            &[entry("fresh", "active", "2026-07-20")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(out.contains("[verified 2026-07-20]"));
        assert!(!out.contains("UNEXAMINED"));
    }

    #[test]
    fn the_index_declares_itself_generated() {
        let out = render_flat(
            &[entry("x", "active", "2026-08-01")],
            &LocalIndex::default(),
            no_threshold("2026-08-01"),
        );
        assert!(out.starts_with("<!-- GENERATED by `temper memory emit` — do not edit -->"));
    }

    #[test]
    fn entries_group_under_their_context() {
        let mut a = entry("from temper", "active", "2026-08-01");
        a.context_ref = "@me/temper".into();
        let mut b = entry("from agreements", "active", "2026-08-01");
        b.context_ref = "@me/working-agreements".into();
        let out = render_flat(&[a, b], &LocalIndex::default(), no_threshold("2026-08-01"));
        assert!(out.contains("## @me/temper"));
        assert!(out.contains("## @me/working-agreements"));
    }

    // ---- the collapsed tail ----------------------------------------------------------------

    /// **The acceptance criterion, asserted against the whole string.** Every machine in existence
    /// has no threshold configured, and every memory in existence is unreinforced — so the
    /// no-threshold render over unreinforced entries is not an edge case, it is the *only* case
    /// today. This must therefore be byte-identical to what shipped before the tail existed: no
    /// tail line, no trailing marker, no extra blank.
    ///
    /// The config half of this criterion is guarded separately, at the deserializer
    /// (`temper_core::types::config::tests::a_memory_section_omitting_the_threshold_leaves_it_absent_never_defaulted`)
    /// and end-to-end through a parsed config
    /// (`emit::tests::an_unconfigured_threshold_renders_every_unreinforced_memory_individually`).
    /// Neither can stand in for this one: they prove the value arrives as `None`, this proves what
    /// `None` renders.
    #[test]
    fn an_absent_threshold_renders_byte_for_byte_what_it_rendered_before() {
        // The entry CARRIES reinforcement dates. Asserting this over an unreinforced entry would
        // have been the natural fixture and would have guarded almost nothing: the criterion is
        // about what reinforcement does to the render, so the render has to be given some.
        let mut e = entry("a memory", "active", "2026-07-20");
        e.reinforced = vec![d("2026-05-14"), d("2026-06-02")];

        let out = render_flat(&[e], &LocalIndex::default(), no_threshold("2026-08-01"));
        assert_eq!(
            out,
            format!(
                "<!-- GENERATED by `temper memory emit` — do not edit -->\n\n\
                 # Memory index\n\n\
                 {READING_GUIDANCE}\n\
                 ## @me/temper\n\n\
                 - [a memory](00000000-0000-0000-0000-000000000000)  [verified 2026-07-20]\n"
            ),
            "reinforcement must leave no trace in the render until a threshold is set"
        );
    }

    /// **The half the byte-for-byte assertion above cannot reach: N > 1, and the two states side
    /// by side.** A per-line reinforcement marker — `[×3]`, a re-sort, anything keyed on the new
    /// field — is the obvious next thing someone adds, and it would break criterion 2 on the five
    /// memories that are reinforced on the live corpus today while every fixture built from
    /// unreinforced rows stayed green. Rendering the same corpus twice, differing only in
    /// reinforcement, is what makes that indistinguishable-by-construction.
    #[test]
    fn under_no_threshold_reinforcement_changes_nothing_about_the_render() {
        let policy = no_threshold("2026-08-01");
        let unreinforced: Vec<MemoryEntry> = (0..4)
            .map(|i| reinforced_entry(&format!("memory {i}"), 0))
            .collect();
        let reinforced: Vec<MemoryEntry> = (0..4)
            .map(|i| reinforced_entry(&format!("memory {i}"), i + 1))
            .collect();

        assert_eq!(
            render_flat(&reinforced, &LocalIndex::default(), policy),
            render_flat(&unreinforced, &LocalIndex::default(), policy),
            "with no threshold, a heavily-reinforced corpus and an untouched one must render the \
             same bytes — order included"
        );
    }

    /// **Demotion, never deletion** — the load-bearing rule of the whole feature. A collapsed
    /// memory stops having its own line and does not stop existing, so the render must say how
    /// many went, that they were demoted rather than dropped, and a route back to
    /// them. `--all` is asserted because a bare `resource list` returns a capped page: sending a
    /// reader there would replace one truncation with another.
    #[test]
    fn a_collapsed_memory_is_counted_and_routed_to_never_silently_dropped() {
        let out = render_flat(
            &[
                reinforced_entry("load-bearing", 2),
                reinforced_entry("quiet one", 0),
                reinforced_entry("also quiet", 0),
            ],
            &LocalIndex::default(),
            threshold("2026-08-01", 1),
        );
        assert!(
            out.contains("- [load-bearing]"),
            "an at-threshold memory keeps its own line: {out}"
        );
        assert!(
            !out.contains("quiet one") && !out.contains("also quiet"),
            "below-threshold memories stop rendering individually: {out}"
        );
        let tail = out
            .lines()
            .find(|l| l.contains("more in"))
            .expect("the tail must render");
        assert!(tail.contains("2 more"), "the count must be stated: {tail}");
        assert!(
            tail.contains("@me/temper"),
            "the tail must name the section they are still in: {tail}"
        );
        assert!(
            tail.contains("demoted, not dropped"),
            "the render must say they still exist: {tail}"
        );
        assert!(
            tail.contains("temper resource list --type memory --context @me/temper --all"),
            "and must give an uncapped route back to the section rather than a second capped \
             page: {tail}"
        );
    }

    /// The converse, so the tail cannot be satisfied by always printing one. A section where every
    /// memory clears the threshold must look exactly like a section from before the tail existed —
    /// no "0 more" line, which would be noise on the common case once a threshold is finally set.
    #[test]
    fn a_section_that_collapsed_nothing_renders_no_tail_line() {
        let out = render_flat(
            &[reinforced_entry("a", 3), reinforced_entry("b", 3)],
            &LocalIndex::default(),
            threshold("2026-08-01", 2),
        );
        assert!(
            !out.contains("more in"),
            "a section with an empty tail must not announce one: {out}"
        );
    }

    /// The tail is **per section**, not one global line — a reader scanning `@me/temper` must be
    /// told what `@me/temper` is hiding, and the route printed must be scoped to that section or
    /// it points at the wrong corpus.
    #[test]
    fn each_section_carries_its_own_tail_with_its_own_count() {
        let mut a = reinforced_entry("quiet in temper", 0);
        a.context_ref = "@me/temper".into();
        let mut b = reinforced_entry("quiet in agreements", 0);
        b.context_ref = "@me/working-agreements".into();
        let mut c = reinforced_entry("also quiet in agreements", 0);
        c.context_ref = "@me/working-agreements".into();

        let out = render_flat(
            &[a, b, c],
            &LocalIndex::default(),
            threshold("2026-08-01", 1),
        );
        assert!(
            out.contains("- … 1 more in @me/temper,"),
            "each section counts only its own: {out}"
        );
        assert!(
            out.contains("- … 2 more in @me/working-agreements,"),
            "each section counts only its own: {out}"
        );
        assert!(
            out.contains("--context @me/working-agreements --all"),
            "the route must be scoped to the section it appears under: {out}"
        );
    }

    /// **The tail says why, and the reason has to be true.** At a threshold of 1 the collapsed set
    /// really is the unreinforced ones. At 2 it is not — a memory with one date *is* reinforced
    /// and still demoted — so the shorter word would be a false statement about the memories it
    /// describes, which is the same class of error as a `verified` date that reads as checked.
    #[test]
    fn the_tail_states_a_reason_that_is_true_at_the_threshold_in_force() {
        let at_one = render_flat(
            &[reinforced_entry("quiet", 0)],
            &LocalIndex::default(),
            threshold("2026-08-01", 1),
        );
        assert!(
            at_one.contains("unreinforced"),
            "at a threshold of 1 the plain word is accurate: {at_one}"
        );

        let at_two = render_flat(
            &[reinforced_entry("once", 1)],
            &LocalIndex::default(),
            threshold("2026-08-01", 2),
        );
        assert!(
            at_two.contains("reinforced fewer than 2 times"),
            "above 1 the line must state the threshold: {at_two}"
        );
        assert!(
            !at_two.contains("unreinforced"),
            "a memory with one date is not unreinforced, and the tail must not say it is: {at_two}"
        );
    }

    /// The tail filters; it never re-sorts. A threshold that reordered the surviving entries would
    /// make the index churn for reasons unrelated to what changed, and would put `check` into
    /// permanent drift on any machine that set one.
    #[test]
    fn the_threshold_filters_without_reordering_what_survives() {
        let out = render_flat(
            &[
                reinforced_entry("first", 5),
                reinforced_entry("collapsed", 0),
                reinforced_entry("second", 1),
            ],
            &LocalIndex::default(),
            threshold("2026-08-01", 1),
        );
        let first = out.find("first").expect("renders");
        let second = out.find("second").expect("renders");
        assert!(
            first < second,
            "surviving entries keep their incoming order, weakest-first or not: {out}"
        );
    }

    // ---- reading `open_meta.reinforced` --------------------------------------------------------

    /// The state of every memory in existence today. Absent is **not** malformed — reporting it as
    /// one would make `status` print 388 lines of noise on a corpus that is behaving correctly.
    #[test]
    fn an_absent_reinforced_key_is_unreinforced_not_malformed() {
        let r = reinforcement_of(&row_with(Some("active"), Some("2026-08-01")));
        assert_eq!(r.dates.len(), 0);
        assert_eq!(r.last(), None);
        assert_eq!(
            r.malformed, None,
            "absent is the ordinary state, not a report"
        );
    }

    #[test]
    fn well_formed_dates_are_read_distinct_and_ascending() {
        let r = reinforcement_of(&row_with_reinforced(
            Some("active"),
            Some("2026-08-01"),
            Some(json!(["2026-06-02", "2026-05-14", "2026-06-02"])),
        ));
        assert_eq!(r.dates, vec![d("2026-05-14"), d("2026-06-02")]);
        assert_eq!(r.dates.len(), 2, "strength is the count of DISTINCT dates");
        assert_eq!(r.last(), Some(d("2026-06-02")), "recency is their max");
        assert_eq!(r.malformed, None);
    }

    /// A value that is not a list at all — what `--open-meta-add` refuses with a 400, and what a
    /// hand-written `--open-meta` will happily store.
    #[test]
    fn a_non_list_reinforced_is_reported_and_yields_no_dates() {
        let r = reinforcement_of(&row_with_reinforced(
            Some("active"),
            Some("2026-08-01"),
            Some(json!("2026-05-14")),
        ));
        assert_eq!(r.dates.len(), 0);
        assert!(
            r.malformed
                .as_deref()
                .is_some_and(|m| m.contains("expected a list")),
            "the report must say what was expected: {:?}",
            r.malformed
        );
    }

    /// **The accepted consequence, asserted rather than described.** One mistyped date demotes the
    /// whole memory into the tail — the parseable siblings are deliberately NOT salvaged, because
    /// salvaging would leave the typo invisible on exactly the memory that has one. Recoverable,
    /// because demotion is never deletion, and `status` names it.
    #[test]
    fn one_unparseable_date_makes_the_whole_record_unreinforced() {
        let r = reinforcement_of(&row_with_reinforced(
            Some("active"),
            Some("2026-08-01"),
            Some(json!(["2026-05-14", "last tuesday"])),
        ));
        assert_eq!(
            r.dates.len(),
            0,
            "the parseable sibling must not be salvaged — the demotion is the signal"
        );
        assert!(
            r.malformed
                .as_deref()
                .is_some_and(|m| m.contains("last tuesday")),
            "the report must name what it could not read: {:?}",
            r.malformed
        );
    }

    /// **The soft/hard line, asserted at the boundary it governs.** `status` and `verified` fail
    /// the whole index; `reinforced` must not. This is the test that fails the moment someone
    /// gives the reinforcement parse a `MemoryDefect` variant.
    #[test]
    fn a_malformed_reinforced_is_never_a_defect_and_the_entry_still_parses() {
        let row = row_with_reinforced(
            Some("active"),
            Some("2026-08-01"),
            Some(json!(["not a date"])),
        );
        let e = parse_entry(&row).expect("a malformed reinforced must not fail the parse");
        assert!(
            e.reinforced.is_empty(),
            "and the entry is treated as unreinforced"
        );
    }

    #[test]
    fn a_parsed_entry_carries_its_reinforcement_dates() {
        let row = row_with_reinforced(
            Some("active"),
            Some("2026-08-01"),
            Some(json!(["2026-05-14", "2026-08-02"])),
        );
        let e = parse_entry(&row).expect("parses");
        assert_eq!(e.reinforced, vec![d("2026-05-14"), d("2026-08-02")]);
    }

    #[test]
    fn a_memory_missing_status_is_a_defect_not_a_default() {
        let row = row_with(None, Some("2026-08-01"));
        assert!(
            matches!(parse_entry(&row), Err(MemoryDefect::MissingStatus { .. })),
            "emit is the enforcement point; a missing key must never silently default to active"
        );
    }

    #[test]
    fn a_memory_with_an_unknown_status_is_a_defect() {
        let row = row_with(Some("activ"), Some("2026-08-01"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadStatus { .. })
        ));
    }

    #[test]
    fn a_memory_with_an_unparseable_verified_date_is_a_defect() {
        let row = row_with(Some("active"), Some("last tuesday"));
        assert!(matches!(
            parse_entry(&row),
            Err(MemoryDefect::BadVerified { .. })
        ));
    }

    // ---- grouping by principle ------------------------------------------------------------

    /// An entry with a distinct id. The shared [`entry`] helper gives every memory `Uuid::nil()`,
    /// which was harmless while the render sectioned on `context_ref` and is fatal here: grouping
    /// is entirely id-joined, so nil ids would make every memory a member of everything.
    fn identified(title: &str, id: u128) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::from_u128(id),
            ..entry(title, "active", "2026-07-20")
        }
    }

    fn principle(
        id: u128,
        title: &str,
        statement: Option<&str>,
        members: &[u128],
    ) -> PrincipleSection {
        PrincipleSection {
            id: Uuid::from_u128(id),
            title: title.to_string(),
            statement: statement.map(str::to_string),
            members: members.iter().copied().map(Uuid::from_u128).collect(),
        }
    }

    #[test]
    fn the_index_sections_by_principle_and_renders_its_statement_as_the_preamble() {
        let entries = [identified("a memory", 1), identified("another", 2)];
        let p = principle(
            0xF1,
            "The system is the authority",
            Some("Your model of the system is a hypothesis."),
            &[1, 2],
        );

        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[p],
            no_threshold("2026-08-01"),
        );

        assert!(
            out.contains(
                "## The system is the authority\n\nYour model of the system is a hypothesis.\n\n"
            ),
            "the principle's own statement must be the section preamble, directly under its \
             heading: {out}"
        );
        assert!(
            !out.contains("## @me/temper"),
            "grouping replaces the context heading, it does not render alongside it: {out}"
        );
        for title in ["a memory", "another"] {
            assert!(
                out.contains(title),
                "{title} must render in the section: {out}"
            );
        }
    }

    /// **The fallback criterion, mutated at the feature rather than at a detail.** Emptying every
    /// membership set is what "the grouping went away" means to this render — the principles are
    /// still fetched, still titled, still carry statements, and none of them groups anything. The
    /// index must then be *exactly* the flat render: not similar, not "still fine", byte-identical,
    /// because the whole point is that a session loading this file cold notices nothing.
    #[test]
    fn dropping_every_edge_falls_back_to_the_flat_render_byte_for_byte() {
        let entries = [identified("a memory", 1), identified("another", 2)];
        let policy = no_threshold("2026-08-01");
        let flat = render_flat(&entries, &LocalIndex::default(), policy);

        let grouped_away = [
            principle(
                0xF1,
                "The system is the authority",
                Some("A statement."),
                &[],
            ),
            principle(0xF2, "Write for a partner", Some("Another."), &[]),
        ];
        let out = render_index(&entries, &LocalIndex::default(), &grouped_away, policy);

        assert_eq!(
            out, flat,
            "with nothing grouped the index must be byte-identical to the render that existed \
             before principles did"
        );

        // The control: with the edges restored the two must DIFFER, or the assertion above would
        // pass for a render that never groups at all.
        let grouped = [principle(
            0xF1,
            "The system is the authority",
            Some("A statement."),
            &[1, 2],
        )];
        assert_ne!(
            render_index(&entries, &LocalIndex::default(), &grouped, policy),
            flat,
            "grouping must actually change the render, or the fallback test proves nothing"
        );
    }

    #[test]
    fn a_memory_with_no_principle_edge_is_in_the_index_under_a_heading_that_states_the_count() {
        let entries = [
            identified("grouped", 1),
            identified("unjudged", 2),
            identified("also unjudged", 3),
        ];
        let p = principle(0xF1, "A principle", Some("A statement."), &[1]);

        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[p],
            no_threshold("2026-08-01"),
        );

        assert!(
            out.contains("## Not yet grouped (2)\n"),
            "the heading must state the count rather than silently omitting them: {out}"
        );
        for title in ["unjudged", "also unjudged"] {
            assert!(
                out.contains(title),
                "{title} must still be IN the index — absence from a section is never absence \
                 from the record: {out}"
            );
        }
        assert!(
            out.contains("never what is surplus"),
            "the section must say it measures attention rather than value, because two thirds of \
             what lands here is an assignment error: {out}"
        );
    }

    /// The ungrouped section must not be collapsible by the reinforcement threshold. Its entries
    /// are the ones nobody has judged; hiding them behind a count would conceal the assignment
    /// pass's own errors, which is the one thing the section exists to show.
    #[test]
    fn a_threshold_never_collapses_the_ungrouped_section() {
        let entries = [
            reinforced_and_identified("grouped", 1, 3),
            identified("unjudged", 2),
        ];
        let p = principle(0xF1, "A principle", None, &[1]);

        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[p],
            threshold("2026-08-01", 2),
        );

        assert!(
            out.contains("- [unjudged]"),
            "an unreinforced, unjudged memory must render on its own line even under a \
             threshold: {out}"
        );
    }

    fn reinforced_and_identified(title: &str, id: u128, n: usize) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::from_u128(id),
            ..reinforced_entry(title, n)
        }
    }

    /// **The route back must resolve.** `render_tail` used to compose
    /// `resource list --context {section}` from the section name, which was true while every
    /// heading was a context ref. Under a principle heading that command names a context that does
    /// not exist, so `decay-must-never-make-a-memory-unfindable` would be satisfied by a printed
    /// command that goes nowhere — the exact failure the `temper://` link shipped with.
    #[test]
    fn a_principle_sections_tail_routes_through_the_principle_not_a_context() {
        let entries = [
            reinforced_and_identified("kept", 1, 3),
            identified("demoted", 2),
        ];
        let p = principle(0xF1, "A principle", None, &[1, 2]);

        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[p],
            threshold("2026-08-01", 2),
        );

        let tail = out
            .lines()
            .find(|l| l.contains("more in"))
            .unwrap_or_else(|| panic!("a tail line must render: {out}"));
        assert!(
            tail.contains(&format!(
                "temper resource show {} --edges",
                Uuid::from_u128(0xF1)
            )),
            "the route back must be the principle's own edge read: {tail}"
        );
        assert!(
            !tail.contains("--context A principle"),
            "the tail must not compose a --context from a heading that is not a context: {tail}"
        );
    }

    #[test]
    fn a_principle_with_no_live_member_contributes_no_section() {
        let entries = [MemoryEntry {
            status: "superseded".to_string(),
            ..identified("superseded one", 1)
        }];
        let p = principle(0xF1, "An unevidenced principle", Some("A statement."), &[1]);

        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[p],
            no_threshold("2026-08-01"),
        );

        assert!(
            !out.contains("## An unevidenced principle"),
            "a heading with a preamble and nothing under it costs bytes to say nothing: {out}"
        );
    }

    /// The byte-budget criterion: a preamble is paid once per SECTION, never once per entry.
    #[test]
    fn the_preamble_is_paid_once_per_section_however_many_entries_it_holds() {
        let statement = "A statement that would be expensive to repeat.";
        let one = render_index(
            &[identified("a", 1)],
            &LocalIndex::default(),
            &[principle(0xF1, "P", Some(statement), &[1])],
            no_threshold("2026-08-01"),
        );
        let three = render_index(
            &[identified("a", 1), identified("b", 2), identified("c", 3)],
            &LocalIndex::default(),
            &[principle(0xF1, "P", Some(statement), &[1, 2, 3])],
            no_threshold("2026-08-01"),
        );

        assert_eq!(one.matches(statement).count(), 1);
        assert_eq!(
            three.matches(statement).count(),
            1,
            "three entries must not pay for the statement three times"
        );
    }

    #[test]
    fn a_memory_renders_under_every_principle_it_evidences() {
        let entries = [identified("cited twice", 1)];
        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[
                principle(0xF1, "First", None, &[1]),
                principle(0xF2, "Second", None, &[1]),
            ],
            no_threshold("2026-08-01"),
        );

        assert_eq!(
            out.matches("- [cited twice]").count(),
            2,
            "rendering under only one would silently hide a real edge: {out}"
        );
        assert!(
            !out.contains("## Not yet grouped"),
            "a memory under two principles is grouped, not ungrouped: {out}"
        );
    }

    /// Principles are ordered by title, not by member count — so an ordinary edge assertion
    /// produces a small diff instead of reshuffling the whole file under a hand-edit gate.
    #[test]
    fn principle_sections_are_ordered_by_title_not_by_size() {
        let entries = [identified("a", 1), identified("b", 2), identified("c", 3)];
        let out = render_index(
            &entries,
            &LocalIndex::default(),
            &[
                principle(0xF1, "Zebra", None, &[1, 2, 3]),
                principle(0xF2, "Alpha", None, &[1]),
            ],
            no_threshold("2026-08-01"),
        );

        let alpha = out.find("## Alpha").expect("Alpha section");
        let zebra = out.find("## Zebra").expect("Zebra section");
        assert!(
            alpha < zebra,
            "title order, not the 3-member section first: {out}"
        );
    }

    // ---- statement_of ---------------------------------------------------------------------

    #[test]
    fn a_statement_is_the_first_paragraph_never_the_whole_body() {
        let body = "The opening claim, which is the statement.\n\n\
                    - a recurring shape\n- another\n\n\
                    **How to apply.** Elaboration.";
        assert_eq!(
            statement_of(body).as_deref(),
            Some("The opening claim, which is the statement."),
            "the elaboration and the shapes list stay one `resource show` away"
        );
    }

    #[test]
    fn a_body_that_does_not_open_with_prose_yields_no_preamble() {
        for body in [
            "# A heading\n\nprose after it",
            "- a list item\n\nprose after it",
            "> a quote\n\nprose",
            "| a | table |\n\nprose",
            "1. an ordered item\n\nprose",
        ] {
            assert_eq!(
                statement_of(body),
                None,
                "a fragment of structure presented as a claim is worse than no preamble: {body}"
            );
        }
    }

    #[test]
    fn an_empty_body_yields_no_preamble_rather_than_an_empty_one() {
        assert_eq!(statement_of(""), None);
        assert_eq!(statement_of("   \n\n  "), None);
    }

    /// A number that opens a sentence is prose, not an ordered list. `1706 bytes is what the eight
    /// statements cost.` must survive.
    #[test]
    fn a_leading_number_that_is_not_a_list_marker_is_still_prose() {
        let body = "1706 bytes is what the eight statements cost.\n\nmore";
        assert_eq!(
            statement_of(body).as_deref(),
            Some("1706 bytes is what the eight statements cost.")
        );
    }
}
