-- GENERATED by tools/gen-install-migration.sh — do not edit by hand.
-- Source of truth: schema-artifact/01_schema.sql + 02_functions.sql.
-- Additive, run-once: creates the temper_next namespace alongside public (WS6 chunk 2, §D).

CREATE SCHEMA temper_next;
SET search_path TO temper_next, public;

-- ============================================================================
-- Temper — Arc-1 destination schema (one-shot artifact, NOT a migration)
-- ----------------------------------------------------------------------------
-- This is the fresh, destination shape the five+one Arc-1 specs describe, written
-- as a *target* so it can be loaded into a separate Postgres namespace alongside
-- the live `public.*` schema and evaluated empirically (seed + scenario queries)
-- before any phased migration is written. Read the real delta vs. `public.*`,
-- then ground the migration work on what the model actually does.
--
-- Namespace: everything lands in `temper_next`. Extensions (`vector`, the
-- `uuid_generate_v7()` generator) live in `public` and are reached via search_path.
--
-- Source specs (docs/superpowers/specs/):
--   2026-06-01-data-model-reconciliation-design.md      (resources/homes/properties/edges)
--   2026-06-02-access-capability-model-design.md        (descriptor, edge-home, teams:RBAC)
--   2026-06-02-map-regions-self-materialized-shape-surface-design.md  (cogmaps, regions)
--   2026-06-02-map-to-map-delegation-dissolution-design.md            (cogmaps_share_a_team)
--   2026-06-03-content-block-primitive-design.md        (blocks/chunks/revisions/provenance)
--   2026-06-04-domain-b-charter-questions-regulation-edge-semantics-design.md  (Domain-B)
--
-- All 17 plan-level leans were promoted to decisions on 2026-06-04 (commit 9335afb);
-- the ones with DDL consequence are marked [LEAN→DECISION] inline below.
--
-- Out of scope for this artifact (operational/sync Domain-A tables not central to
-- evaluating the cognitive-map model): kb_blob_files, kb_ingestion_records,
-- kb_device_sync_state, kb_transfers, kb_team_invitations, kb_join_requests,
-- kb_profile_auth_links, kb_resource_search_index (FTS rebuilt by trigger in prod).
-- ============================================================================

-- Namespace-resident DDL body — NO `DROP SCHEMA`/`CREATE SCHEMA` here. The destructive test-reset
-- preamble lives in `00_namespace_reset.sql` (prepended by the test harness); the additive production
-- install migration prepends its own run-once `CREATE SCHEMA temper_next;` (tools/gen-install-migration.sh).
-- This bare search_path keeps the body resolving the namespace when loaded standalone after 00.

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Carried unchanged from the built schema -----------------------------------
CREATE TYPE team_role     AS ENUM ('owner', 'maintainer', 'member', 'watcher');
CREATE TYPE edge_polarity AS ENUM ('forward', 'inverse');

-- edge_kind: the four structural classes. edge_kind = structural class;
-- the row's `label` carries the domain relationship (Domain-B §4 carve).
--   express  — abstract prior → local operationalization (skill→cogmap, telos→regulation)
--   contains — hierarchical has-a
--   leads_to — causal
--   near     — non-hierarchical, override-by-construction
CREATE TYPE edge_kind AS ENUM ('express', 'contains', 'leads_to', 'near');

-- NEW: profile-level system-access status (access §6). Virtual root-team
-- membership is *derived* from this — no stored membership row.
--   none     — no system access
--   approved — read-only ceiling on root/system-public content
--   admin    — management tier (may author system-public content)
CREATE TYPE system_access AS ENUM ('none', 'approved', 'admin');

-- NEW: tags a block-provenance contribution's source (content-block §DDL).
CREATE TYPE provenance_source_kind AS ENUM ('event', 'resource');

-- RETIRED (intentionally absent): `access_level` (vault|mutable|immutable) →
-- replaced by four boolean columns on kb_resource_access; `porosity`
-- (access|attention) → dropped, visibility is teams:RBAC.

-- ============================================================================
-- IDENTITY & ACTORS
-- ============================================================================

-- People. system_access gates the virtual root-team membership (access §6).
CREATE TABLE kb_profiles (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    handle        TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    system_access system_access NOT NULL DEFAULT 'none',
    created       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- NEW: the actor of an event. "Personas are behavior; the actor is an entity"
-- (Domain-B §6). A launched agent-instance is a runtime entity carrying
-- launch-metadata; a GitHub/Linear integration is another. The event ledger
-- emits via emitter_entity_id, never a bare profile.
--
-- [LEAN→DECISION] launch-metadata home (domain-b PQ-7): an OPEN `metadata jsonb`,
-- NOT a frozen entity_kind enum. An agent-instance populates {model, platform,
-- bound_cogmap, persona, priming_telos}; an integration populates differently;
-- neither is forced into the other's shape. Keeps room for ephemeral-vs-long-lived
-- and future profile-property promotion. The typed-typology cut, if ever earned,
-- is deferred to the event-substrate spec on real evidence.
CREATE TABLE kb_entities (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    profile_id  UUID NOT NULL REFERENCES kb_profiles(id),   -- the human/principal behind the actor
    name        TEXT NOT NULL,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kb_entities_profile ON kb_entities(profile_id);

-- Navigation home anchor (Domain-A). A resource homes in a context. Owner-scoped, slugged
-- namespace (WS6 §2 amendment 2026-06-13): uuid stays the canonical reference everything else uses;
-- `owner_table`/`owner_id` scope the namespace (a global `name UNIQUE` was a latent multi-tenant
-- error); `slug` is the per-owner addressable handle (team-style: unique slug, free display name).
-- `contexts_visible_to` stays retired and `kb_team_contexts` is still the sharing mechanism,
-- orthogonal to owner.
CREATE TABLE kb_contexts (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v7(),  -- canonical reference + access mechanism
    owner_table  VARCHAR(64) NOT NULL CHECK (owner_table IN ('kb_profiles','kb_teams')),
    owner_id     UUID NOT NULL,
    slug         TEXT NOT NULL,        -- per-owner addressable handle (team-style: unique slug, free name)
    name         TEXT NOT NULL,        -- display label (may collide across owners)
    created      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_table, owner_id, slug)
);
CREATE INDEX idx_kb_contexts_owner ON kb_contexts(owner_table, owner_id);

-- Topic taxonomy (event ledger dimension; carried, minimal).
CREATE TABLE kb_topics (
    id         UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    fqdn       TEXT NOT NULL UNIQUE,
    parent_id  UUID REFERENCES kb_topics(id),
    created    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- TEAMS (RBAC) — access §4/§6
-- ============================================================================

CREATE TABLE kb_teams (
    id       UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    slug     TEXT NOT NULL UNIQUE,
    name     TEXT NOT NULL,
    created  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- team_role re-grounded as a (management_tier, member_ceiling) pair (access §6);
-- the enum is unchanged.
CREATE TABLE kb_team_members (
    team_id     UUID NOT NULL REFERENCES kb_teams(id) ON DELETE CASCADE,
    profile_id  UUID NOT NULL REFERENCES kb_profiles(id) ON DELETE CASCADE,
    role        team_role NOT NULL,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, profile_id)
);
CREATE INDEX idx_kb_team_members_profile ON kb_team_members(profile_id);

-- Teams DAG. vis(T) is DAG-expanded DOWN-only: a descendant inherits an
-- ancestor/umbrella's grants; an ancestor gains no visibility into a descendant's
-- privates (access §4 A2-3). Every team descends from the temper-system root.
CREATE TABLE kb_teams_parents (
    child_id   UUID NOT NULL REFERENCES kb_teams(id) ON DELETE CASCADE,
    parent_id  UUID NOT NULL REFERENCES kb_teams(id) ON DELETE CASCADE,
    PRIMARY KEY (child_id, parent_id),
    CHECK (child_id <> parent_id)
);

-- ============================================================================
-- RESOURCES, HOMES, COGMAPS
-- ============================================================================

-- Slimmed to identity (data-model §1). Anchor/ownership moved to homes; doctype
-- and slug left entirely (doctype → kb_properties key='doc_type'; slug retired).
CREATE TABLE kb_resources (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    title       TEXT NOT NULL,
    origin_uri  TEXT NOT NULL,                 -- canonical source uri; not unique
    -- [LEAN→DECISION] A1: denormalized sync fingerprint — a merkle over the
    -- resource's ordered non-folded (block_id, block_body_hash) tuples. NOT
    -- identity: a derived content cache, recomputed by the block-mutation write
    -- path. sync_diff_for_device reads this column (one-column source swap).
    body_hash   TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Write-envelope for block mutations (audit_id FK target on revisions).
CREATE TABLE kb_resource_audits (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    resource_id  UUID REFERENCES kb_resources(id) ON DELETE SET NULL,
    created      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Cognitive maps (map-regions §0). Was kb_scopes; renamed, porosity dropped,
-- gains the constitutive telos_resource_id FK.
--
-- [LEAN→DECISION] map↔telos creation ordering (map-regions OQ-4, SUPERSEDED by
-- spine #2): cogmap_genesis inserts the telos resource BEFORE this row, so the
-- NOT NULL FK holds at insert in one transaction — no deferred FK.
CREATE TABLE kb_cogmaps (
    id                          UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    name                        TEXT NOT NULL,
    telos_resource_id           UUID NOT NULL REFERENCES kb_resources(id),  -- the charter resource (Domain-B §1)
    -- §6 stored materialization watermark: the event the shape was last
    -- materialized under (distinct from the on-read staleness aggregate, A3-3).
    shape_materialized_event_id UUID,                                       -- FK added after kb_events
    created                     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Joins a cogmap to 0+ teams. Empty-join ⇒ default-CLOSED cogmap (access §4).
CREATE TABLE kb_team_cogmaps (
    cogmap_id  UUID NOT NULL REFERENCES kb_cogmaps(id) ON DELETE CASCADE,
    team_id    UUID NOT NULL REFERENCES kb_teams(id) ON DELETE CASCADE,
    PRIMARY KEY (cogmap_id, team_id)
);
CREATE INDEX idx_kb_team_cogmaps_team ON kb_team_cogmaps(team_id);

-- NEW (WS6 adjudication §2): context-shareability. Joins a context to 0+ teams —
-- "this team's vis-reach includes this context's resources (and context-homed
-- edges)." Sibling of kb_team_cogmaps in shape; GRANT-like in semantics (inherits
-- DOWN the teams DAG via team_ancestors, exactly as team grants do). Cognitive
-- maps reach workflow content ONLY through producer-intersection over their
-- joined teams — there is no direct map↔context coupling.
CREATE TABLE kb_team_contexts (
    context_id  UUID NOT NULL REFERENCES kb_contexts(id) ON DELETE CASCADE,
    team_id     UUID NOT NULL REFERENCES kb_teams(id) ON DELETE CASCADE,
    PRIMARY KEY (context_id, team_id)
);
CREATE INDEX idx_kb_team_contexts_team ON kb_team_contexts(team_id);

-- Navigation: where a resource lives. One per resource. Polymorphic anchor —
-- no real FK (can't FK two tables); integrity is the CHECK + the seeding path.
CREATE TABLE kb_resource_homes (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    resource_id           UUID NOT NULL UNIQUE REFERENCES kb_resources(id) ON DELETE CASCADE,
    anchor_table          VARCHAR(64) NOT NULL CHECK (anchor_table IN ('kb_contexts', 'kb_cogmaps')),
    anchor_id             UUID NOT NULL,
    originator_profile_id UUID NOT NULL REFERENCES kb_profiles(id),
    owner_profile_id      UUID NOT NULL REFERENCES kb_profiles(id),
    created               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kb_resource_homes_anchor ON kb_resource_homes(anchor_table, anchor_id);

-- Additive grants beyond the home anchor (access §2). Subsumes kb_team_resources.
-- [LEAN→DECISION] B3 descriptor: four boolean capability columns (NOT an
-- access_level enum, NOT a bitmask) — readable directly in SQL, keeping the §6
-- role-mask intersection a plain per-column AND. The verb set is exactly §2's;
-- `contribute` is a role-CEILING tier, not a descriptor column.
-- [LEAN→DECISION] A2 grant-anchor set: ('kb_teams','kb_profiles') only. Cogmaps
-- read via the resources_accessible_to_cogmap intersection (never per-resource
-- grants); a context is a navigation home, not a grantee. A profile-anchored grant
-- is consumer-axis ONLY (leak-safety — never enters a vis(T) or a producer intersection).
CREATE TABLE kb_resource_access (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    resource_id           UUID NOT NULL REFERENCES kb_resources(id) ON DELETE CASCADE,
    anchor_table          VARCHAR(64) NOT NULL CHECK (anchor_table IN ('kb_teams', 'kb_profiles')),
    anchor_id             UUID NOT NULL,
    can_read              BOOLEAN NOT NULL DEFAULT false,
    can_write             BOOLEAN NOT NULL DEFAULT false,
    can_delete            BOOLEAN NOT NULL DEFAULT false,
    can_grant             BOOLEAN NOT NULL DEFAULT false,
    granted_by_profile_id UUID NOT NULL REFERENCES kb_profiles(id),
    granted_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (resource_id, anchor_table, anchor_id),
    -- §2 coherence: you cannot mutate or re-share what you cannot read.
    CHECK ((can_write OR can_delete OR can_grant) <= can_read)
);
CREATE INDEX idx_kb_resource_access_anchor   ON kb_resource_access(anchor_table, anchor_id);
CREATE INDEX idx_kb_resource_access_resource ON kb_resource_access(resource_id);

-- ============================================================================
-- EVENT LEDGER — the append-only spine everything projects from
-- ============================================================================

CREATE TABLE kb_event_types (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    name            TEXT NOT NULL UNIQUE,
    -- The published contract: current JSON-Schema for this type's payload (NULL =
    -- unregistered/permissive — foreign/webhook types may stay NULL). Stamped by the
    -- boot-seed from the committed schema-artifact/payloads/*.schema.json snapshots.
    payload_schema  JSONB,
    -- First-class version declaration. Evolution: additive-only within a version;
    -- a breaking change bumps this and registers the new schema.
    schema_version  INT NOT NULL DEFAULT 1,
    created         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The unified ledger. DELTA vs. public.kb_events: the built ledger emits via
-- (profile_id, device_id); the Arc-1 target emits via emitter_entity_id (spine
-- #2 "actor is an entity"). Legacy payload/references/resource_id/kb_context_id
-- columns collapse into metadata + the producing anchor.
--
-- [PHASE-2 DECISION] producing-anchor (formerly kb_events.scope_id): every homed
-- object (edges/properties/regions) carries its OWN gating (anchor_table,
-- anchor_id), so the event's producing anchor is PROVENANCE, not the gate. Modeled
-- polymorphic + nullable over ('kb_contexts','kb_cogmaps') — faithful to the
-- edge-home set, costs little.
CREATE TABLE kb_events (
    id                     UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    event_type_id          UUID NOT NULL REFERENCES kb_event_types(id),
    emitter_entity_id      UUID NOT NULL REFERENCES kb_entities(id),
    topic_id               UUID REFERENCES kb_topics(id),
    producing_anchor_table VARCHAR(64) CHECK (producing_anchor_table IN ('kb_contexts', 'kb_cogmaps')),
    producing_anchor_id    UUID,
    correlation_id         UUID,                              -- groups a multi-event act (e.g. a block's stream)
    -- Typed, per-event-type, replay-sufficient (payload-first design, 2026-06-09 spec §1/§3).
    -- The projection halves (_project_*) read ONLY this.
    payload                JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Typed provenance pointers: [{rel: supersedes|derived_from|touches, target:{kind,id}}]
    "references"           JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Which registered schema version this row's payload conforms to.
    payload_version        INT   NOT NULL DEFAULT 1,
    metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    created                TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- both-null-or-both-set for the polymorphic producing anchor
    CHECK ((producing_anchor_table IS NULL) = (producing_anchor_id IS NULL))
);
CREATE INDEX idx_kb_events_emitter     ON kb_events(emitter_entity_id, occurred_at DESC);
CREATE INDEX idx_kb_events_type        ON kb_events(event_type_id);
CREATE INDEX idx_kb_events_correlation ON kb_events(correlation_id);
CREATE INDEX idx_kb_events_references  ON kb_events USING GIN ("references" jsonb_path_ops);

-- Append-only enforcement (parity with production 20260522000001): supersession and correction are
-- themselves events; the ledger row is final. Safe to add now — no mutation function UPDATEs
-- kb_events anymore (identity-as-input made the genesis anchor known up front).
CREATE FUNCTION kb_events_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'event ledger is append-only';
END;
$$;
CREATE TRIGGER kb_events_append_only
    BEFORE UPDATE OR DELETE ON kb_events
    FOR EACH ROW EXECUTE FUNCTION kb_events_append_only();

-- Deferred FK from kb_cogmaps to the ledger (table created after kb_cogmaps).
ALTER TABLE kb_cogmaps
    ADD CONSTRAINT fk_kb_cogmaps_shape_event
    FOREIGN KEY (shape_materialized_event_id) REFERENCES kb_events(id);

-- ============================================================================
-- CONTENT BLOCKS — resource ⊃ blocks ⊃ chunks (content-block spec)
-- ============================================================================

-- The unit of content. A projection of the block's correlation-keyed event stream.
-- Blocks carry NO prose (text stays emergent from chunks, β overlay).
CREATE TABLE kb_content_blocks (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    resource_id       UUID NOT NULL REFERENCES kb_resources(id) ON DELETE CASCADE,
    seq               INT  NOT NULL,                  -- flat ordering within the resource
    -- [LEAN→DECISION] block-fold indexing: folding is an act on VISIBILITY (same
    -- category as edge-fold), orthogonal to chunk currency. NOT is_folded is the
    -- availability gate; is_current (on chunks) stays a true statement about the
    -- chunk. Reads filter on both; the vector index is partial on both.
    is_folded         BOOLEAN NOT NULL DEFAULT false,
    genesis_event_id  UUID NOT NULL REFERENCES kb_events(id),  -- correlation root of the block's stream
    last_event_id     UUID NOT NULL REFERENCES kb_events(id),  -- most recent event to change the block
    created           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (resource_id, seq)
);
CREATE INDEX idx_kb_content_blocks_resource ON kb_content_blocks(resource_id) WHERE NOT is_folded;

-- Chunks gain block_id (lifecycle anchor), keep resource_id (denormalized,
-- immutable = block's resource_id) so resource-scoped reads stay intact.
CREATE TABLE kb_chunks (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    block_id        UUID NOT NULL REFERENCES kb_content_blocks(id) ON DELETE CASCADE,
    resource_id     UUID NOT NULL REFERENCES kb_resources(id) ON DELETE CASCADE,  -- denormalized, immutable
    chunk_index     INT  NOT NULL,
    version         INT  NOT NULL DEFAULT 1,
    header_path     TEXT,
    heading_depth   SMALLINT,
    content_hash    TEXT NOT NULL,
    embedding       vector(768),
    is_current      BOOLEAN NOT NULL DEFAULT true,   -- latest revision of THIS chunk; orthogonal to block fold
    created         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (block_id, chunk_index, version)           -- dedup at block grain
);
CREATE INDEX idx_kb_chunks_block    ON kb_chunks(block_id);
CREATE INDEX idx_kb_chunks_resource ON kb_chunks(resource_id);
-- [LEAN→DECISION] partial HNSW: is_current AND NOT is_folded (join to the block).
-- A partial index can't reference another table, so the fold predicate rides the
-- query join; the index is partial on the chunk-local is_current. (Production may
-- denormalize is_folded onto the chunk if the join proves hot — measure first.)
CREATE INDEX idx_kb_chunks_embedding ON kb_chunks
    USING hnsw (embedding vector_cosine_ops) WHERE is_current;

-- Chunk prose (TOAST-stored), split so chunk metadata reads stay narrow.
CREATE TABLE kb_chunk_content (
    chunk_id  UUID PRIMARY KEY REFERENCES kb_chunks(id) ON DELETE CASCADE,
    content   TEXT NOT NULL
);

-- Content-version anchor at block grain (replaces resource-grain revisions).
CREATE TABLE kb_block_revisions (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    block_id        UUID NOT NULL REFERENCES kb_content_blocks(id) ON DELETE CASCADE,
    audit_id        UUID REFERENCES kb_resource_audits(id) ON DELETE SET NULL,  -- write envelope
    block_body_hash TEXT NOT NULL,
    chunk_count     INT  NOT NULL,
    created         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kb_block_revisions_block_created ON kb_block_revisions(block_id, created DESC);

-- Per-block provenance. ACCRETES — append-only-in-spirit, never superseded.
-- [LEAN→DECISION] scar linkage (domain-b PQ-2): a scar-lesson links back to the
-- folded question-block HERE via {kind:block} provenance (source_kind='resource',
-- the regulation resource), not via a graph edge — "the lesson came from scarring."
CREATE TABLE kb_block_provenance (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    block_id                UUID NOT NULL REFERENCES kb_content_blocks(id) ON DELETE CASCADE,
    source_kind             provenance_source_kind NOT NULL,
    source_id               UUID NOT NULL,                              -- the contributing event/resource
    contributed_by_event_id UUID NOT NULL REFERENCES kb_events(id),     -- the block_mutated event that added it
    accretion_seq           INT  NOT NULL,                              -- monotonic order this source shaped the block
    is_corrected            BOOLEAN NOT NULL DEFAULT false,             -- rare: "this source was wrong" (a scar)
    created                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (block_id, source_kind, source_id, contributed_by_event_id)
);
CREATE INDEX idx_kb_block_provenance_block  ON kb_block_provenance(block_id) WHERE NOT is_corrected;
CREATE INDEX idx_kb_block_provenance_source ON kb_block_provenance(source_kind, source_id);

-- ============================================================================
-- EDGES & PROPERTIES — polymorphic, event-sourced projections
-- ============================================================================

-- Was kb_resource_edges. Endpoints become polymorphic ('kb_resources','kb_cogmaps').
-- [LEAN→DECISION] edge-home (access OQ-2): the nullable scope_id is SUPERSEDED by a
-- denormalized home (home_anchor_table, home_anchor_id) over ('kb_contexts','kb_cogmaps'),
-- projected write-once from the asserting event. An edge is a first-class
-- access-gated object homed in the same resource-terms as everything else; the
-- home gates "seeing the assertion exists" (access §3). The event stays the
-- normalized source of truth; this column makes the graph read-gate a plain join.
CREATE TABLE kb_edges (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    source_table       VARCHAR(64) NOT NULL CHECK (source_table IN ('kb_resources', 'kb_cogmaps')),
    source_id          UUID NOT NULL,
    target_table       VARCHAR(64) NOT NULL CHECK (target_table IN ('kb_resources', 'kb_cogmaps')),
    target_id          UUID NOT NULL,
    edge_kind          edge_kind NOT NULL,
    polarity           edge_polarity NOT NULL DEFAULT 'forward',
    label              TEXT,                            -- the domain relationship (e.g. 'operationalized_by')
    weight             DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    home_anchor_table  VARCHAR(64) NOT NULL CHECK (home_anchor_table IN ('kb_contexts', 'kb_cogmaps')),
    home_anchor_id     UUID NOT NULL,
    asserted_by_event_id UUID NOT NULL REFERENCES kb_events(id),
    last_event_id        UUID NOT NULL REFERENCES kb_events(id),
    is_folded          BOOLEAN NOT NULL DEFAULT false,
    created            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_kb_edges_assertion ON kb_edges
    (source_table, source_id, target_table, target_id, edge_kind, COALESCE(label, ''),
     home_anchor_table, home_anchor_id) WHERE NOT is_folded;
CREATE INDEX idx_kb_edges_source ON kb_edges(source_table, source_id) WHERE NOT is_folded;
CREATE INDEX idx_kb_edges_target ON kb_edges(target_table, target_id) WHERE NOT is_folded;
CREATE INDEX idx_kb_edges_home   ON kb_edges(home_anchor_table, home_anchor_id) WHERE NOT is_folded;

-- The canonical structured-meta model (data-model §3). Single shape, non-null key.
-- doctype is a row here (key='doc_type'); relational frontmatter projects to edges.
CREATE TABLE kb_properties (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    owner_table           VARCHAR(64) NOT NULL CHECK (owner_table IN ('kb_resources', 'kb_cogmaps', 'kb_edges', 'kb_content_blocks')),  -- §4a edges carry facets; D3 blocks carry block_role
    owner_id              UUID NOT NULL,
    property_key          TEXT NOT NULL,
    property_value        JSONB NOT NULL,
    weight                DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    asserted_by_event_id  UUID NOT NULL REFERENCES kb_events(id),
    last_event_id         UUID NOT NULL REFERENCES kb_events(id),
    is_folded             BOOLEAN NOT NULL DEFAULT false,
    created               TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Uniqueness applies to ACTIVE rows only (partial): a folded property is history and may repeat a
-- value, so property_set's fold-then-reinsert (incl. revert-to-a-prior-value) never collides. Active
-- duplicates of (owner, key, value) stay forbidden — the multi-valued-facet guard.
CREATE UNIQUE INDEX uq_kb_properties_active ON kb_properties
    (owner_table, owner_id, property_key, property_value) WHERE NOT is_folded;
CREATE INDEX idx_kb_properties_owner     ON kb_properties(owner_table, owner_id) WHERE NOT is_folded;
CREATE INDEX idx_kb_properties_value_gin ON kb_properties USING gin (property_value jsonb_path_ops);
CREATE INDEX idx_kb_properties_key       ON kb_properties(property_key) WHERE NOT is_folded;

-- ============================================================================
-- COGNITIVE-MAP SHAPE — self-materialized regions (map-regions spec)
-- ============================================================================

-- The surface tier. Readable by anyone who can read the map (§4). Same
-- assert/fold pattern as edges/properties — no new freshness primitive.
-- Region lenses (spec §3B): a lens IS a declared, stored, IMMUTABLE projection-class
-- instance. Editing = assert a new row; a region's lens_id pins the exact weight-vector
-- it was computed under (the reproducibility anchor). Plurality = more rows; same function.
CREATE TABLE kb_cogmap_lenses (
    id                   UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    cogmap_id            UUID REFERENCES kb_cogmaps(id),  -- NULL = global default; non-null = map-specific
    name                 TEXT NOT NULL,
    selection_kind       TEXT NOT NULL DEFAULT 'homed',   -- 'homed' (this plan); 'team_visible' later
    w_express            DOUBLE PRECISION NOT NULL,
    w_contains           DOUBLE PRECISION NOT NULL,
    w_leads_to           DOUBLE PRECISION NOT NULL,
    w_near               DOUBLE PRECISION NOT NULL,
    w_prop               DOUBLE PRECISION NOT NULL,
    s_telos              DOUBLE PRECISION NOT NULL,
    s_ref                DOUBLE PRECISION NOT NULL,
    s_central            DOUBLE PRECISION NOT NULL,
    resolution           DOUBLE PRECISION NOT NULL,
    asserted_by_event_id UUID NOT NULL REFERENCES kb_events(id),
    created              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The INPUT-grain grouping a region is computed within (drift decision §3.2/§4). A component is a
-- connected set of the nonzero-affinity graph; regions never span components, so clustering decomposes
-- over them and a change re-clusters only its touched component(s). `fingerprint` is the SHA-256 of the
-- component's membership-determining inputs (members + intra-component edges + member facets + lens
-- affinity weights); `member_ids` is the component's node set (its identity across materializes).
-- Together they are the persisted artifact behind incremental materialization: a current component whose
-- (member_ids, fingerprint) matches a live row is provably unchanged ⇒ its regions are reused untouched.
CREATE TABLE kb_cogmap_components (
    id                   UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    cogmap_id            UUID NOT NULL REFERENCES kb_cogmaps(id) ON DELETE CASCADE,
    lens_id              UUID NOT NULL REFERENCES kb_cogmap_lenses(id),
    fingerprint          TEXT NOT NULL,               -- sha256 of membership-determining inputs
    member_ids           UUID[] NOT NULL,             -- the component's node set (sorted; its identity)
    asserted_by_event_id UUID NOT NULL REFERENCES kb_events(id),
    last_event_id        UUID NOT NULL REFERENCES kb_events(id),
    is_folded            BOOLEAN NOT NULL DEFAULT false,
    created              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kb_cogmap_components_live ON kb_cogmap_components(cogmap_id, lens_id) WHERE NOT is_folded;

-- [LEAN→DECISION] centroid pooling (OQ-1): pool-per-concept-then-mean (one vector
-- per member concept first), computed in MaterializeCogmapShape. No HNSW on
-- centroid yet (OQ-2: per-map scan; wanted, deferred "as we go").
CREATE TABLE kb_cogmap_regions (
    id                   UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    cogmap_id            UUID NOT NULL REFERENCES kb_cogmaps(id) ON DELETE CASCADE,
    lens_id              UUID NOT NULL REFERENCES kb_cogmap_lenses(id),  -- the perspective that produced this region (§3B)
    component_id         UUID REFERENCES kb_cogmap_components(id),       -- the input-grain group this region was clustered within (drift §4)
    centroid             vector(768) NOT NULL,
    salience             DOUBLE PRECISION NOT NULL,   -- computed blend, memoized (was agent-assigned; spec §3A)
    telos_alignment      DOUBLE PRECISION,            -- cosine(centroid, telos_resource.embedding)  [salience part]
    reference_standing   DOUBLE PRECISION,            -- aggregate reinforce_count over members        [salience part]
    centrality           DOUBLE PRECISION,            -- internal declared-affinity density × size      [salience part]
    content_cohesion     DOUBLE PRECISION,            -- mean member-to-centroid cosine (surface↔relational, §2c)
    internal_tension     DOUBLE PRECISION,            -- over oppositional-labeled declared edges among members
    label                TEXT,                        -- optional agent-authored region label
    member_count         INT NOT NULL,                -- aggregate; the blur exposed in the surface read
    asserted_by_event_id UUID NOT NULL REFERENCES kb_events(id),
    last_event_id        UUID NOT NULL REFERENCES kb_events(id),
    is_folded            BOOLEAN NOT NULL DEFAULT false,
    created              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kb_cogmap_regions_map ON kb_cogmap_regions(cogmap_id) WHERE NOT is_folded;

-- The interior tier. Member identities — NEVER returned wholesale by the surface
-- read; resolved per-member through resources_visible_to (and may be denied).
CREATE TABLE kb_cogmap_region_members (
    region_id     UUID NOT NULL REFERENCES kb_cogmap_regions(id) ON DELETE CASCADE,
    member_table  VARCHAR(64) NOT NULL CHECK (member_table IN ('kb_resources', 'kb_cogmaps')),
    member_id     UUID NOT NULL,
    affinity      DOUBLE PRECISION,            -- nearness to centroid (core vs peripheral)
    PRIMARY KEY (region_id, member_table, member_id)
);
CREATE INDEX idx_kb_cogmap_region_members_member ON kb_cogmap_region_members(member_table, member_id);

-- ============================================================================
-- End of 01_schema.sql. Functions → 02_functions.sql; seed → 03_seed.sql.
-- ============================================================================

-- ============================================================================
-- Temper — Arc-1 destination schema: FUNCTIONS
-- ----------------------------------------------------------------------------
-- The access-gating functions (the two-principal sum type), the delegation
-- predicate, the single-transaction cogmap seeding, and the Domain-B read
-- projections. Load after 01_schema.sql.
--
-- Principal sum type (access §4, CS-1): a substrate read carries ONE principal.
--   Profile(uuid) — a person reading        → resources_visible_to        (consumer axis)
--   Cogmap(uuid)  — an agent producing in M  → resources_accessible_to_cogmap (producer axis)
-- An agent cannot pass a profile: "never who is at the keyboard" is structural.
-- In SQL the sum is modeled as (p_principal_kind text IN ('profile','cogmap'),
-- p_principal_id uuid), dispatched by resources_readable_by below.
-- ============================================================================


-- ============================================================================
-- TEAMS DAG (kb_teams_parents inherits DOWN-only, access §4)
-- ============================================================================

-- A team plus all its ancestors (up the DAG). Grants on an ancestor are
-- inherited DOWN to this team, so the resources this team can reach via grants
-- are those granted on any team in {self} ∪ ancestors.
CREATE FUNCTION team_ancestors(p_team uuid)
RETURNS TABLE(team_id uuid) LANGUAGE sql STABLE AS $$
    WITH RECURSIVE up AS (
        SELECT p_team AS team_id
        UNION
        SELECT tp.parent_id
        FROM kb_teams_parents tp
        JOIN up ON tp.child_id = up.team_id
    )
    SELECT team_id FROM up;
$$;

-- A person's effective team set is just their memberships — uniform, no special
-- cases. The root-team membership is NOT derived at read time from a slug + a
-- system_access check; it is a REAL kb_team_members row that falls out of enabling
-- the profile (see sync_system_membership below). Approval auto-joins the
-- temper-system root, whose full overlap with the system-default cogmap is then
-- structural, not re-derived in every read function.
--   [REVISES access §6 OQ-3: "virtual root-membership, no stored row" → a real
--    membership maintained at approval time. The access mechanics read plainly.]
CREATE FUNCTION profile_effective_teams(p_profile uuid)
RETURNS TABLE(team_id uuid) LANGUAGE sql STABLE AS $$
    SELECT tm.team_id FROM kb_team_members tm WHERE tm.profile_id = p_profile;
$$;

-- Enabling a profile is what joins it to the teams DAG root. system_access is the
-- profile STATUS; its access consequence is a maintained membership, not a
-- read-time branch. Role encodes the §6 tier: approved → watcher (read-only
-- ceiling); admin → owner (management tier). Disabling ('none') removes the join.
CREATE FUNCTION sync_system_membership()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_root uuid;
BEGIN
    SELECT id INTO v_root FROM kb_teams WHERE slug = 'temper-system';
    IF v_root IS NULL THEN
        RETURN NEW;  -- root not yet seeded; nothing to maintain
    END IF;
    IF NEW.system_access = 'none' THEN
        DELETE FROM kb_team_members WHERE team_id = v_root AND profile_id = NEW.id;
    ELSE
        INSERT INTO kb_team_members (team_id, profile_id, role)
        VALUES (v_root, NEW.id,
                CASE NEW.system_access WHEN 'admin' THEN 'owner'::team_role
                                       ELSE 'watcher'::team_role END)
        ON CONFLICT (team_id, profile_id) DO UPDATE SET role = EXCLUDED.role;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_sync_system_membership
    AFTER INSERT OR UPDATE OF system_access ON kb_profiles
    FOR EACH ROW EXECUTE FUNCTION sync_system_membership();

-- NEW (WS6 adjudication §2): the default personal team — a loopback self-reference
-- so a solo profile's maps read their own contexts through the SAME intersection
-- mechanics (share context → personal team; join map → personal team). No
-- visibility-model special case. Idempotent by slug: replay restores kb_teams
-- BEFORE kb_profiles, so the trigger's insert no-ops against restored rows and
-- the original team ids survive (mirrors the kb_team_members tolerance).
CREATE FUNCTION sync_personal_team()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_team uuid;
    v_root uuid;
BEGIN
    INSERT INTO kb_teams (slug, name)
    VALUES ('personal-' || NEW.handle, NEW.display_name || ' (personal)')
    ON CONFLICT (slug) DO NOTHING;
    SELECT id INTO v_team FROM kb_teams WHERE slug = 'personal-' || NEW.handle;
    INSERT INTO kb_team_members (team_id, profile_id, role)
    VALUES (v_team, NEW.id, 'owner'::team_role)
    ON CONFLICT (team_id, profile_id) DO NOTHING;
    SELECT id INTO v_root FROM kb_teams WHERE slug = 'temper-system';
    IF v_root IS NOT NULL THEN
        INSERT INTO kb_teams_parents (child_id, parent_id)
        VALUES (v_team, v_root)
        ON CONFLICT DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_sync_personal_team
    AFTER INSERT ON kb_profiles
    FOR EACH ROW EXECUTE FUNCTION sync_personal_team();

-- ============================================================================
-- CONSUMER AXIS — resources_visible_to(profile)
-- ============================================================================

-- A person reads a resource if they own/originated it, hold a direct
-- profile-anchored grant, hold a team-anchored grant on any team they reach
-- (an effective team or one of its ancestors — grants inherit down), or the
-- resource homes in a context shared to a reachable team (WS6 §2). The
-- temper-system root floor falls out: every team descends from root, so a root
-- grant lands in every person's ancestor set.
CREATE FUNCTION resources_visible_to(p_profile uuid)
RETURNS TABLE(resource_id uuid) LANGUAGE sql STABLE AS $$
    WITH reachable_teams AS (
        SELECT DISTINCT a.team_id
        FROM profile_effective_teams(p_profile) e
        CROSS JOIN LATERAL team_ancestors(e.team_id) a
    )
    -- owned / originated (the home confers access to its principals)
    SELECT h.resource_id FROM kb_resource_homes h
     WHERE h.owner_profile_id = p_profile OR h.originator_profile_id = p_profile
    UNION
    -- direct profile-anchored grant (consumer-axis ONLY — never enters a vis(T))
    SELECT ra.resource_id FROM kb_resource_access ra
     WHERE ra.anchor_table = 'kb_profiles' AND ra.anchor_id = p_profile AND ra.can_read
    UNION
    -- team-anchored grant on a reachable (self-or-ancestor) team
    SELECT ra.resource_id FROM kb_resource_access ra
     JOIN reachable_teams rt ON ra.anchor_id = rt.team_id
     WHERE ra.anchor_table = 'kb_teams' AND ra.can_read
    UNION
    -- context-share: resources homed in a context shared to a reachable team (WS6 §2)
    SELECT h.resource_id
    FROM kb_team_contexts tc
    JOIN reachable_teams rt ON tc.team_id = rt.team_id
    JOIN kb_resource_homes h
      ON h.anchor_table = 'kb_contexts' AND h.anchor_id = tc.context_id;
$$;

-- ============================================================================
-- PRODUCER AXIS — resources_accessible_to_cogmap(M) = ⋂ vis(T) over teams(M)
-- ============================================================================

-- vis(T): team T's visibility. TEAM-anchored grants on T or its ancestors, plus
-- resources homed in contexts SHARED to T or its ancestors (WS6 adjudication §2 —
-- context-shares are grant-like and inherit DOWN identically). Profile-anchored
-- grants NEVER enter vis(T) — the A2 leak-safety invariant (access §4): a
-- person-grant cannot be referenced into a cogmap or leak cross-team, which is
-- what makes admitting kb_profiles as a grantee safe.
CREATE FUNCTION vis_team(p_team uuid)
RETURNS TABLE(resource_id uuid) LANGUAGE sql STABLE AS $$
    SELECT DISTINCT ra.resource_id
    FROM team_ancestors(p_team) a
    JOIN kb_resource_access ra
      ON ra.anchor_table = 'kb_teams' AND ra.anchor_id = a.team_id AND ra.can_read
    UNION
    SELECT h.resource_id
    FROM team_ancestors(p_team) a
    JOIN kb_team_contexts tc ON tc.team_id = a.team_id
    JOIN kb_resource_homes h
      ON h.anchor_table = 'kb_contexts' AND h.anchor_id = tc.context_id;
$$;

-- The least-privilege team-INTERSECTION (access §4). An agent producing in M may
-- read only the common ground of M's joined teams — the only bound that closes
-- the cross-team leak (every joined team can read M's shape). Plus M's own
-- interior (resources homed in M), conferred unconditionally by map-home.
--   • empty teams(M) ⇒ NO shared rows (⋂ over ∅ would be the universe — backwards;
--     default-closed by construction). Own-home still readable.
--   • more teams ⇒ NARROWER reach (the overlap). Deliberate.
--   • the launching person's memberships never enter.
CREATE FUNCTION resources_accessible_to_cogmap(p_cogmap uuid)
RETURNS TABLE(resource_id uuid) LANGUAGE sql STABLE AS $$
    -- own interior (map-home-confers, access §1) — always readable by the map's agent
    SELECT h.resource_id FROM kb_resource_homes h
     WHERE h.anchor_table = 'kb_cogmaps' AND h.anchor_id = p_cogmap
    UNION
    -- shared reach: a resource in EVERY joined team's vis(T); empty join ⇒ none
    SELECT v.resource_id
    FROM (
        SELECT tc.team_id, vt.resource_id
        FROM kb_team_cogmaps tc
        CROSS JOIN LATERAL vis_team(tc.team_id) vt
        WHERE tc.cogmap_id = p_cogmap
    ) v
    GROUP BY v.resource_id
    HAVING count(DISTINCT v.team_id) = (
        SELECT count(*) FROM kb_team_cogmaps tc WHERE tc.cogmap_id = p_cogmap
    )
    AND (SELECT count(*) FROM kb_team_cogmaps tc WHERE tc.cogmap_id = p_cogmap) > 0;
$$;

-- Dispatch the principal sum type to the correct axis.
CREATE FUNCTION resources_readable_by(p_principal_kind text, p_principal_id uuid)
RETURNS TABLE(resource_id uuid) LANGUAGE sql STABLE AS $$
    SELECT resource_id FROM resources_visible_to(p_principal_id)        WHERE p_principal_kind = 'profile'
    UNION
    SELECT resource_id FROM resources_accessible_to_cogmap(p_principal_id) WHERE p_principal_kind = 'cogmap';
$$;

-- ============================================================================
-- COGMAP READABILITY & EDGE-HOME (access §3)
-- ============================================================================

-- A person reads a cogmap's SHAPE iff they are a member of a team joined to it
-- (any joined-team member, access §3 / map-regions §4). The root-joined
-- system-default cogmap is readable by anyone with approved+ (effective teams
-- include root). Membership-based — distinct from the down-only GRANT inheritance.
CREATE FUNCTION cogmap_readable_by_profile(p_profile uuid, p_cogmap uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT EXISTS (
        SELECT 1
        FROM kb_team_cogmaps tc
        JOIN profile_effective_teams(p_profile) e ON e.team_id = tc.team_id
        WHERE tc.cogmap_id = p_cogmap
    );
$$;

-- Can a Profile read a polymorphic anchor (an edge/region home)?
--   cogmap  → cogmap_readable_by_profile
--   context → ∃ a context-share on a reachable (self-or-ancestor) team (WS6 §2 —
--             replaces the pre-amendment 'always true' simplification; a
--             context-homed edge is gated exactly like the context's resources).
CREATE FUNCTION anchor_readable_by_profile(p_profile uuid, p_anchor_table text, p_anchor_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT CASE p_anchor_table
        WHEN 'kb_cogmaps'  THEN cogmap_readable_by_profile(p_profile, p_anchor_id)
        WHEN 'kb_contexts' THEN EXISTS (
            SELECT 1
            FROM profile_effective_teams(p_profile) e
            CROSS JOIN LATERAL team_ancestors(e.team_id) a
            JOIN kb_team_contexts tc ON tc.team_id = a.team_id
            WHERE tc.context_id = p_anchor_id
        )
        ELSE false
    END;
$$;

-- Is a polymorphic endpoint readable by a Profile? (resource → visible-set;
-- cogmap → shape-readable). The "endpoint integrity" gate (access §3): you may
-- not traverse to a node you cannot see.
CREATE FUNCTION endpoint_readable_by_profile(p_profile uuid, p_endpoint_table text, p_endpoint_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT CASE p_endpoint_table
        WHEN 'kb_resources' THEN p_endpoint_id IN (SELECT resource_id FROM resources_visible_to(p_profile))
        WHEN 'kb_cogmaps'   THEN cogmap_readable_by_profile(p_profile, p_endpoint_id)
        ELSE false
    END;
$$;

-- Edges TRAVERSABLE by a Profile: edge-home visible AND both endpoints
-- independently readable (access §3, A2-4 — both gates AND for traversal). The
-- directors' private edge between two public concepts is invisible because its
-- HOME (the directors' cogmap) is unreadable, even though both endpoints are public.
CREATE FUNCTION edges_visible_to(p_profile uuid)
RETURNS TABLE(edge_id uuid) LANGUAGE sql STABLE AS $$
    SELECT e.id
    FROM kb_edges e
    WHERE NOT e.is_folded
      AND anchor_readable_by_profile(p_profile, e.home_anchor_table, e.home_anchor_id)
      AND endpoint_readable_by_profile(p_profile, e.source_table, e.source_id)
      AND endpoint_readable_by_profile(p_profile, e.target_table, e.target_id);
$$;

-- ============================================================================
-- DELEGATION — cogmaps_share_a_team (map-to-map spec)
-- ============================================================================

-- The priming authz-prior: true iff the two cogmaps share ≥1 joined team. A LIVE
-- predicate (never materialized). Gates frame-injection (borrowing a target's
-- telos + blurred shape on a single bridge), NOT material reads — those stay
-- bound to resources_accessible_to_cogmap(originating), strictly stronger.
CREATE FUNCTION cogmaps_share_a_team(p_cogmap_a uuid, p_cogmap_b uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT EXISTS (
        SELECT 1
        FROM kb_team_cogmaps a
        JOIN kb_team_cogmaps b ON a.team_id = b.team_id
        WHERE a.cogmap_id = p_cogmap_a AND b.cogmap_id = p_cogmap_b
    );
$$;

-- ============================================================================
-- BODY-TEXT PROJECTION (β: text is emergent from chunks, not stored on blocks)
-- ============================================================================

-- Assemble a resource's body from its current chunks of non-folded blocks
-- (is_current AND NOT is_folded — the orthogonal gates).
CREATE FUNCTION resource_body_text(p_resource uuid)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT string_agg(cc.content, E'\n\n' ORDER BY b.seq, ch.chunk_index)
    FROM kb_content_blocks b
    JOIN kb_chunks ch        ON ch.block_id = b.id AND ch.is_current
    JOIN kb_chunk_content cc ON cc.chunk_id = ch.id
    WHERE b.resource_id = p_resource AND NOT b.is_folded;
$$;

CREATE FUNCTION block_body_text(p_block uuid)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT string_agg(cc.content, E'\n\n' ORDER BY ch.chunk_index)
    FROM kb_chunks ch
    JOIN kb_chunk_content cc ON cc.chunk_id = ch.id
    WHERE ch.block_id = p_block AND ch.is_current;
$$;

-- ============================================================================
-- DOMAIN-B READ PROJECTIONS (conventions over kernel; access-gated reads)
-- ============================================================================

-- Generic per-resource block projection (D3): a resource's non-folded blocks with assembled body
-- text, their block_role, and the provenance-attribution signal. Access-gated via resources_readable_by.
-- p_role NULL ⇒ all blocks; otherwise only blocks whose block_role property equals p_role. The
-- questions / framing / statement reads are all THIS function with a role filter — "kind" is not a
-- per-resource-type concept, but a property-filtered block read is universal (design §2, §4).
-- reinforce_count is a provenance-ATTRIBUTION accretion count (a reinforcement proxy), not a modeled
-- block-level trajectory (design §5).
-- ASSUMES single-label roles (design §3.2): exactly one non-folded block_role row per block, so the
-- role LEFT JOIN is 1:1 and reinforce_count's provenance fan-out is accurate. The weighted-multi-role
-- seam (design §3.4) would emit a row per role AND multiply reinforce_count — when that opens, pre-
-- aggregate kb_block_provenance in a subquery before the role join.
CREATE FUNCTION resource_blocks(
    p_resource uuid, p_principal_kind text, p_principal_id uuid, p_role text DEFAULT NULL
) RETURNS TABLE(seq int, block_id uuid, body_text text, role text,
                reinforce_count bigint, last_reinforced_at timestamptz) LANGUAGE sql STABLE AS $$
    SELECT b.seq, b.id, block_body_text(b.id),
           rp.property_value #>> '{}',
           count(pr.id) FILTER (WHERE NOT pr.is_corrected),
           max(pr.created) FILTER (WHERE NOT pr.is_corrected)
    FROM kb_content_blocks b
    LEFT JOIN kb_properties rp
           ON rp.owner_table = 'kb_content_blocks' AND rp.owner_id = b.id
          AND rp.property_key = 'block_role' AND NOT rp.is_folded
    LEFT JOIN kb_block_provenance pr ON pr.block_id = b.id
    WHERE b.resource_id = p_resource AND NOT b.is_folded
      AND p_resource IN (SELECT resource_id FROM resources_readable_by(p_principal_kind, p_principal_id))
      AND (p_role IS NULL OR rp.property_value #>> '{}' = p_role)
    GROUP BY b.seq, b.id, rp.property_value
    ORDER BY b.seq;
$$;

-- The one genuinely cogmap-specific read (D3): resolve a cogmap to its telos-charter resource id (the
-- kb_cogmaps.telos_resource_id FK). Everything else is generic resource-level — resource_body_text for
-- the charter body, resource_blocks(telos, …, p_role) for questions/framing. Retires
-- cogmap_charter/cogmap_questions. (cogmap_regulation is a graph-edge read — left untouched; it may be
-- demoted when the regulation/edge-semantics deliverable lands.)
CREATE FUNCTION cogmap_telos(p_cogmap uuid)
RETURNS uuid LANGUAGE sql STABLE AS $$
    SELECT telos_resource_id FROM kb_cogmaps WHERE id = p_cogmap;
$$;

-- Regulation: the open set of concept-resources the charter `express`-edges to
-- (label 'operationalized_by'), filtered to those the principal can read.
CREATE FUNCTION cogmap_regulation(p_cogmap uuid, p_principal_kind text, p_principal_id uuid)
RETURNS TABLE(resource_id uuid, title text, body_text text, edge_label text) LANGUAGE sql STABLE AS $$
    SELECT r.id, r.title, resource_body_text(r.id), e.label
    FROM kb_cogmaps c
    JOIN kb_edges e ON e.source_table = 'kb_resources'
                   AND e.source_id = c.telos_resource_id
                   AND e.edge_kind = 'express'
                   AND NOT e.is_folded
    JOIN kb_resources r ON r.id = e.target_id AND e.target_table = 'kb_resources'
    WHERE c.id = p_cogmap
      AND r.id IN (SELECT resource_id FROM resources_readable_by(p_principal_kind, p_principal_id));
$$;

-- ============================================================================
-- COGMAP SHAPE SURFACE + STALENESS (map-regions §3/§6)
-- ============================================================================

-- The surface tier (centroid, salience, label, member_count) — readable by any
-- principal who can read the map. Member identities are NEVER returned here
-- (interior is dereferenced per-member through resources_visible_to).
CREATE OR REPLACE FUNCTION cogmap_shape(
    p_cogmap uuid, p_principal_kind text, p_principal_id uuid, p_lens uuid DEFAULT NULL)
RETURNS TABLE(region_id uuid, lens_id uuid, salience double precision,
              content_cohesion double precision, label text, member_count int)
LANGUAGE sql STABLE AS $$
    SELECT reg.id, reg.lens_id, reg.salience, reg.content_cohesion, reg.label, reg.member_count
    FROM kb_cogmap_regions reg
    WHERE reg.cogmap_id = p_cogmap
      AND NOT reg.is_folded
      AND (p_lens IS NULL OR reg.lens_id = p_lens)   -- default = all lenses; Plan 3 may default to telos-default
      AND (
        (p_principal_kind = 'profile' AND cogmap_readable_by_profile(p_principal_id, p_cogmap))
        OR (p_principal_kind = 'cogmap' AND p_principal_id = p_cogmap)
      );
$$;

-- Content cohesion (spec §2c): mean member-to-centroid cosine. A DOWNSTREAM readout over a
-- formed region (cosine never enters FORMATION — that is Plan 2's declared-only affinity).
-- Per-concept pooling: each member resource's current chunk embeddings are mean-pooled to one
-- vector first (pool-per-concept-then-mean, map-regions OQ-1); the region centroid is the mean
-- of those; cohesion is the mean cosine of each member-vector to the centroid.
CREATE FUNCTION cogmap_region_content_cohesion(p_region uuid)
RETURNS double precision LANGUAGE sql STABLE AS $$
    WITH member_vec AS (   -- one pooled vector per member resource
        SELECT m.member_id, avg(ch.embedding) AS v
        FROM kb_cogmap_region_members m
        JOIN kb_chunks ch        ON ch.resource_id = m.member_id AND ch.is_current
        JOIN kb_content_blocks b ON b.id = ch.block_id AND NOT b.is_folded  -- vector gate mirrors embed + body-text
        WHERE m.region_id = p_region AND m.member_table = 'kb_resources'
        GROUP BY m.member_id
    ),
    ctr AS (SELECT avg(v) AS c FROM member_vec)
    SELECT avg(1 - (mv.v <=> ctr.c)) FROM member_vec mv, ctr;
$$;

-- Telos alignment (spec §2c, salience part): cosine of the region centroid to the cogmap's
-- telos-resource embedding (kb_cogmaps.telos_resource_id). "Importance under the map's telos,"
-- literal because the telos IS a resource with chunks. NULL iff the telos has no current chunks.
CREATE FUNCTION cogmap_region_telos_alignment(p_region uuid, p_cogmap uuid)
RETURNS double precision LANGUAGE sql STABLE AS $$
    WITH telos AS (
        SELECT avg(ch.embedding) AS v
        FROM kb_cogmaps c
        JOIN kb_chunks ch        ON ch.resource_id = c.telos_resource_id AND ch.is_current
        JOIN kb_content_blocks b ON b.id = ch.block_id AND NOT b.is_folded  -- vector gate mirrors embed + body-text
        WHERE c.id = p_cogmap
    ),
    reg AS (SELECT centroid AS v FROM kb_cogmap_regions WHERE id = p_region)
    SELECT 1 - (reg.v <=> telos.v) FROM reg, telos WHERE telos.v IS NOT NULL;
$$;

-- Reference standing (spec §2c): summed reinforce_count over the member resources' blocks
-- (a count() over kb_block_provenance, page-04 — derived, never stored). is_corrected excluded.
CREATE FUNCTION cogmap_region_reference_standing(p_region uuid)
RETURNS double precision LANGUAGE sql STABLE AS $$
    SELECT coalesce(count(p.*), 0)::double precision
    FROM kb_cogmap_region_members m
    JOIN kb_content_blocks b ON b.resource_id = m.member_id AND NOT b.is_folded
    JOIN kb_block_provenance p ON p.block_id = b.id AND NOT p.is_corrected
    WHERE m.region_id = p_region AND m.member_table = 'kb_resources';
$$;

-- Centrality (spec §2c): internal declared-affinity mass × size. Sum of declared edge weights
-- BOTH of whose endpoints are members of the region, times member_count. Raw (un-lens-weighted);
-- Plan 2 scales by the lens at materialization. Cosine never enters.
CREATE FUNCTION cogmap_region_centrality(p_region uuid)
RETURNS double precision LANGUAGE sql STABLE AS $$
    WITH mem AS (
        SELECT member_id FROM kb_cogmap_region_members
        WHERE region_id = p_region AND member_table = 'kb_resources'
    ),
    internal AS (
        SELECT coalesce(sum(e.weight), 0) AS mass
        FROM kb_edges e
        WHERE e.source_table='kb_resources' AND e.target_table='kb_resources'
          AND e.source_id IN (SELECT member_id FROM mem)
          AND e.target_id IN (SELECT member_id FROM mem)
          AND NOT e.is_folded
    )
    SELECT internal.mass * (SELECT count(*) FROM mem) FROM internal;
$$;

-- Internal tension (spec §2a/§2c): declared opposition among members — a FEATURE of the region,
-- never a fracture. Matches a caller-supplied label set (default {'contradicts'}); semantics are
-- NOT reserved at the kernel — the caller (lens) decides what counts as opposed.
CREATE FUNCTION cogmap_region_internal_tension(p_region uuid, p_opposed_labels text[])
RETURNS double precision LANGUAGE sql STABLE AS $$
    WITH mem AS (
        SELECT member_id FROM kb_cogmap_region_members
        WHERE region_id = p_region AND member_table = 'kb_resources'
    )
    SELECT coalesce(sum(e.weight), 0)::double precision
    FROM kb_edges e
    WHERE e.source_table='kb_resources' AND e.target_table='kb_resources'
      AND e.source_id IN (SELECT member_id FROM mem)
      AND e.target_id IN (SELECT member_id FROM mem)
      AND NOT e.is_folded
      AND e.label = ANY(p_opposed_labels);
$$;

-- Staleness (A3-3): ON-READ aggregate, not a denormalized watermark. Compares the
-- stored materialization watermark (kb_cogmaps.shape_materialized_event_id) against
-- the latest event touching the map's homed regions/edges. Stale reads are allowed
-- and LEGIBLE — this reports staleness, never blocks on it.
CREATE FUNCTION cogmap_staleness(p_cogmap uuid)
RETURNS TABLE(materialized_at timestamptz, latest_touch timestamptz, is_stale boolean)
LANGUAGE sql STABLE AS $$
    WITH mat AS (
        SELECT ev.occurred_at AS materialized_at
        FROM kb_cogmaps c
        LEFT JOIN kb_events ev ON ev.id = c.shape_materialized_event_id
        WHERE c.id = p_cogmap
    ),
    touch AS (
        SELECT max(occurred_at) AS latest_touch FROM (
            SELECT ev.occurred_at FROM kb_cogmap_regions reg
              JOIN kb_events ev ON ev.id = reg.last_event_id
             WHERE reg.cogmap_id = p_cogmap
            UNION ALL
            SELECT ev.occurred_at FROM kb_edges e
              JOIN kb_events ev ON ev.id = e.last_event_id
             WHERE e.home_anchor_table = 'kb_cogmaps' AND e.home_anchor_id = p_cogmap
        ) t
    )
    SELECT mat.materialized_at, touch.latest_touch,
           COALESCE(touch.latest_touch > mat.materialized_at, mat.materialized_at IS NULL)
    FROM mat, touch;
$$;

-- ============================================================================
-- Shared chunk-row writer: one persisted chunk (kb_chunks row + its kb_chunk_content prose), used by
-- BOTH the create projector (_project_blocks) and the revise projector (_project_block_mutated) so the
-- fragile fire-vs-replay embedding CASE lives in exactly one place. p_emb is the sidecar's
-- `embedding` jsonb: SQL/JSON-null ⇒ NULL vector; a JSON string ⇒ pgvector text (replay path); a JSON
-- array ⇒ fire path. version / is_current are explicit so the create path (v1, current) and the revise
-- path (next version, current) share the writer without relying on column defaults.
CREATE FUNCTION _insert_chunk(p_chunk uuid, p_block uuid, p_resource uuid, p_chunk_index int,
                              p_version int, p_content_hash text, p_emb jsonb, p_is_current boolean,
                              p_content text, p_header_path text, p_heading_depth smallint,
                              p_occurred timestamptz)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    -- header_path/heading_depth are production render metadata (§8 carry-as-is): persisted verbatim so
    -- a downstream read reconstructs headed markdown identically to production. They are NOT inputs to
    -- content_hash or the body_hash merkle (those stay over the chunk content hashes only). NULL on the
    -- scenario-authoring path (no production headings), exactly as before this carry existed.
    INSERT INTO kb_chunks (id, block_id, resource_id, chunk_index, version, content_hash,
                           embedding, is_current, header_path, heading_depth, created)
        VALUES (p_chunk, p_block, p_resource, p_chunk_index, p_version, p_content_hash,
                CASE
                    WHEN p_emb IS NULL OR jsonb_typeof(p_emb) = 'null' THEN NULL
                    WHEN jsonb_typeof(p_emb) = 'string' THEN (p_emb #>> '{}')::vector  -- replay: pgvector text
                    ELSE (p_emb::text)::vector                                          -- fire: JSON array
                END,
                p_is_current, p_header_path, p_heading_depth, p_occurred);
    INSERT INTO kb_chunk_content (chunk_id, content) VALUES (p_chunk, p_content);
END;
$$;

-- Shared resource body_hash recompute: sha256 merkle over each non-folded block's (sha256 of its
-- is_current chunk hashes in chunk_index order), blocks in seq order — a pure function of the resource's
-- CURRENT visible state. Both projectors call this after writing their chunks: at create every block is
-- fresh + current (so it equals the array-order concatenation), at revise it reflects the superseded
-- chunks. Replay-stable: identical visible state ⇒ identical hash, with `updated` carried from the event.
CREATE FUNCTION _recompute_resource_body_hash(p_resource uuid, p_occurred timestamptz)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_resource_hashes text;
BEGIN
    SELECT string_agg(bh, '' ORDER BY seq) INTO v_resource_hashes FROM (
        SELECT b.seq,
               encode(sha256(convert_to(string_agg(ch.content_hash, '' ORDER BY ch.chunk_index), 'UTF8')),
                      'hex') AS bh
        FROM kb_content_blocks b
        JOIN kb_chunks ch ON ch.block_id = b.id AND ch.is_current
        WHERE b.resource_id = p_resource AND NOT b.is_folded
        GROUP BY b.seq
    ) per_block;
    UPDATE kb_resources
        SET body_hash = encode(sha256(convert_to(coalesce(v_resource_hashes, ''), 'UTF8')), 'hex'),
            updated = p_occurred
        WHERE id = p_resource;
END;
$$;

-- ============================================================================
-- Shared block→chunk PROJECTOR (the content-block write path, payload-first). p_manifests is the
-- payload's BlockManifest array — pre-generated ids + seqs + roles + sha256 content hashes, NO prose
-- (the CAS rule: prose lives once in kb_chunk_content). p_content is the sidecar
--   { "<chunk_id>": { "content": text, "embedding": [f32;768] | "[...]" | null } }
-- persisted to kb_chunk_content / kb_chunks.embedding, never written to the ledger. Structural truth
-- comes ONLY from the manifests: a manifest chunk missing from the sidecar is an exception; sidecar
-- extras are ignored. Projected timestamps come from the owning event's occurred_at (replay-stable).
-- block_body_hash / resource body_hash stay DERIVED (sha256 merkles over the carried chunk hashes).
-- Blocks carry NO prose (β); a block whose prose exceeded one 510-token window arrives as >1 chunk.
-- The block_role property pair (owner_table='kb_content_blocks', property_key='block_role')
-- double-segregates roles from the resource-facet lens math (D3 guard-rail).
CREATE FUNCTION _project_blocks(p_resource uuid, p_event uuid, p_manifests jsonb, p_content jsonb)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    v_block uuid; v_chunk uuid;
    v_block_json jsonb; v_chunk_json jsonb; v_side jsonb;
    v_block_hash text; v_chunk_hashes text; v_chunk_count int;
    v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
BEGIN
    -- blocks ⊃ chunks, in array order (already seq-ordered Rust-side; the block's own seq is authoritative).
    FOR v_block_json IN SELECT jsonb_array_elements(p_manifests) LOOP
        v_block := (v_block_json->>'block_id')::uuid;
        INSERT INTO kb_content_blocks (id, resource_id, seq, genesis_event_id, last_event_id, created)
            VALUES (v_block, p_resource, (v_block_json->>'seq')::int, p_event, p_event, v_occurred);
        IF v_block_json ? 'role' AND jsonb_typeof(v_block_json->'role') = 'string' THEN
            INSERT INTO kb_properties (owner_table, owner_id, property_key, property_value,
                                       asserted_by_event_id, last_event_id, created)
            VALUES ('kb_content_blocks', v_block, 'block_role', v_block_json->'role',
                    p_event, p_event, v_occurred);
        END IF;
        v_chunk_hashes := '';
        v_chunk_count := 0;
        FOR v_chunk_json IN SELECT jsonb_array_elements(v_block_json->'chunks') LOOP
            v_chunk := (v_chunk_json->>'chunk_id')::uuid;
            v_side := p_content->(v_chunk_json->>'chunk_id');
            IF v_side IS NULL THEN
                RAISE EXCEPTION '_project_blocks: content sidecar missing chunk %', v_chunk;
            END IF;
            -- create path: every chunk is version 1 + current (the column defaults, stated explicitly here).
            PERFORM _insert_chunk(v_chunk, v_block, p_resource, (v_chunk_json->>'chunk_index')::int,
                                  1, v_chunk_json->>'content_hash', v_side->'embedding', true,
                                  v_side->>'content', v_side->>'header_path',
                                  NULLIF(v_side->>'heading_depth','')::smallint, v_occurred);
            v_chunk_hashes := v_chunk_hashes || (v_chunk_json->>'content_hash');
            v_chunk_count := v_chunk_count + 1;
        END LOOP;
        -- block_body_hash = sha256 merkle over the ordered chunk hashes (derived, never payload).
        v_block_hash := encode(sha256(convert_to(v_chunk_hashes, 'UTF8')), 'hex');
        INSERT INTO kb_block_revisions (block_id, block_body_hash, chunk_count, created)
            VALUES (v_block, v_block_hash, v_chunk_count, v_occurred);
    END LOOP;
    -- resource body_hash = merkle over current visible state (= the array-order concatenation at create).
    PERFORM _recompute_resource_body_hash(p_resource, v_occurred);
END;
$$;

-- ============================================================================
-- COGMAP GENESIS — single-transaction, resource-first seeding (Domain-B §5)
-- ============================================================================

-- Seeds a new cogmap atomically, payload-first. Identity-as-input: cogmap/resource/block/chunk ids
-- all arrive in the payload (CogmapSeeded, payloads.rs), so the producing anchor is known UP FRONT —
-- the old post-hoc backfill UPDATE on kb_events is gone (the ledger is append-only). Resource-first
-- ordering preserved: the telos resource + its blocks are created BEFORE the kb_cogmaps row, so
-- telos_resource_id NOT NULL holds at insert with no deferred FK.
-- The telos charter is real content-blocks (block-0 statement, blocks 1..n questions-with-context,
-- then framing), projected via the shared _project_blocks path with the p_content sidecar.
-- Emits a single `cogmap_seeded` event (the genesis correlation root; correlation_id = its own id).
-- doc_type property 'cogmap_charter' is stamped on the telos resource.
CREATE FUNCTION _project_cogmap_seeded(p_event uuid, p_payload jsonb, p_content jsonb)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
        v_cogmap   uuid := (p_payload->>'cogmap_id')::uuid;
        v_resource uuid := (p_payload#>>'{telos,resource_id}')::uuid;
        v_owner    uuid := (p_payload->>'owner_profile_id')::uuid;
BEGIN
    -- telos resource FIRST (telos_resource_id NOT NULL holds at the cogmap insert)
    INSERT INTO kb_resources (id, title, origin_uri, created, updated)
        VALUES (v_resource, p_payload#>>'{telos,title}', p_payload#>>'{telos,origin_uri}',
                v_occurred, v_occurred);
    PERFORM _project_blocks(v_resource, p_event, p_payload#>'{telos,blocks}', p_content);
    INSERT INTO kb_cogmaps (id, name, telos_resource_id, created)
        VALUES (v_cogmap, p_payload->>'name', v_resource, v_occurred);
    INSERT INTO kb_resource_homes (resource_id, anchor_table, anchor_id,
                                   originator_profile_id, owner_profile_id, created)
        VALUES (v_resource, 'kb_cogmaps', v_cogmap, v_owner, v_owner, v_occurred);
    INSERT INTO kb_properties (owner_table, owner_id, property_key, property_value,
                               asserted_by_event_id, last_event_id, created)
        VALUES ('kb_resources', v_resource, 'doc_type', '"cogmap_charter"'::jsonb,
                p_event, p_event, v_occurred);
END;
$$;

CREATE FUNCTION cogmap_genesis(p_payload jsonb, p_content jsonb, p_emitter uuid)
RETURNS TABLE(cogmap_id uuid, telos_resource_id uuid) LANGUAGE plpgsql AS $$
DECLARE v_ev uuid;
BEGIN
    v_ev := _event_append('cogmap_seeded', p_emitter,
                          'kb_cogmaps', (p_payload->>'cogmap_id')::uuid, p_payload);
    PERFORM _project_cogmap_seeded(v_ev, p_payload, p_content);
    cogmap_id := (p_payload->>'cogmap_id')::uuid;
    telos_resource_id := (p_payload#>>'{telos,resource_id}')::uuid;
    RETURN NEXT;
END;
$$;

-- ============================================================================
-- Reusable mutation mechanics (the cogmap_genesis mold): each emits its event AND projects in one
-- txn. The scenario loader / temper-cogmap lift call these; YAML is the event input source.
-- ============================================================================

-- Create a resource (payload-first; ResourceCreated, payloads.rs): identity from the payload, home
-- per the payload's polymorphic anchor, content as the real nesting (blocks ⊃ chunks ⊃ chunk_content)
-- via the shared _project_blocks path with the p_content sidecar, optional doc_type property.
-- Emits one `resource_created` event (the projection root). Returns the resource id.
CREATE FUNCTION _project_resource_created(p_event uuid, p_payload jsonb, p_content jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
        v_resource uuid := (p_payload->>'resource_id')::uuid;
        v_owner    uuid := (p_payload->>'owner_profile_id')::uuid;
BEGIN
    INSERT INTO kb_resources (id, title, origin_uri, created, updated)
        VALUES (v_resource, p_payload->>'title', p_payload->>'origin_uri', v_occurred, v_occurred);
    INSERT INTO kb_resource_homes (resource_id, anchor_table, anchor_id,
                                   originator_profile_id, owner_profile_id, created)
        VALUES (v_resource, p_payload#>>'{home,table}', (p_payload#>>'{home,id}')::uuid,
                COALESCE((p_payload->>'originator_profile_id')::uuid, v_owner),
                v_owner, v_occurred);
    PERFORM _project_blocks(v_resource, p_event, p_payload->'blocks', p_content);
    IF p_payload->>'doc_type' IS NOT NULL THEN
        INSERT INTO kb_properties (owner_table, owner_id, property_key, property_value,
                                   asserted_by_event_id, last_event_id, created)
            VALUES ('kb_resources', v_resource, 'doc_type', p_payload->'doc_type',
                    p_event, p_event, v_occurred);
    END IF;
    RETURN v_resource;
END;
$$;

CREATE FUNCTION resource_create(p_payload jsonb, p_content jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid;
BEGIN
    v_ev := _event_append('resource_created', p_emitter,
                          p_payload#>>'{home,table}', (p_payload#>>'{home,id}')::uuid, p_payload);
    RETURN _project_resource_created(v_ev, p_payload, p_content);
END;
$$;

-- ============================================================================
-- THE ONE EVENT WRITER (payload-first design §5). Every mutation function appends through here;
-- it is also the foreign-event door: an external/webhook event is _event_append with no projection
-- half. Root-event convention: correlation_id = the event's own id when no correlation is supplied
-- (computed up front — the ledger is append-only, no post-hoc UPDATE).
-- ============================================================================
CREATE FUNCTION _event_append(
    p_type_name text, p_emitter uuid, p_anchor_table text, p_anchor_id uuid,
    p_payload jsonb,
    p_references jsonb DEFAULT '[]'::jsonb,
    p_correlation uuid DEFAULT NULL,
    p_payload_version int DEFAULT 1
) RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_et uuid; v_ev uuid := uuid_generate_v7();
BEGIN
    SELECT id INTO v_et FROM kb_event_types WHERE name = p_type_name;
    IF v_et IS NULL THEN RAISE EXCEPTION 'event_type % not seeded', p_type_name; END IF;
    INSERT INTO kb_events (id, event_type_id, emitter_entity_id,
                           producing_anchor_table, producing_anchor_id,
                           payload, "references", payload_version, correlation_id)
    VALUES (v_ev, v_et, p_emitter, p_anchor_table, p_anchor_id,
            p_payload, p_references, p_payload_version, COALESCE(p_correlation, v_ev));
    RETURN v_ev;
END;
$$;

-- ── relationship_asserted ────────────────────────────────────────────────────
-- Projection half: reads ONLY the payload (RelationshipAsserted, payloads.rs). Projected timestamps
-- come from the event's occurred_at, never now() (replay-stable by construction).
CREATE FUNCTION _project_relationship_asserted(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_edge uuid := (p_payload->>'edge_id')::uuid;
        v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
BEGIN
    INSERT INTO kb_edges (id, source_table, source_id, target_table, target_id,
                          edge_kind, polarity, label, weight,
                          home_anchor_table, home_anchor_id,
                          asserted_by_event_id, last_event_id, created)
    VALUES (v_edge,
            p_payload#>>'{source,table}', (p_payload#>>'{source,id}')::uuid,
            p_payload#>>'{target,table}', (p_payload#>>'{target,id}')::uuid,
            (p_payload->>'edge_kind')::edge_kind,
            COALESCE(p_payload->>'polarity', 'forward')::edge_polarity,
            p_payload->>'label',
            (p_payload->>'weight')::double precision,
            p_payload#>>'{home,table}', (p_payload#>>'{home,id}')::uuid,
            p_event, p_event, v_occurred)
    -- Idempotent on the active-edge invariant (uq_kb_edges_assertion): re-asserting the same active
    -- relationship updates the existing edge's weight (+ last_event_id) and returns ITS id rather than
    -- creating a duplicate active edge. asserted_by_event_id is left on the original assertion. The
    -- ON CONFLICT inference clause mirrors uq_kb_edges_assertion's columns + partial predicate exactly.
    ON CONFLICT (source_table, source_id, target_table, target_id, edge_kind, COALESCE(label, ''),
                 home_anchor_table, home_anchor_id) WHERE NOT is_folded
        DO UPDATE SET weight = EXCLUDED.weight, last_event_id = EXCLUDED.last_event_id
    RETURNING id INTO v_edge;
    RETURN v_edge;
END;
$$;

-- Assert a typed edge, homed per the payload. Emits `relationship_asserted` + projects, one txn.
CREATE FUNCTION relationship_assert(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid;
BEGIN
    v_ev := _event_append('relationship_asserted', p_emitter,
                          p_payload#>>'{home,table}', (p_payload#>>'{home,id}')::uuid, p_payload);
    RETURN _project_relationship_asserted(v_ev, p_payload);
END;
$$;

-- ── relationship_folded ──────────────────────────────────────────────────────
-- Projection half: flips an edge's visibility (is_folded), reads ONLY the payload
-- (RelationshipFolded, payloads.rs). is_folded is the read gate every shape read honors.
CREATE FUNCTION _project_relationship_folded(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_edge uuid := (p_payload->>'edge_id')::uuid;
BEGIN
    UPDATE kb_edges SET is_folded = true, last_event_id = p_event WHERE id = v_edge;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'relationship_fold: edge % not found', v_edge;
    END IF;
    RETURN v_edge;
END;
$$;

-- Fold a declared edge (retire the relationship). The producing anchor is an ENVELOPE concern read
-- from the edge's own home (never payload data) — the same discipline as facet_set.
CREATE FUNCTION relationship_fold(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_edge uuid := (p_payload->>'edge_id')::uuid;
        v_home_tbl text; v_home uuid;
BEGIN
    SELECT home_anchor_table, home_anchor_id INTO v_home_tbl, v_home
        FROM kb_edges WHERE id = v_edge;
    IF v_home IS NULL THEN
        RAISE EXCEPTION 'relationship_fold: edge % not found', v_edge;
    END IF;
    v_ev := _event_append('relationship_folded', p_emitter, v_home_tbl, v_home, p_payload);
    RETURN _project_relationship_folded(v_ev, p_payload);
END;
$$;

-- ── property_asserted ────────────────────────────────────────────────────────
CREATE FUNCTION _project_property_asserted(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_prop uuid := (p_payload->>'property_id')::uuid;
        v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
BEGIN
    INSERT INTO kb_properties (id, owner_table, owner_id, property_key, property_value, weight,
                               asserted_by_event_id, last_event_id, created)
    VALUES (v_prop,
            p_payload#>>'{owner,table}', (p_payload#>>'{owner,id}')::uuid,
            p_payload->>'property_key', p_payload->'value',
            (p_payload->>'weight')::double precision,
            p_event, p_event, v_occurred);
    RETURN v_prop;
END;
$$;

-- Set a property per the payload. Emits `property_asserted`. The producing anchor is an ENVELOPE
-- concern derived from the owner resource's home (cogmap OR context — both in the kb_events CHECK
-- set), preferring a cogmap home — never payload data. A homeless resource is an error.
CREATE FUNCTION facet_set(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_anchor_tbl text; v_anchor uuid;
        v_owner uuid := (p_payload#>>'{owner,id}')::uuid;
BEGIN
    SELECT anchor_table, anchor_id INTO v_anchor_tbl, v_anchor FROM kb_resource_homes
        WHERE resource_id = v_owner ORDER BY (anchor_table='kb_cogmaps') DESC LIMIT 1;
    IF v_anchor IS NULL THEN
        RAISE EXCEPTION 'facet_set: resource % has no home to anchor the property event', v_owner;
    END IF;
    v_ev := _event_append('property_asserted', p_emitter, v_anchor_tbl, v_anchor, p_payload);
    RETURN _project_property_asserted(v_ev, p_payload);
END;
$$;

-- ── block_mutated (content revision) ─────────────────────────────────────────
-- Projection half (BlockMutated, payloads.rs): supersede the block's current chunks, insert the new
-- revision's chunks (re-embedded inline, carried in the sidecar like resource_created), record the
-- revision, bump the block's last_event_id, recompute the resource body_hash merkle. Block-body content
-- is NOT a region-formation input (affinity is declared-only) — this moves a member's embedding, which
-- the downstream SQL readouts (centroid → content_cohesion/telos_alignment) read, without touching any
-- component's membership inputs. Resource body_hash is recomputed from CURRENT visible chunk hashes
-- (ordered by block seq then chunk_index) — a pure function of visible state, so replay reproduces it.
CREATE FUNCTION _project_block_mutated(p_event uuid, p_payload jsonb, p_content jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
        v_block    uuid := (p_payload->>'block_id')::uuid;
        v_resource uuid;
        v_next_ver int;
        v_chunk_json jsonb; v_chunk uuid; v_side jsonb;
        v_chunk_hashes text := ''; v_chunk_count int := 0; v_block_hash text;
BEGIN
    SELECT resource_id INTO v_resource FROM kb_content_blocks WHERE id = v_block;
    IF v_resource IS NULL THEN
        RAISE EXCEPTION '_project_block_mutated: block % not found', v_block;
    END IF;
    -- supersede the prior revision's chunks (is_current is the chunk-currency flag; the rows stay for CAS)
    UPDATE kb_chunks SET is_current = false WHERE block_id = v_block AND is_current;
    SELECT coalesce(max(version), 0) + 1 INTO v_next_ver FROM kb_chunks WHERE block_id = v_block;
    FOR v_chunk_json IN SELECT jsonb_array_elements(p_payload->'chunks') LOOP
        v_chunk := (v_chunk_json->>'chunk_id')::uuid;
        v_side  := p_content->(v_chunk_json->>'chunk_id');
        IF v_side IS NULL THEN
            RAISE EXCEPTION '_project_block_mutated: content sidecar missing chunk %', v_chunk;
        END IF;
        -- revise path: supersedes the prior chunks, so the new run carries v_next_ver + is_current.
        PERFORM _insert_chunk(v_chunk, v_block, v_resource, (v_chunk_json->>'chunk_index')::int,
                              v_next_ver, v_chunk_json->>'content_hash', v_side->'embedding', true,
                              v_side->>'content', v_side->>'header_path',
                              NULLIF(v_side->>'heading_depth','')::smallint, v_occurred);
        v_chunk_hashes := v_chunk_hashes || (v_chunk_json->>'content_hash');
        v_chunk_count := v_chunk_count + 1;
    END LOOP;
    v_block_hash := encode(sha256(convert_to(v_chunk_hashes, 'UTF8')), 'hex');
    INSERT INTO kb_block_revisions (block_id, block_body_hash, chunk_count, created)
        VALUES (v_block, v_block_hash, v_chunk_count, v_occurred);
    UPDATE kb_content_blocks SET last_event_id = p_event WHERE id = v_block;
    -- resource body_hash recomputed from current visible state (the now-superseded chunks excluded).
    PERFORM _recompute_resource_body_hash(v_resource, v_occurred);
    RETURN v_block;
END;
$$;

-- Mutate a block's content (revise its prose). The producing anchor is an ENVELOPE concern derived
-- from the block's resource home (prefer a cogmap home — same discipline as facet_set), never payload
-- data. Emits `block_mutated` + projects, one txn.
CREATE FUNCTION block_mutate(p_payload jsonb, p_content jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_block uuid := (p_payload->>'block_id')::uuid;
        v_resource uuid; v_anchor_tbl text; v_anchor uuid;
BEGIN
    SELECT resource_id INTO v_resource FROM kb_content_blocks WHERE id = v_block;
    IF v_resource IS NULL THEN
        RAISE EXCEPTION 'block_mutate: block % not found', v_block;
    END IF;
    -- An empty chunk set would supersede the block's current chunks and insert none, silently dropping
    -- the member from its region centroid and diverging body_hash from create-path semantics (which has
    -- no empty-body block). Reject before appending an event — a revise must carry content.
    IF p_payload->'chunks' IS NULL OR jsonb_array_length(p_payload->'chunks') = 0 THEN
        RAISE EXCEPTION 'block_mutate: empty chunk set for block % (a revise with no content would drop the block)', v_block;
    END IF;
    SELECT anchor_table, anchor_id INTO v_anchor_tbl, v_anchor FROM kb_resource_homes
        WHERE resource_id = v_resource ORDER BY (anchor_table = 'kb_cogmaps') DESC LIMIT 1;
    IF v_anchor IS NULL THEN
        RAISE EXCEPTION 'block_mutate: resource % has no home to anchor the event', v_resource;
    END IF;
    v_ev := _event_append('block_mutated', p_emitter, v_anchor_tbl, v_anchor, p_payload);
    RETURN _project_block_mutated(v_ev, p_payload, p_content);
END;
$$;

-- ── lens_created ─────────────────────────────────────────────────────────────
CREATE FUNCTION _project_lens_created(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_lens uuid := (p_payload->>'lens_id')::uuid;
        v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
BEGIN
    INSERT INTO kb_cogmap_lenses
        (id, cogmap_id, name, selection_kind,
         w_express, w_contains, w_leads_to, w_near, w_prop,
         s_telos, s_ref, s_central, resolution, asserted_by_event_id, created)
    VALUES (v_lens,
            (p_payload->>'cogmap_id')::uuid,             -- NULL for a global lens
            p_payload->>'name', p_payload->>'selection_kind',
            (p_payload#>>'{weights,express}')::double precision,
            (p_payload#>>'{weights,contains}')::double precision,
            (p_payload#>>'{weights,leads_to}')::double precision,
            (p_payload#>>'{weights,near}')::double precision,
            (p_payload#>>'{weights,prop}')::double precision,
            (p_payload#>>'{salience,telos}')::double precision,
            (p_payload#>>'{salience,ref}')::double precision,
            (p_payload#>>'{salience,central}')::double precision,
            (p_payload->>'resolution')::double precision,
            p_event, v_occurred);
    RETURN v_lens;
END;
$$;

-- Create a lens (global when payload.cogmap_id is absent/null — a system event with no producing
-- anchor, both NULL satisfying the both-null-or-both-set CHECK). Returns the lens id.
CREATE FUNCTION lens_create(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_anchor_tbl text;
BEGIN
    v_anchor_tbl := CASE WHEN p_payload->>'cogmap_id' IS NULL THEN NULL ELSE 'kb_cogmaps' END;
    v_ev := _event_append('lens_created', p_emitter, v_anchor_tbl, (p_payload->>'cogmap_id')::uuid, p_payload);
    RETURN _project_lens_created(v_ev, p_payload);
END;
$$;

-- ── region_materialized ──────────────────────────────────────────────────────
-- Region ROWS are second-order derived compute (clustering output) and stay Rust-side; the
-- projection half records only the act's bookkeeping: the materialization watermark on the cogmap.
-- Replay proof for regions = replay substrate → re-run materialize → fingerprint matches the payload.
CREATE FUNCTION _project_region_materialized(p_event uuid, p_payload jsonb)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE kb_cogmaps SET shape_materialized_event_id = p_event
     WHERE id = (p_payload->>'cogmap_id')::uuid;
END;
$$;

CREATE FUNCTION region_materialize(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid;
BEGIN
    v_ev := _event_append('region_materialized', p_emitter,
                          'kb_cogmaps', (p_payload->>'cogmap_id')::uuid, p_payload);
    PERFORM _project_region_materialized(v_ev, p_payload);
    RETURN v_ev;
END;
$$;

-- ============================================================================
-- WS6 chunk 4c — resource + relationship mutation functions for the live write path.
-- Resource mutations take the envelope from the resource's own home (the facet_set discipline);
-- edge mutations take it from the edge's home (the relationship_fold discipline). Each emits + projects
-- in one txn through _event_append, so replay is the same code path.
-- ============================================================================

-- ── resource_deleted (soft-delete) ───────────────────────────────────────────
CREATE FUNCTION _project_resource_deleted(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_resource uuid := (p_payload->>'resource_id')::uuid;
BEGIN
    UPDATE kb_resources SET is_active = false,
        updated = (SELECT occurred_at FROM kb_events WHERE id = p_event)
        WHERE id = v_resource;
    IF NOT FOUND THEN RAISE EXCEPTION 'resource_delete: resource % not found', v_resource; END IF;
    RETURN v_resource;
END;
$$;

CREATE FUNCTION resource_delete(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_resource uuid := (p_payload->>'resource_id')::uuid;
        v_anchor_tbl text; v_anchor uuid;
BEGIN
    SELECT anchor_table, anchor_id INTO v_anchor_tbl, v_anchor FROM kb_resource_homes
        WHERE resource_id = v_resource ORDER BY (anchor_table='kb_cogmaps') DESC LIMIT 1;
    IF v_anchor IS NULL THEN RAISE EXCEPTION 'resource_delete: resource % has no home', v_resource; END IF;
    v_ev := _event_append('resource_deleted', p_emitter, v_anchor_tbl, v_anchor, p_payload);
    RETURN _project_resource_deleted(v_ev, p_payload);
END;
$$;

-- ── resource_updated (mutable kb_resources columns) ──────────────────────────
-- COALESCE keeps an unset field at its current value — the payload carries only the changed columns.
CREATE FUNCTION _project_resource_updated(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_resource uuid := (p_payload->>'resource_id')::uuid;
BEGIN
    UPDATE kb_resources SET
        title      = COALESCE(p_payload->>'title', title),
        origin_uri = COALESCE(p_payload->>'origin_uri', origin_uri),
        updated    = (SELECT occurred_at FROM kb_events WHERE id = p_event)
        WHERE id = v_resource;
    IF NOT FOUND THEN RAISE EXCEPTION 'resource_update: resource % not found', v_resource; END IF;
    RETURN v_resource;
END;
$$;

CREATE FUNCTION resource_update(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_resource uuid := (p_payload->>'resource_id')::uuid;
        v_anchor_tbl text; v_anchor uuid;
BEGIN
    SELECT anchor_table, anchor_id INTO v_anchor_tbl, v_anchor FROM kb_resource_homes
        WHERE resource_id = v_resource ORDER BY (anchor_table='kb_cogmaps') DESC LIMIT 1;
    IF v_anchor IS NULL THEN RAISE EXCEPTION 'resource_update: resource % has no home', v_resource; END IF;
    v_ev := _event_append('resource_updated', p_emitter, v_anchor_tbl, v_anchor, p_payload);
    RETURN _project_resource_updated(v_ev, p_payload);
END;
$$;

-- ── resource_rehomed (context move) ──────────────────────────────────────────
-- Re-point the resource's single home row to the destination anchor. The event envelope is the
-- DESTINATION home (post-move, that is where the resource lives) — read from the payload, not the row.
CREATE FUNCTION _project_resource_rehomed(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_resource uuid := (p_payload->>'resource_id')::uuid;
BEGIN
    UPDATE kb_resource_homes SET
        anchor_table = p_payload#>>'{home,table}',
        anchor_id    = (p_payload#>>'{home,id}')::uuid
        WHERE resource_id = v_resource;
    IF NOT FOUND THEN RAISE EXCEPTION 'resource_rehome: resource % has no home', v_resource; END IF;
    RETURN v_resource;
END;
$$;

CREATE FUNCTION resource_rehome(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid;
BEGIN
    v_ev := _event_append('resource_rehomed', p_emitter,
                          p_payload#>>'{home,table}', (p_payload#>>'{home,id}')::uuid, p_payload);
    RETURN _project_resource_rehomed(v_ev, p_payload);
END;
$$;

-- ── property_set (single-valued upsert) ──────────────────────────────────────
-- Fold prior ACTIVE rows for (owner, property_key) then insert the new value, so a single-valued key
-- (the resource-frontmatter shape) holds exactly one current row. Distinct from facet_set/
-- property_asserted (append — the multi-valued facet shape). Replay-safe: deterministic from payload.
CREATE FUNCTION _project_property_set(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_prop uuid := (p_payload->>'property_id')::uuid;
        v_occurred timestamptz := (SELECT occurred_at FROM kb_events WHERE id = p_event);
        v_owner_tbl text := p_payload#>>'{owner,table}';
        v_owner uuid := (p_payload#>>'{owner,id}')::uuid;
        v_key text := p_payload->>'property_key';
BEGIN
    UPDATE kb_properties SET is_folded = true, last_event_id = p_event
        WHERE owner_table = v_owner_tbl AND owner_id = v_owner
          AND property_key = v_key AND NOT is_folded;
    INSERT INTO kb_properties (id, owner_table, owner_id, property_key, property_value, weight,
                               asserted_by_event_id, last_event_id, created)
    VALUES (v_prop, v_owner_tbl, v_owner, v_key, p_payload->'value',
            (p_payload->>'weight')::double precision, p_event, p_event, v_occurred);
    RETURN v_prop;
END;
$$;

-- Envelope = the owner resource's home (the facet_set discipline). A homeless owner is an error.
CREATE FUNCTION property_set(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_anchor_tbl text; v_anchor uuid;
        v_owner uuid := (p_payload#>>'{owner,id}')::uuid;
BEGIN
    SELECT anchor_table, anchor_id INTO v_anchor_tbl, v_anchor FROM kb_resource_homes
        WHERE resource_id = v_owner ORDER BY (anchor_table='kb_cogmaps') DESC LIMIT 1;
    IF v_anchor IS NULL THEN
        RAISE EXCEPTION 'property_set: resource % has no home to anchor the property event', v_owner;
    END IF;
    v_ev := _event_append('property_set', p_emitter, v_anchor_tbl, v_anchor, p_payload);
    RETURN _project_property_set(v_ev, p_payload);
END;
$$;

-- ── relationship_retyped (edge_kind / polarity) ──────────────────────────────
CREATE FUNCTION _project_relationship_retyped(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_edge uuid := (p_payload->>'edge_id')::uuid;
BEGIN
    UPDATE kb_edges SET
        edge_kind = (p_payload->>'edge_kind')::edge_kind,
        polarity  = (p_payload->>'polarity')::edge_polarity,
        last_event_id = p_event
        WHERE id = v_edge;
    IF NOT FOUND THEN RAISE EXCEPTION 'relationship_retype: edge % not found', v_edge; END IF;
    RETURN v_edge;
END;
$$;

CREATE FUNCTION relationship_retype(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_edge uuid := (p_payload->>'edge_id')::uuid;
        v_home_tbl text; v_home uuid;
BEGIN
    SELECT home_anchor_table, home_anchor_id INTO v_home_tbl, v_home FROM kb_edges WHERE id = v_edge;
    IF v_home IS NULL THEN RAISE EXCEPTION 'relationship_retype: edge % not found', v_edge; END IF;
    v_ev := _event_append('relationship_retyped', p_emitter, v_home_tbl, v_home, p_payload);
    RETURN _project_relationship_retyped(v_ev, p_payload);
END;
$$;

-- ── relationship_reweighted (weight) ─────────────────────────────────────────
CREATE FUNCTION _project_relationship_reweighted(p_event uuid, p_payload jsonb)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_edge uuid := (p_payload->>'edge_id')::uuid;
BEGIN
    UPDATE kb_edges SET weight = (p_payload->>'weight')::double precision, last_event_id = p_event
        WHERE id = v_edge;
    IF NOT FOUND THEN RAISE EXCEPTION 'relationship_reweight: edge % not found', v_edge; END IF;
    RETURN v_edge;
END;
$$;

CREATE FUNCTION relationship_reweight(p_payload jsonb, p_emitter uuid)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_ev uuid; v_edge uuid := (p_payload->>'edge_id')::uuid;
        v_home_tbl text; v_home uuid;
BEGIN
    SELECT home_anchor_table, home_anchor_id INTO v_home_tbl, v_home FROM kb_edges WHERE id = v_edge;
    IF v_home IS NULL THEN RAISE EXCEPTION 'relationship_reweight: edge % not found', v_edge; END IF;
    v_ev := _event_append('relationship_reweighted', p_emitter, v_home_tbl, v_home, p_payload);
    RETURN _project_relationship_reweighted(v_ev, p_payload);
END;
$$;

-- ============================================================================
-- End of 02_functions.sql. Seed → 03_seed.sql; scenarios → 04_scenarios.sql.
-- ============================================================================
