-- Canonical system boot-seed (spec §2): what any temper system needs. Namespace-free —
-- every statement resolves against the connection-default schema (`public` in production;
-- ephemeral `public`-schema databases via `#[sqlx::test]` in artifact tests). Mirrors
-- temper_substrate::scenario::bootseed::seed_system, translated to a plain migration.

-- 1. The canonical system actor. Events require a NOT NULL emitter. kb_profiles.handle is UNIQUE;
--    kb_entities has no unique constraint on (profile_id, name), so mirror bootseed's
--    SELECT-then-INSERT existence check instead of ON CONFLICT.
INSERT INTO kb_profiles (handle, display_name, system_access)
VALUES ('system', 'System', 'admin')
ON CONFLICT (handle) DO UPDATE SET display_name = EXCLUDED.display_name;

INSERT INTO kb_entities (profile_id, name, metadata)
SELECT p.id, 'system', '{}'::jsonb
  FROM kb_profiles p
 WHERE p.handle = 'system'
   AND NOT EXISTS (
       SELECT 1 FROM kb_entities e WHERE e.profile_id = p.id AND e.name = 'system'
   );

-- 2. The access-gate settings row (id = 1 CHECK). Without it has_system_access / is_system_admin
--    read an empty CTE and return NULL (spec §2, item 4) — the access gate fails closed-as-NULL.
INSERT INTO kb_system_settings (id, access_mode) VALUES (1, 'open')
ON CONFLICT (id) DO NOTHING;

-- 3. The event-type registry (27 names from schema-artifact/seeds/system.yaml, in order).
--    payload_schema is inlined verbatim from the committed payloads/<name>.v1.schema.json
--    snapshots (registry==repo contract); a name with no snapshot stays NULL (permissive),
--    exactly as bootseed leaves it. schema_version = 1.
INSERT INTO kb_event_types (name, payload_schema, schema_version) VALUES
  ('resource_created', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"ResourceCreated","type":"object","properties":{"resource_id":{"$ref":"#/$defs/ResourceId"},"title":{"type":"string"},"origin_uri":{"type":"string"},"home":{"$ref":"#/$defs/AnchorRef"},"owner_profile_id":{"$ref":"#/$defs/ProfileId"},"originator_profile_id":{"description":"The home's originator (\u00a72: \"carrying its current originator/owner\"). Absent \u21d2 the projector\nCOALESCEs it to `owner_profile_id` (the scenario path, where originator\u2261owner). Synthesis sets\nit explicitly so a production row whose originator differs from its owner survives the carry.","anyOf":[{"$ref":"#/$defs/ProfileId"},{"type":"null"}]},"doc_type":{"type":["string","null"]},"blocks":{"type":"array","items":{"$ref":"#/$defs/BlockManifest"}}},"required":["resource_id","title","origin_uri","home","owner_profile_id","blocks"],"$defs":{"ResourceId":{"description":"A `kb_resources` row (the named, edge-connected, findable unit).","type":"string","format":"uuid"},"AnchorRef":{"type":"object","properties":{"table":{"$ref":"#/$defs/AnchorTable"},"id":{"type":"string","format":"uuid"}},"required":["table","id"]},"AnchorTable":{"description":"A polymorphic anchor/endpoint reference. Serializes table names exactly as the DDL spells them.","type":"string","enum":["kb_contexts","kb_cogmaps","kb_resources","kb_edges","kb_content_blocks","kb_teams","kb_profiles"]},"ProfileId":{"description":"A `kb_profiles` row (the owner/actor principal).","type":"string","format":"uuid"},"BlockManifest":{"description":"One block's manifest. `block_body_hash` deliberately absent \u2014 it is sha256(ordered chunk hashes),\nderived in the projector (the derived-state rule applied to the spec's own \u00a73 sketch).","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"seq":{"type":"integer","format":"int32"},"role":{"type":["string","null"]},"chunks":{"type":"array","items":{"$ref":"#/$defs/ChunkManifest"}}},"required":["block_id","seq","chunks"]},"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"},"ChunkManifest":{"description":"Content-addressed chunk reference: structure + hash, NEVER prose (CAS rule, spec \u00a70.1).","type":"object","properties":{"chunk_id":{"$ref":"#/$defs/ChunkId"},"chunk_index":{"type":"integer","format":"int32"},"content_hash":{"type":"string"}},"required":["chunk_id","chunk_index","content_hash"]},"ChunkId":{"description":"A `kb_chunks` row (one embedding window of a block's prose).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('resource_updated', NULL, 1),
  ('resource_deleted', NULL, 1),
  ('resource_rehomed', NULL, 1),
  ('relationship_asserted', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipAsserted","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"source":{"$ref":"#/$defs/AnchorRef"},"target":{"$ref":"#/$defs/AnchorRef"},"edge_kind":{"$ref":"#/$defs/EdgeKind"},"polarity":{"$ref":"#/$defs/EdgePolarity","default":"forward"},"label":{"type":["string","null"]},"weight":{"type":"number","format":"double"},"home":{"$ref":"#/$defs/AnchorRef"}},"required":["edge_id","source","target","edge_kind","weight","home"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"},"AnchorRef":{"type":"object","properties":{"table":{"$ref":"#/$defs/AnchorTable"},"id":{"type":"string","format":"uuid"}},"required":["table","id"]},"AnchorTable":{"description":"A polymorphic anchor/endpoint reference. Serializes table names exactly as the DDL spells them.","type":"string","enum":["kb_contexts","kb_cogmaps","kb_resources","kb_edges","kb_content_blocks","kb_teams","kb_profiles"]},"EdgeKind":{"type":"string","enum":["express","contains","leads_to","near"]},"EdgePolarity":{"description":"kb_edges.polarity. The projection's only non-parameter column today \u2014 carried explicitly so the\npayload covers every projected column (spec \u00a79 column-coverage obligation).","type":"string","enum":["forward","inverse"]}}}$js$::jsonb, 1),
  ('relationship_retracted', NULL, 1),
  ('relationship_retyped', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipRetyped","description":"Mirrors production `temper-core/src/types/relationship_events.rs` + `edge_id` (identity-as-input).","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"edge_kind":{"$ref":"#/$defs/EdgeKind"},"polarity":{"$ref":"#/$defs/EdgePolarity"}},"required":["edge_id","edge_kind","polarity"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"},"EdgeKind":{"type":"string","enum":["express","contains","leads_to","near"]},"EdgePolarity":{"description":"kb_edges.polarity. The projection's only non-parameter column today \u2014 carried explicitly so the\npayload covers every projected column (spec \u00a79 column-coverage obligation).","type":"string","enum":["forward","inverse"]}}}$js$::jsonb, 1),
  ('relationship_reweighted', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipReweighted","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"weight":{"type":"number","format":"double"}},"required":["edge_id","weight"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('relationship_folded', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipFolded","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"reason":{"type":["string","null"]}},"required":["edge_id"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('relationship_decayed', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipDecayed","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"factor":{"description":"Multiplicative decay factor applied to the edge weight (0.0..1.0) \u2014 production's shape.","type":"number","format":"double"}},"required":["edge_id","factor"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('relationship_corrected', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RelationshipCorrected","type":"object","properties":{"edge_id":{"$ref":"#/$defs/EdgeId"},"scar":{"description":"Structured account of the wrongness \u2014 the scar (production's shape).","type":"string"}},"required":["edge_id","scar"],"$defs":{"EdgeId":{"description":"A `kb_edges` row (a declared relationship assertion).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('property_asserted', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"PropertyAsserted","type":"object","properties":{"property_id":{"$ref":"#/$defs/PropertyId"},"owner":{"$ref":"#/$defs/AnchorRef"},"property_key":{"type":"string"},"value":true,"weight":{"type":"number","format":"double"}},"required":["property_id","owner","property_key","value","weight"],"$defs":{"PropertyId":{"description":"A `kb_properties` row (a facet/doc_type/block_role assertion).","type":"string","format":"uuid"},"AnchorRef":{"type":"object","properties":{"table":{"$ref":"#/$defs/AnchorTable"},"id":{"type":"string","format":"uuid"}},"required":["table","id"]},"AnchorTable":{"description":"A polymorphic anchor/endpoint reference. Serializes table names exactly as the DDL spells them.","type":"string","enum":["kb_contexts","kb_cogmaps","kb_resources","kb_edges","kb_content_blocks","kb_teams","kb_profiles"]}}}$js$::jsonb, 1),
  ('property_set', NULL, 1),
  ('property_retracted', NULL, 1),
  ('property_reweighted', NULL, 1),
  ('property_folded', NULL, 1),
  ('block_created', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"BlockCreated","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"resource_id":{"$ref":"#/$defs/ResourceId"},"seq":{"type":"integer","format":"int32"}},"required":["block_id","resource_id","seq"],"$defs":{"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"},"ResourceId":{"description":"A `kb_resources` row (the named, edge-connected, findable unit).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('block_mutated', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"BlockMutated","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"chunks":{"type":"array","items":{"$ref":"#/$defs/ChunkManifest"}},"incorporated":{"type":"array","items":{"$ref":"#/$defs/Incorporation"},"default":[]}},"required":["block_id","chunks"],"$defs":{"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"},"ChunkManifest":{"description":"Content-addressed chunk reference: structure + hash, NEVER prose (CAS rule, spec \u00a70.1).","type":"object","properties":{"chunk_id":{"$ref":"#/$defs/ChunkId"},"chunk_index":{"type":"integer","format":"int32"},"content_hash":{"type":"string"}},"required":["chunk_id","chunk_index","content_hash"]},"ChunkId":{"description":"A `kb_chunks` row (one embedding window of a block's prose).","type":"string","format":"uuid"},"Incorporation":{"type":"object","properties":{"source":{"$ref":"#/$defs/ProvenanceSource"},"seq":{"type":"integer","format":"int32"}},"required":["source","seq"]},"ProvenanceSource":{"description":"Tagged like the DDL's provenance_source_kind ({kind, value} sum \u2014 content-block spec).","oneOf":[{"type":"object","properties":{"kind":{"type":"string","const":"event"},"value":{"type":"string","format":"uuid"}},"required":["kind","value"]},{"type":"object","properties":{"kind":{"type":"string","const":"resource"},"value":{"type":"string","format":"uuid"}},"required":["kind","value"]}]}}}$js$::jsonb, 1),
  ('block_folded', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"BlockFolded","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"reason":{"type":["string","null"]}},"required":["block_id"],"$defs":{"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('block_provenance_corrected', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"BlockProvenanceCorrected","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"source":{"$ref":"#/$defs/ProvenanceSource"},"scar":{"type":"string"}},"required":["block_id","source","scar"],"$defs":{"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"},"ProvenanceSource":{"description":"Tagged like the DDL's provenance_source_kind ({kind, value} sum \u2014 content-block spec).","oneOf":[{"type":"object","properties":{"kind":{"type":"string","const":"event"},"value":{"type":"string","format":"uuid"}},"required":["kind","value"]},{"type":"object","properties":{"kind":{"type":"string","const":"resource"},"value":{"type":"string","format":"uuid"}},"required":["kind","value"]}]}}}$js$::jsonb, 1),
  ('grant_created', NULL, 1),
  ('grant_revoked', NULL, 1),
  ('cogmap_seeded', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"CogmapSeeded","type":"object","properties":{"cogmap_id":{"$ref":"#/$defs/CogmapId"},"name":{"type":"string"},"owner_profile_id":{"$ref":"#/$defs/ProfileId"},"telos":{"$ref":"#/$defs/TelosManifest"}},"required":["cogmap_id","name","owner_profile_id","telos"],"$defs":{"CogmapId":{"description":"A `kb_cogmaps` row.","type":"string","format":"uuid"},"ProfileId":{"description":"A `kb_profiles` row (the owner/actor principal).","type":"string","format":"uuid"},"TelosManifest":{"type":"object","properties":{"resource_id":{"$ref":"#/$defs/ResourceId"},"title":{"type":"string"},"origin_uri":{"type":"string"},"blocks":{"type":"array","items":{"$ref":"#/$defs/BlockManifest"}}},"required":["resource_id","title","origin_uri","blocks"]},"ResourceId":{"description":"A `kb_resources` row (the named, edge-connected, findable unit).","type":"string","format":"uuid"},"BlockManifest":{"description":"One block's manifest. `block_body_hash` deliberately absent \u2014 it is sha256(ordered chunk hashes),\nderived in the projector (the derived-state rule applied to the spec's own \u00a73 sketch).","type":"object","properties":{"block_id":{"$ref":"#/$defs/BlockId"},"seq":{"type":"integer","format":"int32"},"role":{"type":["string","null"]},"chunks":{"type":"array","items":{"$ref":"#/$defs/ChunkManifest"}}},"required":["block_id","seq","chunks"]},"BlockId":{"description":"A `kb_content_blocks` row (a resource's addressable interior unit).","type":"string","format":"uuid"},"ChunkManifest":{"description":"Content-addressed chunk reference: structure + hash, NEVER prose (CAS rule, spec \u00a70.1).","type":"object","properties":{"chunk_id":{"$ref":"#/$defs/ChunkId"},"chunk_index":{"type":"integer","format":"int32"},"content_hash":{"type":"string"}},"required":["chunk_id","chunk_index","content_hash"]},"ChunkId":{"description":"A `kb_chunks` row (one embedding window of a block's prose).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('region_materialized', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"RegionMaterialized","type":"object","properties":{"cogmap_id":{"$ref":"#/$defs/CogmapId"},"lens_id":{"$ref":"#/$defs/LensId"},"watermark_event_id":{"description":"Max event id over the substrate at load time \u2014 the point-in-time the projection saw.","$ref":"#/$defs/EventId"},"membership_fingerprint":{"description":"The per-lens membership signature (sorted member-uuid join). Doubles as the drift-detection\ndecision's persisted fingerprint artifact.","type":"string"},"region_ids":{"type":"array","items":{"$ref":"#/$defs/RegionId"}}},"required":["cogmap_id","lens_id","watermark_event_id","membership_fingerprint","region_ids"],"$defs":{"CogmapId":{"description":"A `kb_cogmaps` row.","type":"string","format":"uuid"},"LensId":{"description":"A `kb_cogmap_lenses` row.","type":"string","format":"uuid"},"EventId":{"description":"A `kb_events` row (a ledger event).","type":"string","format":"uuid"},"RegionId":{"description":"A `kb_cogmap_regions` row (one materialized region).","type":"string","format":"uuid"}}}$js$::jsonb, 1),
  ('delegated_launch', NULL, 1),
  ('invocation_closed', NULL, 1),
  ('lens_created', $js${"$schema":"https://json-schema.org/draft/2020-12/schema","title":"LensCreated","type":"object","properties":{"lens_id":{"$ref":"#/$defs/LensId"},"cogmap_id":{"anyOf":[{"$ref":"#/$defs/CogmapId"},{"type":"null"}]},"name":{"type":"string"},"selection_kind":{"type":"string"},"weights":{"$ref":"#/$defs/LensWeights"},"salience":{"$ref":"#/$defs/SalienceWeights"},"resolution":{"type":"number","format":"double"}},"required":["lens_id","name","selection_kind","weights","salience","resolution"],"$defs":{"LensId":{"description":"A `kb_cogmap_lenses` row.","type":"string","format":"uuid"},"CogmapId":{"description":"A `kb_cogmaps` row.","type":"string","format":"uuid"},"LensWeights":{"type":"object","properties":{"express":{"type":"number","format":"double"},"contains":{"type":"number","format":"double"},"leads_to":{"type":"number","format":"double"},"near":{"type":"number","format":"double"},"prop":{"type":"number","format":"double"}},"required":["express","contains","leads_to","near","prop"]},"SalienceWeights":{"type":"object","properties":{"telos":{"type":"number","format":"double"},"ref":{"type":"number","format":"double"},"central":{"type":"number","format":"double"}},"required":["telos","ref","central"]}}}$js$::jsonb, 1)
ON CONFLICT (name) DO UPDATE
  SET payload_schema = EXCLUDED.payload_schema, schema_version = EXCLUDED.schema_version;

-- 4. The 2 global system lenses (cogmap_id NULL = global), event-sourced via lens_create and
--    attributed to the system entity. lens_create(p_payload jsonb, p_emitter uuid): a NESTED
--    jsonb payload (NOT positional weights). _project_lens_created reads lens_id (minted here),
--    cogmap_id, name, selection_kind ('homed' — bootseed value + column default),
--    weights{express,contains,leads_to,near,prop}, salience{telos,ref,central}, resolution.
--    The salience key the projector reads is `ref` (not `reference`). Weight values are the EXACT
--    vectors from system.yaml (telos-default lines :38, telos-default-propheavy :39).
SELECT lens_create(
  jsonb_build_object(
    'lens_id',        uuid_generate_v7(),
    'cogmap_id',      NULL,
    'name',           'telos-default',
    'selection_kind', 'homed',
    'weights',  jsonb_build_object('express', 1.0, 'contains', 1.0, 'leads_to', 0.6, 'near', 0.3, 'prop', 0.4),
    'salience', jsonb_build_object('telos', 0.5, 'ref', 0.3, 'central', 0.2),
    'resolution',     0.5
  ),
  (SELECT e.id FROM kb_entities e JOIN kb_profiles p ON p.id = e.profile_id
    WHERE p.handle = 'system' AND e.name = 'system')
);

SELECT lens_create(
  jsonb_build_object(
    'lens_id',        uuid_generate_v7(),
    'cogmap_id',      NULL,
    'name',           'telos-default-propheavy',
    'selection_kind', 'homed',
    'weights',  jsonb_build_object('express', 1.0, 'contains', 1.0, 'leads_to', 0.1, 'near', 0.3, 'prop', 1.2),
    'salience', jsonb_build_object('telos', 0.5, 'ref', 0.3, 'central', 0.2),
    'resolution',     0.5
  ),
  (SELECT e.id FROM kb_entities e JOIN kb_profiles p ON p.id = e.profile_id
    WHERE p.handle = 'system' AND e.name = 'system')
);
