-- Phase 6 — Canonical managed_meta keys + date move.
--
-- Brings legacy kb_resource_manifests rows into the canonical shape established
-- by Phases 1 + 5: rename bare `title`/`slug` to `temper-title`/`temper-slug`,
-- move `date` from managed_meta to open_meta for session/research/decision/
-- concept rows, and reset affected hashes to the empty-string sentinel so
-- Phase 5's receive-side wiring re-stamps them on next sync push.
--
-- See: docs/superpowers/specs/2026-05-05-managed-meta-phase6-canonical-data-migration-design.md
-- See: docs/superpowers/plans/2026-05-05-managed-meta-phase6-canonical-data-migration.md
--
-- Idempotent: re-running this migration is safe. Each UPDATE has a guard
-- predicate that skips already-canonical rows. Migration B (separate file,
-- generated by examples/phase6_recompute_hashes.rs) restores correct hashes.

BEGIN;

-- 1a. Rename `title` -> `temper-title` (bare key only).
UPDATE kb_resource_manifests
SET managed_meta = (managed_meta - 'title')
                || jsonb_build_object('temper-title', managed_meta->'title'),
    managed_hash = ''
WHERE managed_meta ? 'title'
  AND NOT (managed_meta ? 'temper-title');

-- 1b. Drop bare `title` if both forms coexist (canonical key wins).
UPDATE kb_resource_manifests
SET managed_meta = managed_meta - 'title',
    managed_hash = ''
WHERE managed_meta ? 'title'
  AND managed_meta ? 'temper-title';

-- 2a. Rename `slug` -> `temper-slug` (bare key only).
UPDATE kb_resource_manifests
SET managed_meta = (managed_meta - 'slug')
                || jsonb_build_object('temper-slug', managed_meta->'slug'),
    managed_hash = ''
WHERE managed_meta ? 'slug'
  AND NOT (managed_meta ? 'temper-slug');

-- 2b. Drop bare `slug` if both forms coexist (canonical key wins).
UPDATE kb_resource_manifests
SET managed_meta = managed_meta - 'slug',
    managed_hash = ''
WHERE managed_meta ? 'slug'
  AND managed_meta ? 'temper-slug';

-- 3a. Move `date` from managed_meta to open_meta for dated doctypes.
UPDATE kb_resource_manifests m
SET open_meta    = m.open_meta || jsonb_build_object('date', m.managed_meta->'date'),
    managed_meta = m.managed_meta - 'date',
    managed_hash = '',
    open_hash    = ''
FROM kb_resources r
JOIN kb_doc_types dt ON dt.id = r.kb_doc_type_id
WHERE m.resource_id = r.id
  AND dt.name IN ('session', 'research', 'decision', 'concept')
  AND m.managed_meta ? 'date'
  AND NOT (m.open_meta ? 'date');

-- 3b. Drop `date` from managed_meta if open_meta already has one (defensive).
UPDATE kb_resource_manifests m
SET managed_meta = m.managed_meta - 'date',
    managed_hash = ''
FROM kb_resources r
JOIN kb_doc_types dt ON dt.id = r.kb_doc_type_id
WHERE m.resource_id = r.id
  AND dt.name IN ('session', 'research', 'decision', 'concept')
  AND m.managed_meta ? 'date'
  AND m.open_meta ? 'date';

COMMIT;
