//! Phase 6 — one-shot hash-recompute helper. Throwaway.
//!
//! Connects to the database via DATABASE_URL, walks every row in
//! kb_resource_manifests, computes managed_hash + open_hash via
//! temper_core::hash, and emits a static `UPDATE`-per-row SQL script
//! to stdout for capture into Migration B.
//!
//! Usage:
//!   DATABASE_URL=postgresql://... \
//!     cargo run --example phase6_recompute_hashes -p temper-api \
//!     > migrations/<TIMESTAMP>_managed_meta_recompute_hashes.sql
//!
//! Run AFTER Migration A has been applied to the target database (locally
//! against a snapshot of prod, or directly against prod read-replica).
//!
//! Removed in cleanup commit after Migration B validates on remote.

use serde_json::Value;
use sqlx::postgres::PgPoolOptions;
use temper_core::hash::{compute_managed_hash, compute_open_hash};
use uuid::Uuid;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");

    let pool = PgPoolOptions::new()
        .max_connections(2)
        .connect(&database_url)
        .await?;

    // Runtime query (not the `sqlx::query!` macro): `cargo sqlx prepare`'s
    // `cargo check` pass doesn't include examples, so the macro has no cache
    // entry under SQLX_OFFLINE=true and CI fails. This helper is throwaway
    // and runs against a real DB anyway — no compile-time cross-check needed.
    let rows: Vec<(Uuid, Value, Value, String)> = sqlx::query_as(
        r#"
        SELECT m.resource_id, m.managed_meta, m.open_meta, dt.name
        FROM kb_resource_manifests m
        JOIN kb_resources r       ON r.id = m.resource_id
        JOIN kb_doc_types dt      ON dt.id = r.kb_doc_type_id
        ORDER BY m.resource_id
        "#,
    )
    .fetch_all(&pool)
    .await?;

    let now = chrono::Utc::now().to_rfc3339();
    println!("-- Phase 6 — Migration B: recompute managed_hash + open_hash.");
    println!("--");
    println!("-- Generated by crates/temper-api/examples/phase6_recompute_hashes.rs");
    println!("-- Generated at: {}", now);
    println!("-- Source rows: {}", rows.len());
    println!("--");
    println!("-- Run AFTER Migration A. Each UPDATE matches a row by resource_id and");
    println!("-- writes the canonical managed_hash + open_hash for that row's current");
    println!("-- (post-Migration-A) JSONB shape, computed via temper_core::hash.");
    println!("--");
    println!("-- Any row added/updated between this generation time and deploy time");
    println!("-- will retain the empty-string hash sentinel from Migration A; the");
    println!("-- next `temper sync run` push re-stamps it via Phase 5 receive-side.");
    println!();
    println!("BEGIN;");
    println!();

    for (resource_id, managed_meta, open_meta, doc_type) in &rows {
        let managed_hash = compute_managed_hash(doc_type, managed_meta);
        let open_hash = compute_open_hash(open_meta);
        println!(
            "UPDATE kb_resource_manifests SET managed_hash = '{managed_hash}', open_hash = '{open_hash}' WHERE resource_id = '{resource_id}';",
        );
    }

    println!();
    println!("COMMIT;");

    eprintln!("Emitted {} UPDATEs.", rows.len());
    Ok(())
}
