#!/usr/bin/env bash
# Emits the run-once additive install migration from the shared artifact body. Single source of truth:
# schema-artifact/01_schema.sql (body, no DROP) + 02_functions.sql. Output is deterministic, so the
# drift guard (crates/temper-next/tests/schema_drift.rs) can compare `--stdout` against the committed
# file byte-for-byte. Both branches below emit the SAME bytes via `emit()`.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ART="$ROOT/schema-artifact"
# Fixed install-migration path — regenerated in place; never timestamp-derived (so the drift guard
# compares against a stable target).
OUT="$ROOT/migrations/20260613000001_install_temper_next.sql"
emit() {
  printf -- '-- GENERATED by tools/gen-install-migration.sh — do not edit by hand.\n'
  printf -- '-- Source of truth: schema-artifact/01_schema.sql + 02_functions.sql.\n'
  printf -- '-- Additive, run-once: creates the temper_next namespace alongside public (WS6 chunk 2, §D).\n\n'
  printf -- 'CREATE SCHEMA temper_next;\nSET search_path TO temper_next, public;\n\n'
  # 01_schema.sql already had its DROP/CREATE/SET removed (Task 1 Step 3); strip any residual SET search_path.
  grep -vE '^SET search_path' "$ART/01_schema.sql"
  printf -- '\n'
  grep -vE '^SET search_path' "$ART/02_functions.sql"
}
if [[ "${1:-}" == "--stdout" ]]; then
  emit
else
  emit > "$OUT"
fi
